### ISSUE TITLE
[feature] Allow custom pipeline input parameter types

### ISSUE THREAD

**Issue by robertschweizer** [kubeflow/pipelines#10145]
### Feature Area

/area sdk

### What feature would you like to see?

Currently, using the v2 Python SDK, this pipeline

```py
@dsl.pipeline
def _pipeline_func(
    str_param: str,
):
    ...
```

leads to these `inputDefinitions:` in the compiled YAML:

```yaml
  inputDefinitions:
    parameters:
      str_param:
        parameterType: STRING
```

I would like subtypes of currently supported types to be allowed as well, and their names stored. E.g.

```py
class InputVectorAnnotationSet(str):
    """The ID of a vector annotation set."""

class InputRasterAnnotationSet(str):
    """The ID of a raster annotation set."""

@dsl.pipeline
def _pipeline_func(
    input_vector_annos: InputVectorAnnotationSet,  # Leads to compilation error
    input_raster_annos: InputRasterAnnotationSet,  # Leads to compilation error
    mode: Literal["strict", "auto", "free"],  # Leads to compilation error
):
    ...
```

should lead to a YAML file that contains all the provided information. This could look like here:

```yaml
  inputDefinitions:
    parameters:
      input_vector_annos:
        parameterType: STRING
        pythonType: InputVectorAnnotationSet
      input_raster_annos:
        parameterType: STRING
        pythonType: InputRasterAnnotationSet
      mode:
        parameterType: STRING
        pythonType: 'Literal["strict", "auto", "free"]'
```

### What is the use case or pain point?

We have a custom UI for submission. To submit a specific pipeline, it gets the pipeline spec from Kubeflow. Based on the input parameter metadata in the pipeline spec, it lets users select input data based on the type annotation. For example, for an `InputVectorAnnotationSet` input, only vector annotation sets can be selected. The selector can also be smart allow selecting the input by date/name, and finally send the selected ID to Kubeflow.

I guess this is a bit of a niche use-case. Would a PR adding the extra information to the compiled YAML file be accepted?

### Is there a workaround currently?

We currently use the v1 Python SDK to compile pipeline. It includes more type information in the YAML file than the v2 SDK, and does not fail during compilation. But it would be nice to upgrade to v2 soon.

---

Love this idea? Give it a 👍.
