### ISSUE TITLE
Duplicate entry for key 'Execution.UniqueExecutionTypeName' Error

### ISSUE THREAD

**Issue by hexiaoliangRick** [kubeflow/pipelines#10406]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

        Standalone Deployment
*  KFP version: 
    ### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

         Standalone Deployment
*  KFP version: 
    
        v2.0.5

*  KFP SDK version: 

        kfp-2.6.0

### Steps to reproduce
- create a pipeline yaml，and create a pipeline in web ui
```
components:
  comp-say-hello:
    executorLabel: exec-say-hello
deploymentSpec:
  executors:
    exec-say-hello:
      container:
        args:
          - Hello
        command:
          - echo
        image: alpine
pipelineInfo:
  name: say-hello-pipeline
root:
  dag:
    tasks:
      say-hello:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-say-hello
        taskInfo:
          name: say-hello
schemaVersion: 2.1.0
sdkVersion: kfp-2.6.0

```
- create a run with the pipeline.

- when the run executed,it produce a  error
![image](https://github.com/kubeflow/pipelines/assets/54734710/4cb8e9cb-cb04-48ba-98ed-7fe2311f432d)
![image](https://github.com/kubeflow/pipelines/assets/54734710/8c02672c-da59-4b63-912a-40cb652b7b43)

### Expected result
    exuecut a run with success result.

 

 

 

---

Impacted by this bug? Give it a 👍.
