### ISSUE TITLE
[Help] I want to add input argument in image name of YAML file component, but it can't be parsed in Kubeflow pipeline

### ISSUE THREAD

**Issue by stevezkw1998** [kubeflow/pipelines#10520]
I `load_component_from_file` from a yaml file, like 
```yaml
name: custom model inference
description: custom model inference

inputs:
  - { name: flist, type: String }
  - { name: respath, type: String }
  - { name: model, type: String }

outputs:
  - { name: output_dir }

implementation:
  container:
    image: xxxx/${model}:latest
    command:
      - bash
      - -ec
      - |
        flist=$0
        respath=$1
        output_dir=$2
        
        mkdir -p ${output_dir}
        cd /root
        python inference.py $flist $model
        cp result.json ${respath}
        cp result.json ${output_dir}/result.json

      - { inputValue: flist }
      - { inputValue: respath }
      - { outputPath: output_dir }
```
But when I passed argument 'model' to this component, it failed to parsed it in image name.

The error message are:
`This step is in Pending state with this message: InvalidImageName: Failed to apply default image tag "xxxx/${model}:latest": couldn't parse image reference "xxxx/${model}:latest": invalid reference format`
I would appreciate it if someone could help me in this issue, thanks
