### ISSUE TITLE
Migrate postsubmit tests to GH Actions

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10747]
## Description

As part of the [main tracker issue](https://github.com/kubeflow/pipelines/issues/10744), we need to migrate [postsubmit tests](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml) to GH Actions.

### Acceptance Criteria
* Need to be able to run locally (preferrable using KinD)
* Need to implement artifact generation ([workflow example](https://github.com/kubeflow/pipelines/blob/master/.github/workflows/backend.yml#L76), and [script example](https://github.com/kubeflow/pipelines/blob/master/scripts/deploy/github/helper-functions.sh#L252)

Impacted by this bug? Give it a 👍.

**Comment by VDliveson** [comment]
@rimolive What is this annotation and how is it referenced here ?
```    
annotations:
      testgrid-dashboards: googleoss-kubeflow-pipelines
      description: Postsubmit integration tests for kubeflow/pipeline.
      testgrid-alert-email: kubeflow-pipelines+test@google.com
      testgrid-num-failures-to-alert: "5"
```
