### ISSUE TITLE
[backend] S3 MissingRegion

### ISSUE THREAD

**Issue by KKHYeon** [kubeflow/pipelines#10846]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
kubeflow on EKS

*  KFP version: 2.2.0

*  KFP SDK version: 2.4.0

### Steps to reproduce
When I run pipeline, the execution is caused error
```
F0523 10:09:45.264234      30 main.go:49] failed to execute component: failed to upload output artifact "x_test_artifact" to remote storage URI "s3://......": uploadFile(): unable to complete copying "/s3/......." to remote storage "load-dataset/x_test_artifact": unable to complete copying: blob (key "load-dataset/x_test_artifact") (code=Unknown): MissingRegion: could not find region configuration
```
This is `kfp-launcher` configmap data
```
  defaultPipelineRoot: s3://bucket_name/v2/artifacts/kubeflow-cr
  providers: |
    s3:
      default:
        endpoint: "s3.ap-northeast-2.amazonaws.com"
        region: "ap-northeast-2"
        disableSSL: false
        credentials:
          fromEnv: true
```

### Expected result
The region must be configured 'ap-northeast-2'

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
