### ISSUE TITLE
[feature] Convert KFP profile controller to a DecoratorController

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/pipelines#10903]
### Feature Area

/area backend 

### What feature would you like to see?

At the moment, the [KFP profile controller](https://github.com/kubeflow/pipelines/blob/3a0566e8dc27d8fbd13174d6a6aed4daddb2405b/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py) is implemented as a metacontroller [CompositeController](https://github.com/kubeflow/pipelines/blob/3a0566e8dc27d8fbd13174d6a6aed4daddb2405b/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml). This allows for the management of child resources based on a parent that is being watched, which is Namespaces for this component.
However, according to the CompositeController [documentation](https://metacontroller.github.io/metacontroller/api/compositecontroller.html#parent-resource), the Metacontroller expects to have full control of the parent resource:

> CompositeController expects to have full control over this resource. That is, you shouldn't define a CompositeController with a parent resource that already has its own controller. See [DecoratorController](https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html) for an API that's better suited for adding behavior to existing resources.

This is obviously not the case here, since the Namespace should be owned by the [Kubeflow profile controller](https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller)

Instead, converting the controller into a [DecoratorController](https://metacontroller.github.io/metacontroller/api/decoratorcontroller.html), which has a slightly different API, would be more appropriate.

Converting the existing CompositeController resource to a DecoratorController would look like this:

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  resources:
  - apiVersion: v1
    resource: namespaces
    labelSelector: # only select namespaces with KFP enabled
      matchLabels:
        pipelines.kubeflow.org/enabled: "true"
  attachments:
  - apiVersion: v1
    resource: secrets
  - apiVersion: v1
    resource: configmaps
  - apiVersion: apps/v1
    resource: deployments
  - apiVersion: v1
    resource: services
  - apiVersion: networking.istio.io/v1alpha3
    resource: destinationrules
  - apiVersion: security.istio.io/v1beta1
    resource: authorizationpolicies
  hooks:
    sync:
      webhook:
        url: http://kubeflow-pipelines-profile-controller/sync
        timeout: 10s
```

The current `sync.py` has to be changed to expect a request body that includes `controller`, `object`, `attachments`, `related`, and `finalizing`, with `object` being the parent Namespace and `attachments` being the attachments we subscribe to in the DecoratorController.

### What is the use case or pain point?

I have not been able to find any writing about the consequences of using a CompositeController for resources that aren't owned by the controller, so we can just say that _unexpected errors can occur_ by using it like we do.

### Is there a workaround currently?

Continue as usual.

---

Love this idea? Give it a 👍.
