### ISSUE TITLE
[sdk] Using kfp v2.0+ not able to add pod labels in kubeflow pipeline workflow

### ISSUE THREAD

**Issue by emilyyujieli** [kubeflow/pipelines#11015]
Hello All,

**Environment**
KFP version: 2.2.0
kubeflow verison: 1.8
KFP SDK version: 2.7.0

**Background**
We are trying to add a pod label to inject istio sidecar in kubeflow pipeline pod then we can use service mesh to do authentication due to project requirement.

**Issue**
If we use kfp v1 and add parameter kubernetes.add_pod_label(task=task,label_key="sidecar.istio.io/inject",label_value="true") in the code, then use KFP SDK v1 to compile the script. label can be injected in related workflow and run successfully.
However if we add the same parameter in kfp v2 script and use kfp SDK v2 to compile, l can see the label in compiled file showed as below
```
platform_spec:
  platforms:
    kubernetes:
      deploymentSpec:
        executors:
          exec-load:
            podMetadata:
              labels:
                sidecar.istio.io/inject: 'true'
```
However when l try to upload the compiled file and execute it via kubeflow pipeline, the label doesn't be injected in related workflow.

**Question**
1.If this parameter kubernetes.add_pod_label still available in KFP v2? 
2.How can l add label in kubeflow pipeline workflow yaml if using kfp v2 since not able to find any information on kubeflow official doucument?

Regards & thanks!

**Comment by daro1337** [comment]
Not sure if this help you but as a workaround you can enforce istio injection  label on `namespace` resource

```
  kind: Namespace
  name: dummy
  metadata:
    labels:
      istio-injection: enabled
```
then every POD in `dummy` namespace will be part of service mesh.

https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

**Comment by emilyyujieli** [comment]
Hi @daro1337,

Thank you for your suggestion, actually the istio-injection label already existed in namespace level. However it seems when we created kubeflow pipeline it not able to inject istio sidecar automatically, that's why we try to add label manually.

Regards & thanks

**Comment by HumairAK** [comment]
/re-open this looks like we're missing the driver side of this functionality

**Comment by mprahl** [comment]
I'd be interested in taking a look!

**Comment by mprahl** [comment]
@emilyyujieli is this still an issue for you? I tried a pipeline with the following YAML snippet:

```yaml
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-get-data:
          podMetadata:
            labels:
              sidecar.istio.io/inject: 'true'
```

The "impl" pods do get the label:

```yaml
    labels:
      pipeline/runid: b6c3c2b6-30aa-4c30-95d5-e71e19e683c3
      pipelines.kubeflow.org/v2_component: "true"
      sidecar.istio.io/inject: "true"  # <--- injected here
      workflows.argoproj.io/completed: "false"
      workflows.argoproj.io/workflow: dsl-input-6lntt
    name: dsl-input-6lntt-system-container-impl-2123244313
```

Where as the "driver" pods do not:

```yaml
    labels:
      pipeline/runid: b6c3c2b6-30aa-4c30-95d5-e71e19e683c3
      pipelines.kubeflow.org/v2_component: "true"
      workflows.argoproj.io/completed: "true"
      workflows.argoproj.io/workflow: dsl-input-6lntt
    name: dsl-input-6lntt-system-container-driver-2247651804
```

Was the expectation that the label be set on all pods and not just the "impl" pods?
