### ISSUE TITLE
Expose Pipelines as CRD and enable to easy migration from Argo workflow

### ISSUE THREAD

**Issue by inc0** [kubeflow/pipelines#1132]
Currently to use pipelines you need to run python SDK, only that generates argo workflow underneath etc. I think this is very limiting because:

1. not everyone uses python
2. requires to learn whole new API and DSL
3. Argo has a lot of examples already, shame that we can't tap to this knowledge source
4. Argo can do much more than just data pipelines, you can learn one syntax and have it used for data, CI, CD etc

I propose creating new CRD that will be effectively Argo workflow with additional options.
For example

```
apiVersion: kubeflow.org
kind: Pipeline
metadata:
  generateName:  mlapp-
  labels:
    workflow: mlapp
spec:
# Add some useful pipeline specific data
  model_name: foobar
  model_version: 1
# This is just argo workflow spec
  entrypoint: mlapp
  templates:
  - name: mlapp
    dag:
      tasks:
      - name: preprocess
        template: preprocess

      - name: model1
        dependencies: [preprocess]
        template: train
        arguments:
          artifacts:
          - name: dataset
            from: "{{tasks.preprocess.outputs.artifacts.dataset}}"

  - name: preprocess
    container:
      image: myimage:latest
      name: preprocess
      command: ["python", "/src/preprocess.py"]
      env:
        - name: SOMEENV
          value: foobar
    outputs:
     artifacts:
     - name: dataset
       path: /data

  - name: train
    inputs:
      artifacts:
      - name: dataset
        path: /data
    outputs:
     artifacts:
     - name: model
       path: /output
    container:
      image: myimage:latest
      name: trainer
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
      command: ["python", "/src/train.py"]
```

This would make transition to pipelines much easier as Operators are already well known pattern and it handles *a lot* of things for us, including RBAC multitenancy, API auth etc.
