### ISSUE TITLE
[frontend] optional pipeline parameters

### ISSUE THREAD

**Issue by asaff1** [kubeflow/pipelines#11331]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Standalone

*  KFP version: 
2.1.0

### Steps to reproduce
Create a pipeline component with `Optional[int]` parameter. The UI will still require it, even though in the component yaml it is marked as optional. See:
![image](https://github.com/user-attachments/assets/8a86b22a-555b-4c33-bbc7-8a5a2fce3f71)

But UI shows:
![image](https://github.com/user-attachments/assets/75ad93f5-1897-4d5b-8ab4-ac64bcc23af4)

Also probably related, when setting default value for integer type to 0, it shows blank. (so 0 for integer is considered as no default value).

### Expected result
UI pipeline form should respect optional parameter

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by tumido** [comment]
+1, we're also impacted by this. 

Simple reproducer here:

```py
from typing import Optional
from kfp import compiler, dsl


@dsl.component()
def print_param_op(int_param: Optional[int] = None):
    print(int_param)

@dsl.pipeline()
def pipeline(int_param: Optional[int] = None):
    print_param_task = print_param_op(int_param=int_param)

if __name__ == "__main__":
    compiler.Compiler().compile(pipeline, "pipeline.yaml")
```

KFP DSL properly translates this to:

```yaml
...
root:
  dag:
    tasks:
      print-param-op:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-print-param-op
        inputs:
          parameters:
            int_param:
              componentInputParameter: int_param
        taskInfo:
          name: print-param-op
  inputDefinitions:
    parameters:
      int_param:
        isOptional: true
        parameterType: NUMBER_INTEGER
schemaVersion: 2.1.0
sdkVersion: kfp-2.10.1
```

However I'm unable to run the pipeline unless the param value is set.
