### ISSUE TITLE
[backend] Components with optional artifacts not caching after migrating to kfp>2.0

### ISSUE THREAD

**Issue by jortizta** [kubeflow/pipelines#11410]
After migrating a collection of custom components and pipelines running in Vertex AI from KFP 1.8 to KFP 2.3 and 2.8, the components which have optional artifacts are no longer cached.

### Environment

* KFP version: 2.3, 2.8
* KFP SDK version: 2.3, 2.8
* Platform: Vertex AI

### Steps to reproduce

Compile, and run a custom component with an optional artifact, for example:

```
name: Train XGBoost
description: Train an XGBoost
inputs:
  - {name: data_artifact, type: Dataset, optional: True, description: 'Dataset used for training'}
  - {name: data_path, type: String, description: 'Path to parquet file used for training'}
  - {name: target_variable, type: String, description: ''}
  
outputs:
  - {name: model_prod_artifact, type: Model}
  
implementation:
  container:
    image: gcr.io/PROJECT_ID/component_default@DIGEST
    args:
    - --executor_input
    - executorInput: null
    - --function_to_execute
    - train_xgb
    command: 
    - python3
    - -m 
    - kfp.dsl.executor_main
    - --component_module_path
    - ./train_xgb.py
```

### Expected result

Having optional artifacts in the component definition should not prevent component caching from working. That was the behavior in KFP 1.8

---

Impacted by this bug? Give it a 👍.
