### ISSUE TITLE
The volumes PVC name is unreasonable after mount a pvc for pipeline

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/pipelines#1303]
Here have a pipeline definition file, part of the file is as following:

Define the `pvc_name` and mount the pvc by using `onprem.mount_pvc`.

```
def my_pipeline(
....
    pvc_name='pipeline-pvc',
    pvc_mount_path='/mnt',
....
):

    my_pipeline = my_pipeline_op(
...
    ).apply(onprem.mount_pvc(pvc_name, 'local-storage', pvc_mount_path))
```

After compire using `dsl-compile`. The workflow yaml file is as following:

```
  volumes:
  - name: local-storage
    persistentVolumeClaim:
      claimName: '{{input.parameters.pvc-name}}'
```

The clainName value should be `workflow.parameters.pvc-name`, instead of `input.parameters.pvc-name` since the volumes is out of templates/container, no inputs parameters, should be workflow parameters.
