### ISSUE TITLE
Doesn't remove old containers (> maxHistory)

### ISSUE THREAD

**Issue by DmitryBe** [kubeflow/pipelines#15]
does the parameter `maxHistory` assumes removing old argo workflows, or it's just defines number of records in `workflowHistory`?

i have following configuration (keep it short for simplicity):
```
apiVersion: kubeflow.org/v1alpha1
kind: ScheduledWorkflow
metadata:
  name: iris-trainer
  namespace: playground
spec:
  enabled: true
  maxHistory: 5
  trigger:
    cronSchedule:
      cron: "@hourly"
  workflow:
    spec:
    
      # argo workflow declaration    
      entrypoint: iris-train
      onExit: exit-handler

      arguments:
        parameters:
        - name: learning-rate
          value: "0.01"
        - name: num-boost-round
          value: "100"

      templates:

      - name: iris-train
```

In a `workfloHistory` is see 5 last records:
```
 trigger:
    LastIndex: 47
    LastTriggeredTime: 2018-09-03T03:00:00Z
    NextTriggeredTime: 2018-09-03T04:00:00Z
  workflowHistory:
    completed:
    - Phase: Succeeded
      createdAt: 2018-09-03T03:00:08Z
      finishedAt: 2018-09-03T03:00:28Z
      index: 47
      name: iris-trainer-47-991149392
      namespace: playground
      scheduledAt: 2018-09-03T03:00:00Z
      selfLink: /apis/argoproj.io/v1alpha1/namespaces/playground/workflows/iris-trainer-47-991149392
      startedAt: 2018-09-03T03:00:08Z
      uid: 7702b405-af25-11e8-a9d4-06bcfad5caf4
    - Phase: Succeeded
      createdAt: 2018-09-03T02:00:07Z
      finishedAt: 2018-09-03T02:00:27Z
      index: 46
      name: iris-trainer-46-1007927011
      namespace: playground
      scheduledAt: 2018-09-03T02:00:00Z
      selfLink: /apis/argoproj.io/v1alpha1/namespaces/playground/workflows/iris-trainer-46-1007927011
      startedAt: 2018-09-03T02:00:07Z
      uid: 1516d4a3-af1d-11e8-a9d4-06bcfad5caf4
    - Phase: Succeeded
      createdAt: 2018-09-03T01:00:07Z
      finishedAt: 2018-09-03T01:00:27Z
      index: 45
      name: iris-trainer-45-1024704630
      namespace: playground
      scheduledAt: 2018-09-03T01:00:00Z
      selfLink: /apis/argoproj.io/v1alpha1/namespaces/playground/workflows/iris-trainer-45-1024704630
      startedAt: 2018-09-03T01:00:07Z
      uid: b35d925e-af14-11e8-a9d4-06bcfad5caf4
    - Phase: Succeeded
      createdAt: 2018-09-03T00:00:08Z
      finishedAt: 2018-09-03T00:00:26Z
      index: 44
      name: iris-trainer-44-1041482249
      namespace: playground
      scheduledAt: 2018-09-03T00:00:00Z
      selfLink: /apis/argoproj.io/v1alpha1/namespaces/playground/workflows/iris-trainer-44-1041482249
      startedAt: 2018-09-03T00:00:08Z
      uid: 51fcd7bb-af0c-11e8-a9d4-06bcfad5caf4
    - Phase: Succeeded
      createdAt: 2018-09-02T23:00:08Z
      finishedAt: 2018-09-02T23:00:28Z
      index: 43
      name: iris-trainer-43-1058259868
      namespace: playground
      scheduledAt: 2018-09-02T23:00:00Z
      selfLink: /apis/argoproj.io/v1alpha1/namespaces/playground/workflows/iris-trainer-43-1058259868
      startedAt: 2018-09-02T23:00:08Z
      uid: f01968c7-af03-11e8-a9d4-06bcfad5caf4
```

Unfortunately, old containers wasn't removed:
```
argo -n playground list
NAME                         STATUS      AGE    DURATION
iris-trainer-47-991149392    Succeeded   33m    20s
iris-trainer-46-1007927011   Succeeded   1h     20s
iris-trainer-45-1024704630   Succeeded   2h     20s
iris-trainer-44-1041482249   Succeeded   3h     18s
iris-trainer-43-1058259868   Succeeded   4h     20s
iris-trainer-42-1075037487   Succeeded   5h     18s
iris-trainer-41-1091815106   Succeeded   6h     19s
iris-trainer-40-1108592725   Succeeded   7h     19s
iris-trainer-39-3373026837   Succeeded   8h     19s
iris-trainer-38-3356249218   Succeeded   9h     19s
iris-trainer-37-3406582075   Succeeded   10h    20s
iris-trainer-36-3389804456   Succeeded   11h    20s
iris-trainer-35-3440137313   Succeeded   12h    21s
iris-trainer-34-3423359694   Succeeded   13h    18s
iris-trainer-33-3473692551   Succeeded   14h    18s
iris-trainer-32-3456914932   Succeeded   15h    19s
iris-trainer-31-3507247789   Succeeded   16h    19s
iris-trainer-30-3490470170   Succeeded   17h    19s
iris-trainer-29-3171842504   Succeeded   18h    18s
iris-trainer-28-3188620123   Succeeded   19h    18s
iris-trainer-27-3138287266   Succeeded   20h    18s
iris-trainer-26-3155064885   Succeeded   21h    18s
iris-trainer-25-3104732028   Succeeded   22h    19s
iris-trainer-24-3121509647   Succeeded   23h    18s
iris-trainer-23-3071176790   Succeeded   1d     19s
iris-trainer-22-3087954409   Succeeded   1d     18s
iris-trainer-21-3037621552   Succeeded   1d     19s
iris-trainer-20-3054399171   Succeeded   1d     20s
iris-trainer-19-1023865987   Succeeded   1d     18s
iris-trainer-18-1007088368   Succeeded   1d     20s
iris-trainer-17-1258752653   Succeeded   1d     19s
iris-trainer-16-1241975034   Succeeded   1d     18s
iris-trainer-15-1225197415   Succeeded   1d     21s
iris-trainer-14-1208419796   Succeeded   1d     18s
iris-trainer-13-1191642177   Succeeded   1d     20s
iris-trainer-12-1174864558   Succeeded   1d     19s
iris-trainer-11-1158086939   Succeeded   1d     20s
iris-trainer-10-1141309320   Succeeded   1d     19s
iris-trainer-9-3808217808    Succeeded   1d     20s
iris-trainer-8-3824995427    Succeeded   1d     19s
iris-trainer-7-4043104474    Succeeded   1d     18s
iris-trainer-6-4059882093    Succeeded   1d     20s
iris-trainer-5-4009549236    Succeeded   1d     18s
iris-trainer-4-4026326855    Succeeded   1d     19s
iris-trainer-3-3975993998    Succeeded   1d     25s
iris-trainer-2-3992771617    Succeeded   1d     20s
iris-trainer-1-3942438760    Succeeded   1d     21s
```
