### ISSUE TITLE
[Questions] Adding environment variables and specifying component replica count

### ISSUE THREAD

**Issue by pjo256** [kubeflow/pipelines#1504]
Hey! I'm looking into using kubeflow pipelines to manage ML workflows. Not sure if this is the right place to ask, but couldn't find clarity in previous issues or on the doc site.

I'd like to specify environment variables for components in a pipeline using k8s config maps and secrets. I see examples using `use_gcp_secret`, however this is only intended to expose 
 GCP credentials as environment variables. My current approach is to compile the pipeline (`pipeline.yml`), and supply the output and a `patch.yml` to `kustomize`. 

`patch.yml`
```
- op: add
  path: /spec/templates/1/container/env
  value:
      - name: SECRET_A
        valueFrom:
            secretKeyRef:
                name: secret-a
                key: the-secret

- op: add
  path: /spec/templates/1/container/envFrom
  value:
        configMapRef:
          name: the-configmap
```

`kustomization.yml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pipeline.yml
patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Workflow
    name: wat
  path: patch.yml
```

This approach poses a few problems, `kustomize` can [only patch custom resources using a JSON patch strategy](https://github.com/kubernetes-sigs/kustomize/issues/742), which requires a `metadata.name` field to be defined (currently, only `metadata.generateName` is set). Does the pipeline API/SDK provide a better way of doing this?

Lastly, I'd like to distribute tasks among several container instances of a component in my workflow. Is it possible to specify a replica count for a component container?

Thanks for taking a look!
