### ISSUE TITLE
Assign a different namespace to ResouceOp than the pipeline

### ISSUE THREAD

**Issue by PrathamSolanki** [kubeflow/pipelines#2024]
Hi,

I have a Kubeflow GKE deployment in the namespace `kubeflow`, however seldon-core is present in namespace `seldon-core`.

I have a pipeline where the last step is a ResourceOp that creates a SeldonDeployment. Thing is it has to use the seldon-core services in the `seldon-core` namespace and must create deployment there. But the namespace specified in my script that creates the pipeline is `kubeflow`.

So when I run the pipeline, the pod responsible for ResourceOp gives me the error while it tries to run `kubectl get seldondeployment.machinelearning.seldon.io/seldon-deployment-demo -o jsonpath='{}'` as it is not applying the correct namespace.

Is there any way I can force the ResourceOp to use a different namespace?

**Comment by elikatsis** [comment]
Hi @PrathamSolanki,

Could you provide the parts of your pipeline regarding this issue? I.e. definition of the deployment and the ResourceOp creating it.

**Comment by PrathamSolanki** [comment]
Hi @elikatsis,

This is my pipeline definition:

```
@dsl.pipeline(
	name='demo',
	description='pipeline for mercari demo')

def demo_pipeline():
	getdata_step = dsl.ContainerOp(
		name='get_data',
		image='registry/get_data',
		command="python",
		arguments=[
			"/microservice/get_data.py"
		]
	)

	preprocess_step=dsl.ContainerOp(
		name='preprocess',
		image='registry/preprocess',
		command="python",
		arguments=[
			"/microservice/preprocess.py"
		]
	)

	preprocess_step.after(getdata_step)

	train_step=dsl.ContainerOp(
		name='train',
		image='registry/train',
		command="python",
		arguments=[
			"/microservice/model.py"
		]
	)

	train_step.after(preprocess_step)

	steps=[getdata_step,preprocess_step,train_step]

	for step in steps:
		step.apply(gcp.use_gcp_secret(secret)) 
		
	try:
		seldon_config = yaml.load(open("../deploy_pipeline/seldon_production_pipeline.yaml"))
	except:
        # If this file is run from the project core directory
		seldon_config = yaml.load(open("deploy_pipeline/seldon_production_pipeline.yaml"))
		
	deploy_step = dsl.ResourceOp(
        name="seldondeploy",
        k8s_resource=seldon_config,
        attribute_outputs={"name": "{.metadata.name}"})
		
	deploy_step.after(train_step)
```

I want my ResourceOp to use the namespace `seldon-core`.

**Comment by elikatsis** [comment]
The definition of the deployment is crucial and it would help me better understand the problem.

You generally need to have permissions to deploy resources to other namespaces. In this case, I believe you do, because `pipeline-runner` is a `ServiceAccount` connected to `ClusterRole` with a `ClusterRoleBinding`.

I think all you need to do is specify the `namespace` of the kubernetes resource you create, but I can't be sure without knowing what's inside `seldon_production_pipeline.yaml`.

If that is the case, it can be solved by doing one of the following:
* Change `seldon_production_pipeline.yaml`, setting the `namespace` field to `seldon-core`
* If you don't want to change `seldon_production_pipeline.yaml` configuration: `seldon_config` is a dictionary. You will have to set
```python
seldon_config["metadata"]["namespace"] = "seldon-core"
```
once `yaml.load()` has succeeded.

**Comment by PrathamSolanki** [comment]
Hi @elikatsis,

Yes indeed, in the `seldon_production_pipeline.yaml` the namespace is set to `seldon-core`:

```
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "seldon-deployment-{{workflow.name}}"
  namespace: seldon-core
spec:
  annotations:
    project_name: Pipeline
    deployment_version: v1
  name: "seldon-deployment-{{workflow.name}}"
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: registry/preprocess
          imagePullPolicy: IfNotPresent
          name: preprocess
          resources:
            requests:
              memory: 1Mi
        - image: registry/train
          imagePullPolicy: IfNotPresent
          name: train
        imagePullSecrets:
        - name: gitlab-auth
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: train
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: preprocess
      endpoint:
        type: REST
      type: MODEL
    name: single-model
    replicas: 1
    annotations:
      predictor_version: v1
```

But still I get the error as described in the issue. However, my pod does put a deployment in the `seldon-core` namespace but when I describe it the status is shown false:

```
Status:
  Description:  Failed to create deployment seldon-deployment-demo-m7zkc-single-model-2123895
  State:        Failed
Events:         <none> 
```
