### ISSUE TITLE
Workflow yaml generated by the SDK has the "volumes" field located incorrectly, causing the pipeline run to crash.

### ISSUE THREAD

**Issue by sahilmalav** [kubeflow/pipelines#2539]
Given below is my python code. 

```
import yaml
import kfp
from kfp import components
from kfp import dsl
from kubernetes import client as k8s_client

with open('benchmark_pipeline_testing--pipeline_components_file_0.yaml', 'r') as f:
    component_info = yaml.safe_load(f.read())['components']

data_fetch_ = components.load_component_from_text(str(component_info[0]))
prepare_data_ = components.load_component_from_text(str(component_info[1]))
train_ = components.load_component_from_text(str(component_info[2]))
codify_ = components.load_component_from_text(str(component_info[3]))

@dsl.pipeline(
    name='benchmark_pipeline_testing',
    description='A pipeline for training project'
)
def main_function(repo_name="", branch_name="", commit="", output_path="", input_path=""):

	data_fetch = data_fetch_(repo_name=repo_name, branch_name=branch_name, commit=commit, output_path=output_path, input_path=input_path).add_volume(k8s_client.V1Volume(name='benchmark-project-prod--pipeline-pv', persistent_volume_claim=k8s_client.V1PersistentVolumeClaimVolumeSource(claim_name='benchmark-project-prod--pipeline-pvc'))).add_volume_mount(k8s_client.V1VolumeMount(mount_path='/data', name='benchmark-project-prod--pipeline-pv'))

	prepare_data = prepare_data_(repo_name=repo_name, branch_name=branch_name, commit=commit, output_path=output_path, input_path=input_path).add_volume_mount(k8s_client.V1VolumeMount(mount_path='/data', name='benchmark-project-prod--pipeline-pv'))

	prepare_data.after(data_fetch)

	train = train_().add_volume_mount(k8s_client.V1VolumeMount(mount_path='/data', name='benchmark-project-prod--pipeline-pv'))

	train.after(prepare_data)

	codify = codify_().add_volume_mount(k8s_client.V1VolumeMount(mount_path='/data', name='benchmark-project-prod--pipeline-pv'))

	codify.after(train)

	dsl.get_pipeline_conf().set_image_pull_secrets([k8s_client.V1ObjectReference(name="dockerkey")])

kfp.compiler.Compiler().compile(main_function, __file__ + '.zip')
```

Upon compiling this, I got the following workflow yaml : 

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline for training
      irrs", "inputs": [{"default": "", "name": "repo_name"}, {"default": "", "name":
      "branch_name"}, {"default": "", "name": "commit"}, {"default": "", "name": "output_path"},
      {"default": "", "name": "input_path"}], "name": "benchmark_pipeline_testing"}'
  generateName: benchmark-pipeline-testing-
spec:
  arguments:
    parameters:
    - name: repo-name
      value: ''
    - name: branch-name
      value: ''
    - name: commit
      value: ''
    - name: output-path
      value: ''
    - name: input-path
      value: ''
  entrypoint: benchmark-pipeline-testing
  imagePullSecrets:
  - name: dockerkey
  serviceAccountName: pipeline-runner
  templates:
  - dag:
      tasks:
      - dependencies:
        - train
        name: codify
        template: codify
      - arguments:
          parameters:
          - name: branch-name
            value: '{{inputs.parameters.branch-name}}'
          - name: commit
            value: '{{inputs.parameters.commit}}'
          - name: input-path
            value: '{{inputs.parameters.input-path}}'
          - name: output-path
            value: '{{inputs.parameters.output-path}}'
          - name: repo-name
            value: '{{inputs.parameters.repo-name}}'
        name: data-fetch
        template: data-fetch
      - dependencies:
        - data-fetch
        name: prepare-data
        template: prepare-data
      - dependencies:
        - prepare-data
        name: train
        template: train
    inputs:
      parameters:
      - name: branch-name
      - name: commit
      - name: input-path
      - name: output-path
      - name: repo-name
    name: benchmark-pipeline-testing
  - container:
      args: []
      command: []
      image: temp_image
      volumeMounts:
      - mountPath: /data
        name: benchmark-project-prod--pipeline-pv
    metadata:
      annotations:
        pipelines.kubeflow.org/component_spec: '{"description": "Generate embedding
          for trained data", "inputs": [], "name": "codify"}'
    name: codify
  - container:
      args:
      - data_pull
      - -r
      - '{{inputs.parameters.repo-name}}'
      - -b
      - '{{inputs.parameters.branch-name}}'
      - -c
      - '{{inputs.parameters.commit}}'
      - -in
      - '{{inputs.parameters.input-path}}'
      - -out
      - '{{inputs.parameters.output-path}}'
      command: []
      image: temp_image
      volumeMounts:
      - mountPath: /data
        name: benchmark-project-prod--pipeline-pv
    inputs:
      parameters:
      - name: branch-name
      - name: commit
      - name: input-path
      - name: output-path
      - name: repo-name
    metadata:
      annotations:
        pipelines.kubeflow.org/component_spec: '{"description": "fetches data from
          source", "inputs": [{"description": "repo name", "name": "repo_name", "type":
          "String"}, {"description": "branch name", "name": "branch_name", "type":
          "String"}, {"description": "commit", "name": "commit", "type": "String"},
          {"description": "output path", "name": "output_path", "type": "String"},
          {"description": "input path", "name": "input_path", "type": "String"}],
          "name": "data_fetch"}'
    name: data-fetch
    volumes:
    - name: benchmark-project-prod--pipeline-pv
      persistentVolumeClaim:
        claimName: benchmark-project-prod--pipeline-pvc
  - container:
      args: []
      command: []
      image: temp_image
      volumeMounts:
      - mountPath: /data
        name: benchmark-project-prod--pipeline-pv
    metadata:
      annotations:
        pipelines.kubeflow.org/component_spec: '{"description": "reads input data
          from filesystem", "inputs": [{"description": "repo name", "name": "repo_name",
          "type": "String"}, {"description": "branch name", "name": "branch_name",
          "type": "String"}, {"description": "commit", "name": "commit", "type": "String"},
          {"description": "output path", "name": "output_path", "type": "String"},
          {"description": "input path", "name": "input_path", "type": "String"}],
          "name": "prepare_data"}'
    name: prepare-data
  - container:
      args: []
      command: []
      image: temp_image
      volumeMounts:
      - mountPath: /data
        name: benchmark-project-prod--pipeline-pv
    metadata:
      annotations:
        pipelines.kubeflow.org/component_spec: '{"description": "Training of actual
          data", "inputs": [], "name": "train"}'
    name: train
```

I uploaded this to Kubeflow dashboard, and while running, got the following error : 
"**This step is in Error state with this message: volume 'benchmark-project-prod--pipeline-pv' not found in workflow spec**"

As you can see in the workflow yaml, the "volumes" field is inside "container" array, and not inside "spec". I had to manually move it to "spec" to get it to work. 
Any idea why this is happening? I haven't faced this issue before. 

Versions:
kfp-server-api 0.1.18.3
kfp 0.1.32.2 
Kubeflow v0.6.1

**Comment by sahilmalav** [comment]
UPDATE: Problem seems to be with the kfp version. Versions 0.1.31.2 and 0.1.32.2 have the same problem. Upon downgrading to 0.1.30, it's working fine. Please look into it.

**Comment by Ark-kun** [comment]
I'm pretty sure this issue was introduced in this PR: https://github.com/kubeflow/pipelines/pull/2229
I'll take a look and create a fix.

**Comment by Ark-kun** [comment]
>As you can see in the workflow yaml, the "volumes" field is inside "container" array

Are you sure the `volumes` entry is in the `template.container`? It seems to be in the `template`, which is the correct place for volumes in Argo 2.3.0+.

Can you please upgrade your backend KFP installation (or just upgrade Argo to 2.3.0)

**Comment by Ark-kun** [comment]
As a side note: I'd also like to learn more about your use case and how you use Pipelines.

> with open('benchmark_pipeline_testing--pipeline_components_file_0.yaml', 'r') as f:
>     component_info = yaml.safe_load(f.read())['components']

Can you explain the decision to keep all components in the same file as opposed to per-component [versioned] files?



> codify_().add_volume_mount(

Every `add_volume_mount` should be accompanied with `add_volume`.

>data_fetch = data_fetch_(repo_name=repo_name, branch_name=branch_name, commit=commit, output_path=output_path, input_path=input_path).add_volume(k8s_client.V1Volume(name='benchmark-project-prod--pipeline-pv', persistent_volume_claim=k8s_client.V1PersistentVolumeClaimVolumeSource(claim_name='benchmark-project-prod--pipeline-pvc'))).add_volume_mount(k8s_client.V1VolumeMount(mount_path='/data', name='benchmark-project-prod--pipeline-pv'))

This can be greatly simplified by using

```python
from kfp.onprem import mount_pvc

data_fetch_(...).apply(mount_pvc(pvc_name='benchmark-project-prod--pipeline-pvc', volume_mount_path='/data'))
```

Which can be further simplified by using `PipelineConf.add_op_transformer` which applies a modification to all tasks in a pipeline. See https://github.com/kubeflow/pipelines/blob/2fbbf1939974111698547ad519bf403afa4c736f/samples/core/pipeline_transformers/pipeline_transformers.py#L39


>.after

Usage of `.after` is usually a symptom of less than perfect component design. Ideally the pipeline should be setting dependencies by passing data between components.

**Comment by sahilmalav** [comment]
@Ark-kun I'm working on a project that required automated pipeline creation. So the python code that you saw is auto-generated based on some user inputs. 
I'm using ".after" since it's very generic. In a pipeline, the next component might not always use the data from the previous components. 
The decision to keep all the components in one file also arises from the fact the component file is auto-generated. So it's easy to read for the program, instead of going to different files.

**Comment by sahilmalav** [comment]
> > As you can see in the workflow yaml, the "volumes" field is inside "container" array
> 
> Are you sure the `volumes` entry is in the `template.container`? It seems to be in the `template`, which is the correct place for volumes in Argo 2.3.0+.
> 
> Can you please upgrade your backend KFP installation (or just upgrade Argo to 2.3.0)

@Ark-kun Yes, pretty sure it's inside 'container' and not 'template'. You can see that it's at the same level as "args", "inputs", "metadata" and "name".

**Comment by Ark-kun** [comment]
> @Ark-kun Yes, pretty sure it's inside 'container' and not 'template'. You can see that it's at the same level as "args", "inputs", "metadata" and "name".

I'm not sure this is the case:

```yaml
  - container:
        args:
        command: []
        image: temp_image
        volumeMounts:
    inputs:
        parameters:
    metadata:
        annotations:
    name: data-fetch
    volumes:
    - name: benchmark-project-prod--pipeline-pv
      persistentVolumeClaim:
          claimName: benchmark-project-prod--pipeline-pvc
```
