### ISSUE TITLE
Katib component not completing correctly

### ISSUE THREAD

**Issue by karlschriek** [kubeflow/pipelines#2837]
**What happened:**
When running a Katib component as the first step in a Pipeline, the component never reaches a "complete" stage. Both in the Pipelines dashboard and in the Katib dashboard the component is shown as still in progress.

I am running three parallel trials. The relevant pods have the following status:
```
hyperparam-test-0addb24d-8077-4d9c-8b7a-978cc99b3ff2-randovnqnv          1/1       Running     0          7m30s
hyperparam-test-0addb24d-8077-4d9c-8b7a-978cc99b3ff2-6grz2fdz-worker-0   0/2       Completed   0          4m8s
hyperparam-test-0addb24d-8077-4d9c-8b7a-978cc99b3ff2-cfk6qcc6-worker-0   0/2       Completed   0          4m8s
hyperparam-test-0addb24d-8077-4d9c-8b7a-978cc99b3ff2-dqnl9nv2-worker-0   0/2       Completed   0          4m7s
```

I'm using the `File` metrics collector (although the exact same problem applies to the `StdOut` collector). Scrutinising the logs of a `metrics-logger-and-collector` container within one of the worker pods reveals that all the metrics are initially picked up by the collector. I.e. as the model trains, the metrics are contiually showing up in the logs of the  `metrics-logger-and-collector` container.
```

I0114 14:04:53.314037      22 main.go:77] 2020-01-14T14:04:53.313908Z acc=0.49391305446624756
I0114 14:04:53.318359      22 main.go:77] 2020-01-14T14:04:53.318151Z loss=0.23501461744308472
I0114 14:04:53.318396      22 main.go:77] 2020-01-14T14:04:53.318252Z acc=0.4943527281284332
I0114 14:04:53.323229      22 main.go:77] 2020-01-14T14:04:53.323038Z loss=0.04049709439277649
I0114 14:04:53.323350      22 main.go:77] 2020-01-14T14:04:53.323178Z acc=0.4947916567325592
I0114 14:04:53.328207      22 main.go:77] 2020-01-14T14:04:53.327986Z loss=1.456436276435852
I0114 14:04:53.328319      22 main.go:77] 2020-01-14T14:04:53.328122Z acc=0.49479618668556213
I0114 14:04:53.335419      22 main.go:77] 2020-01-14T14:04:53.335210Z loss=0.08680590242147446
...
```
It then stops. The `tensorflow` container terminates, having finished its task and the pod reached "Completed" state. The final dump to the logs of the `metrics-logger-and-collector` container look like this:

```
0114 14:06:07.661148      23 main.go:118] Metrics reported. :
metric_logs:<time_stamp:"0001-01-01T00:00:00Z" metric: metric_logs: > metric_logs: > metric_logs: 
> metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > 
metric_logs: > metric_logs: > metric_logs: > metric_logs: > metric_logs: > ....
```

So it would seem that the metrics are not exporting correctly, therefore the Katib component does not complete.

Note that if I run the exact same Katib job directly from a YAML file instead of via Pipelines it works without any prolems. Below I include the YAML file and the code used to run it.

YAML file:
```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  name: tfjob-example-file
spec:
  parallelTrialCount: 3
  maxTrialCount: 6
  maxFailedTrialCount: 3
  objective:
    type: minimize
    goal: 0.1
    objectiveMetricName: loss
    additionalMetricNames:
      - acc
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/logs/metrics.log"
        kind: File
    collector:
      kind: File
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: --dropout_rate
      parameterType: double
      feasibleSpace:
        min: "0.3"
        max: "0.7"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1
              restartPolicy: OnFailure
              template:
                spec:
                  containers:
                    - name: tensorflow
                      image: /path/to/my/repo/tf_job:latest
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "model.py"
                        - "--input_size_x=10"
                        - "--input_size_y=10"
                        - "--tensorboard_log_dir=/tensorboard"
                        - "--number_of_workers=1"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}

```

Pipeline code:

```
import kfp
import json
import yaml

katib_config_path="./config/katib_file.yaml"
with open(katib_config_path, "rb") as f:
    katib_config = yaml.load(f)

@kfp.dsl.pipeline(name="hyperparam", description="test hyperparam pipeline")
def dev_hyperparam_pipeline(
        name="hyperparam-test-{{workflow.uid}}",
        namespace="kubeflow",
        step="2000"):

    # fetch katib experiment launcher
    katib_experiment_launcher_op = kfp.components.load_component_from_url(
        'https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml')

    # tune hyperparamters and get results.
    katib_experiment_task = katib_experiment_launcher_op(
        experiment_name=name,
        experiment_namespace=namespace,
        parallel_trial_count=katib_config["spec"]["parallelTrialCount"],
        max_trial_count=katib_config["spec"]["maxTrialCount"],
        #max_failed_trial_count=katib_config["spec"]["maxFailedTrialCount"],
        objective=json.dumps(katib_config["spec"]["objective"]),
        algorithm=json.dumps(katib_config["spec"]["algorithm"]),
        trial_template=json.dumps(katib_config["spec"]["trialTemplate"]),
        parameters=json.dumps(katib_config["spec"]["parameters"]),
        metrics_collector=json.dumps(katib_config["spec"]["metricsCollectorSpec"]),
        #experiment_timeout_minutes=experimentTimeoutMinutes,
        delete_finished_experiment="False"
    )
```

Setup:
Kubeflow 0.7.1
Kubernetes 1.12 (EKS)
