### ISSUE TITLE
[Bug] Deploying 'metadata' from KFP manifests breaks KF Metadata

### ISSUE THREAD

**Issue by elikatsis** [kubeflow/pipelines#2889]
I'm testing the `metadata-writer` component locally, on an existing KF v0.7 (MiniKF on GCP).
First of all, it is a great service and looks pretty useful.

So, I deployed it using the manifests in this repo ([manifests/kustomize](https://github.com/kubeflow/pipelines/tree/0.1.40/manifests/kustomize)).

I found out that this installation _breaks_ the global `metadata` component.
The manifests modify metadata as follows:
* `metadata-deployment`: Instead of deploying a container similar to the existing one, that is an HTTP server, a gRPC server gets deployed there.
  Before:
  ```yaml
      containers:
      - command:
        - ./server/server
        - --http_port=8080
        - --mysql_service_host=metadata-db.kubeflow
        - --mysql_service_port=3306
        - --mysql_service_user=root
        - --mysql_service_password=$(MYSQL_ROOT_PASSWORD)
        - --mlmd_db_name=metadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: metadata-db-secrets
        image: gcr.io/kubeflow-images-public/metadata:v0.1.10
        name: container
        ports:
        - containerPort: 8080
          name: backendapi
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: ContentType
              value: application/json
            path: /api/v1alpha1/artifact_types
            port: backendapi
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
  ```
  After:
  ```yaml
      containers:
      - args:
        - --grpc_port=8080
        - --mysql_config_database=$(MYSQL_DATABASE)
        - --mysql_config_host=$(MYSQL_HOST)
        - --mysql_config_port=$(MYSQL_PORT)
        - --mysql_config_user=$(DBCONFIG_USER)
        - --mysql_config_password=$(DBCONFIG_PASSWORD)
        command:
        - /bin/metadata_store_server
        env:
        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-credential
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-credential
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: metadata-mysql-configmap
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: metadata-mysql-configmap
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PORT
              name: metadata-mysql-configmap
        image: gcr.io/tfx-oss-public/ml_metadata_store_server:0.14.0
        name: container
        ports:
        - containerPort: 8080
          name: md-backendapi
  ```
  * `metadata-service`: Port name changes, but I guess that's minor.
  * `metadata-envoy`: Different image tag, KF deploys `gcr.io/ml-pipeline/envoy:metadata-grpc` while these manifests use `gcr.io/ml-pipeline/envoy:initial`
  * Different host & credentials for mysql

The most important change that breaks Metadata is changing the backend server. Artifact Store expects an HTTP server, while Metadata Writer expects a gRPC server, under the same service (`metadata-service.kubeflow`).
https://github.com/kubeflow/pipelines/blob/0577fe10fdc3c57cd56ca3b65198c03636ae4520/backend/metadata_writer/src/metadata_helpers.py#L23-L30

---

So, I've got some questions, trying to find out what's the rationale behind this.

1. Why modify the `metadata-deployment` to be a gRPC server (or create is as a gRPC server), since `metadata-grpc-deployment` exists (or can be created instead) and `metadata-ui` (when that exists) speaks HTTP through `metadata-service`?
   `metadata-grpc-deployment` **is**, actually, almost the same deployment (there are some minor differences in its arguments but it feels like it's just naming stuff).

2. Why change the name of `metadata-service` port to `md-backendapi`? I think it would be best practice to either change `kubeflow/manifests`, or in this repo. But we shouldn't have them differ.

3. Why use directly the `ml_metadata` package, instead of `kubeflow.metadata`? After some [pretty shallow] checking, it seems like we could use the `kubeflow/metadata` SDK which also permits accessing `ml_metadata` objects and their methods.

4. Why use different credentials for the database?

---

Actually, I tried deploying just the `metadata-writer` component (`Deployment`, `Role`, `RoleBinding` and `ServiceAccount`) but I changed the aforementioned lines as follows, to use the gRPC service, and it works just great:
```python
def connect_to_mlmd() -> metadata_store.MetadataStore:
    metadata_service_host = os.environ.get('METADATA_GRPC_SERVICE_SERVICE_HOST', 'metadata-grpc-service')
    metadata_service_port = int(os.environ.get('METADATA_GRPC_SERVICE_SERVICE_PORT', 8080))

   mlmd_connection_config = metadata_store_pb2.MetadataStoreClientConfig(
        host=metadata_service_host,
        port=metadata_service_port,
    )
```

---

All in all, I think we should do some modifications making our manifests and `metadata-writer` code correspond to the main Metadata installation.

Any thoughts?

cc @Ark-kun, since it was mainly you who wrote Metadata Writer and its manifests.
