### ISSUE TITLE
Registed Metadata type is not detected corretly

### ISSUE THREAD

**Issue by vmolina** [kubeflow/pipelines#3100]
Artifacts are registered to the metadata as None type, independenly of the component spec.

I created the following spec.
```yaml
name: Get Data Iris
description: This operator gets the data for the sample model.
inputs:
  - {name: Base output path, type: GCSPath, description: 'GCS Path to output the data'}
  - {name: Train size, type: float, description: 'Size of the train'}
outputs:
  - {name: Train data, type: "data_set", description: 'GCS path for training data'}
  - {name: Validation data, type: "data_set", description: 'GCS path for validation data'}
implementation:
  container:
    image: $DEFAULT_IMAGE
    command: ["kf_test_get_data",
      --train-size, {inputValue: Train size},
      --output-path,  {inputValue: Base output path},
      --output-train-path-file, {outputPath: Train data},
      --output-validation-path-file, {outputPath: Validation data}
    ]
```

I created the pipeline, upload it and created a run of the pipeline.

I expect the output Train data registered artifact in metadata to have the type data_set., but all artifacts get assigned the NonType

### Environment:
Kubeflow pipelines 0.2.2 running on GCP with CloudSQL for metadata

How did you deploy Kubeflow Pipelines (KFP)?
Standalone Kubeflow Pipelines 0.2.2
KFP version: Build commit: 9ffd11a

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area backend
