### ISSUE TITLE
 Pipeline UI unable to access artifacts stored in S3

### ISSUE THREAD

**Issue by Shasvat0601** [kubeflow/pipelines#3366]
I am trying to visualize confusion matrix in my kubeflow pipeline.
`source` of confusion matrix is s3 storage.

I have mounted AWS secret as a volume to the ui-pod
But the UI-Pod is getting 500:access denied error when trying to fetch data from aws s3 bucket to visualize the confusion matrix.

this is my UI-pod: It has secret mounted as a volume
**UI-Pod**
```
Container ID: docker://415762af72b61d51503cf923f10904ad9ec9d5dd1e84d2b13d9ca812f664dfee
Image:          gcr.io/ml-pipeline/frontend:0.1.31
Image ID:       docker-pullable://gcr.io/ml-pipeline/frontend@sha256:7022552d3481edab0e683f9fcdad2ee29f2cabcfd54536d63dfaf20c101a6ed6
Port:           3000/TCP
Host Port:      0/TCP
State:          Running
  Started:      Mon, 09 Dec 2019 18:01:29 -0500
Ready:          True
Restart Count:  0
Environment:    <none>
Mounts:
  /var/run/secrets/kubernetes.io/serviceaccount from ml-pipeline-ui-token-265pv (ro)
Volumes:
  ml-pipeline-ui-token-265pv:
  Type:        Secret (a volume populated by a Secret)
  SecretName:  ml-pipeline-ui-token-265pv
  Optional:    false`
```

Below is the secret volume details

**secret volume**
```
Name:         ml-pipeline-ui-token-265pv
Namespace:    kubeflow
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: ml-pipeline-ui
              kubernetes.io/service-account.uid: d37035e2-1ad7-11ea-80bd-02134654031a

Type:  kubernetes.io/service-account-token

Data
====
namespace:  8 bytes
token:    XXXXXXXXX
ca.crt:     1042 bytes
```
This is the stacktrace and the error I am facing:

![image](https://user-images.githubusercontent.com/52177950/77569174-269f0580-6ea0-11ea-8803-f57ec3082788.png)

@Jeffwan @eterna2 @Ark-kun 
Any insight from you all will be really helpful and is highly appreciated!! :)
linked issues:
#2627 #1278

**Comment by Jeffwan** [comment]
Seems the error is access denied. @Shasvat0601 Can you verify you have S3 permission in UI? Could you show the config?

**Comment by Jeffwan** [comment]
confusion metrics works fine on my side.

Can you try to create an `aws-secret` and then update your UI container env to use it? 

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kubeflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: your_base64_string
  AWS_SECRET_ACCESS_KEY: your_base64_string
```

```
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-secret
```
