### ISSUE TITLE
Backend - Reject invalid pipelines

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3526]
The backend should use Argo's lining capabilities to validate workflows at upload time. Or at least try to unmarshal the YAML into an Argo Workflow object. Otherwise, the users only get errors at run submission time.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  templates:
  - container:
      name: main
      args: [x, y, z]
```
