### ISSUE TITLE
Accessing execution date when backfilling

### ISSUE THREAD

**Issue by omarzouk** [kubeflow/pipelines#3704]
### What did you expect to happen:
How do I inform my pipeline of the timestamp it is supposed to "backfill" when a recurring run is "chatching up" (has early start date and `catchup=true`)? Airflow has `{{ execution_date }}` and `{{ prev_execution_date }}` macros that you can access and pass to your components. For example I can use it to specify which bigquery partition to read from and write to.

What is the equivalent in Kubeflow? I tried using `workflow.creationTimestamp` but it doesn't seem to follow the backfill schedule, it just uses the current datetime.

KFP version: 0.2.5

/kind feature
/kind question

**Comment by omarzouk** [comment]
Okay so I found [retrieveScheduledTime](https://github.com/kubeflow/pipelines/blob/master/backend/src/crd/controller/scheduledworkflow/client/workflow_client.go#L111) which seems to be using this label `workflow.labels.workflowEpoch`. However upon testing it, I still got the creationTimestamp. Also, it seems the label is only set during scheduling which causes the pipeline to blow up when trying to do a normal "run" giving `invalid spec: templates.whalesay: failed to resolve {{workflow.labels.workflowEpoch}}`

**Comment by omarzouk** [comment]
Okay so after piecing together information from [constants.go](https://github.com/kubeflow/pipelines/blob/23e522a3d31f0358b337408a52a2670179913c4e/resources/scheduledworkflow/util/constants.go#L27) the label is actually called `{{workflow.labels.scheduledworkflows.kubeflow.org/workflowEpoch}}` .

This works with scheduled runs. However if I try a one-off, the pipeline fails with this error: `invalid spec: templates.whalesay: failed to resolve {{workflow.labels.scheduledworkflows.kubeflow.org/workflowEpoch}}`

How can I get around this? so that the one-offs don't fail?

Also, it would be nice if this is exposed in the python SDK directly, similar to to how `RUN_ID_PLACEHOLDER = '{{workflow.uid}}'` is exposed

new test DAG file:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{workflow.labels.scheduledworkflows.kubeflow.org/workflowEpoch}}"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```
