### ISSUE TITLE
How to pass 'None' to a string flag of a docker container?

### ISSUE THREAD

**Issue by sadeel** [kubeflow/pipelines#3746]
### What steps did you take:
I have a python flag which looks like this:

```python
flags.DEFINE_float('val_fraction', None,  'Fraction of train data to use for validation.')
```
This flag is exposed as part of a KFP parameter. When not specified in the KFP UI, it seems to pass the flag as an empty string to the python program rather than None. Here is my component:

```python
inputs:
  - {name: val_dir, optional: true}
implementation:
  container:
    image: container
    command: [python3, -m, models.mil.train]
    args: [
      --val_dir, {inputValue: val_dir},
    ]
```

### What happened:
Parameter passed as string

### What did you expect to happen:
Parameter to be passed as none-type.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
Hosted KFP

KFP version: 0.5.1

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
First let's separate KFP issues from non-KFP issues.

How would you "pass 'None' to a string flag of a docker container" without KFP? (For example, when you use Docker or just use command-line and terminal.)

Maybe, in you case the answer is "Just do not include the --val_dir flag in the command-line arguments."

In this case your command-line changes (the number of argument changes) depending on some predicate. There is a limited support for that, but only for compile-time constants or the `{isPresent: input_name}` predicate which is also evaluated at compile-time.

```
inputs:
  - {name: val_dir, optional: true}
implementation:
  container:
    image: container
    command: [python3, -m, models.mil.train]
    args:
    - if:
      cond: {isPresent: val_dir}
      then: ['--val_dir', {inputValue: val_dir}],
```

If this is not sufficient for you, then the workaround is to modify the code so that it converts empty strings to `None`.

WDYT?
