### ISSUE TITLE
Generate a YAML Component Spec from a Python DSL component function

### ISSUE THREAD

**Issue by sm-hawkfish** [kubeflow/pipelines#3748]
Hi everyone,

Using the [kfp.dsl.component ](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html#kfp.dsl.component) decorator to define KFP Components is a great user experience, since it leverages standard features of the Python language like type annotations and docstring inspection. By contrast, the YAML Component specification requires engineers to learn a new syntax and is generally more verbose than the Python equivalent (especially when it comes to writing custom type definitaions using the OpenAPI Schema)

That said, one advantage of the YAML spec that was raised in the Slack channel is around the ease of distributing a readily parseable file format to a variety of different client applications.

Since both formats have their pros and cons, **the purpose of this issue is to discuss the value and feasibility of adding functionality to the KFP Python SDK to support generating the YAML specification from the Python DSL component definition.** This would give the users the best of both worlds by allowing them to define components comfortably in Python and to ship Component specifications to downstream clients in YAML.

By way of example, consider the following (equivalent) specifications of a `Dummy op`:

```python
from kfp import dsl
from kfp.dsl.types import GCSPath
from kfp.dsl.types import String


@dsl.component
def dummy_op(input1: String(), input2: GCSPath()) -> {"output1": GCSPath()}:
    """
    Dummy component for illustrative purposes
    """
    output1 = "/tmp/python_dummy_op/output1_path"
    return dsl.ContainerOp(
        name="Dummy op",
        image="dummy-image",
        command=[
            "python",
            "runner.py",
            "--input1",
            input1,
            "--input2",
            input2,
            "--output1",
            output1,
        ],
        file_outputs={"output1": output1},
    )
```

```yaml
name: Dummy op
description: Dummy component for illustrative purposes
inputs:
- {name: input1, type: {String: {openapi_schema_validator: {type: string}}}}
- {name: input2, type: {GCSPath: {openapi_schema_validator: {type: string, pattern: ^gs://.*$}}}}
outputs:
- {name: output1, type: {GCSPath: {openapi_schema_validator: {type: string, pattern: ^gs://.*$}}}}
implementation:
  container:
    image: dummy-image
    command:
      - python3
      - runner.py
      - --input1
      - inputValue: input1
      - --input2
      - inputValue: input2
      - --output1
      - outputPath: output1
```

When compiled into Pipelines, the Component Metadata is nearly identical:
```python
@dsl.pipeline(
    name="Python Pipeline",
    description="Demonstrate use of Python DSL",
)
def python_pipeline(input1: String(), input2: GCSPath()):
    dummy_task = dummy_op(input1=input1, input2=input2)
    print("Python Pipeline", dummy_task._metadata)


@dsl.pipeline(
    name="YAML Pipeline",
    description="Demonstrate use of YAML component spec",
)
def yaml_pipeline(input1: String(), input2: GCSPath()):
    dummy_task = yaml_dummy_op(input1=input1, input2=input2)
    print("YAML Pipeline", dummy_task._metadata)


if __name__ == "__main__":
    kfp.compiler.Compiler().compile(python_pipeline, "python_pipeline.tar.gz")
    kfp.compiler.Compiler().compile(yaml_pipeline, "yaml_pipeline.tar.gz")
```
Yields:
```
Python Pipeline
{'description': 'Dummy component for illustrative purposes',
 'inputs': [{'name': 'input1',
             'type': {'String': {'openapi_schema_validator': {'type': 'string'}}}},
            {'name': 'input2',
             'type': {'GCSPath': {'openapi_schema_validator': {'pattern': '^gs://.*$',
                                                               'type': 'string'}}}}],
 'name': 'Dummy op',
 'outputs': [{'name': 'output1',
              'type': {'GCSPath': {'openapi_schema_validator': {'pattern': '^gs://.*$',
                                                                'type': 'string'}}}}]}


YAML Pipeline
{'description': 'Dummy component for illustrative purposes',
 'inputs': [{'name': 'input1',
             'type': {'String': OrderedDict([('openapi_schema_validator',
                                              OrderedDict([('type',
                                                            'string')]))])}},
            {'name': 'input2',
             'type': {'GCSPath': OrderedDict([('openapi_schema_validator',
                                               OrderedDict([('type', 'string'),
                                                            ('pattern',
                                                             '^gs://.*$')]))])}}],
 'name': 'Dummy op',
 'outputs': [{'name': 'output1',
              'type': {'GCSPath': OrderedDict([('openapi_schema_validator',
                                                OrderedDict([('type', 'string'),
                                                             ('pattern',
                                                              '^gs://.*$')]))])}}]}
```

CC'ing @Bobgy and @eterna2 since they were involved in the Slack discussion as well (I was unable to find Lida Li's Github username).
