### ISSUE TITLE
[KF 1.0 Compliance] liveness and readiness probes

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3756]
Part of https://github.com/kubeflow/pipelines/issues/2884

This is required.
> The application should expose liveness and/or readiness signals as appropriate for the application

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

An additional challenge with us, is that we need to make sure the probes work with istio mutual TLS (which protects all traffic with istio managed TLS certificates).
Workarounds are documented https://istio.io/faq/security/#k8s-health-checks.
Istio 1.1 didn't include the probe rewrite admission webhook, so the only suitable workaround for us is https://github.com/kubeflow/kubeflow/issues/4865#issuecomment-600951491

Using a liveness/readiness command to probe the port with curl.
```
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:3000/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
```

Other workarounds that are not suitable now:
* separate port, uses a different port for health check and let istio allow traffic to it (needs application code change, so not desirable)
* probe rewrite, needs istio 1.2+

/cc @yanniszark @IronPan @rmgogogo
