### ISSUE TITLE
[KF 1.0 Compliance] Vulnerability Scanning

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3857]
Part of https://github.com/kubeflow/pipelines/issues/2884

> Docker images must be scanned for vulnerabilities and known vulnerabilities published

@jlewi Do you know how other images share vulnerability issues?

I did a quick investigation, gcr.io provides vulnerability scanning, but the result is not visible to external visitors even if the image is public.

We can export the generated yaml report with commands like
```
gcloud beta container images describe --show-package-vulnerability gcr.io/ml-pipeline/api-server:1.0.0-test-5
```
Documented in https://cloud.google.com/container-registry/docs/get-image-vulnerabilities

Do you think that's good enough?

**Comment by Bobgy** [comment]
@jbottum Do you have any ideas about this?

**Comment by jlewi** [comment]
kubeflow/kubeflow#3907 is tracking how we publish a list of vulnerabilities in our images.

A related issue is minimizing vulnerabilities e.g. by using distroless images.
There is documentation at
https://github.com/krishnadurai/community/blob/b1669588d785455a1e4e4cab456e03c08a05af7c/guidelines/creating_dockerfiles.md

Note the use of distroless images is recommended not a requirement.

kubeflow/kubeflow#4590 is a related issue about promoting the use of distroless in Kubeflow to minimize vulnerabilities.

To satisfy the vulnerability scanning requirement I think you just need to turn on vulnerability scanning in whatever GCR registry you are hosting your images in.

You might want to repurpose this issue or file a new one for reducing vulnerabilities if relevant.

**Comment by Bobgy** [comment]
@jlewi As reported in the kubeflow/kubeflow#3907, if we enable gcr vulnerability scanning, they are not visible for external viewers.
We'd still need to dump a yaml report for each KFP release, sounds reasonable?

**Comment by Bobgy** [comment]
Thanks for the relevant link to reducing vulnerability. I'll create a separate issue about it.

**Comment by Bobgy** [comment]
An example of fixing some vulnerability issues: https://github.com/kubeflow/pipelines/issues/4531

**Comment by Bobgy** [comment]
AIs:
* [ ] formalize a vulnerability management process
* [ ] understand current image vulnerability status and triage urgent fixes
* [ ] build the needed vulnerability scanning automation that flag High and Critical issues before release and send vulnerability reports for each KFP release.

**Comment by Bobgy** [comment]
Requests to reduce vulnerabilities come more often than before, so I'm taking some time to continue this.

**Comment by Bobgy** [comment]
## formalize a vulnerability management process

I think the process should come with two parts:
1. set up a process to update dependencies/base images more frequently

this is already being addressed in https://github.com/kubeflow/pipelines/issues/4682

2. add an automated vulnerability policy check step in our CI/CD pipelines

I'll focus on 2. in this issue.

**Comment by Bobgy** [comment]
Research of tools suitable for this need:
* Google Cloud provides vulnerability scanning in container analysis service, but it can only provide information for what we need. It lacks required tools to integrate in a CI/CD pipeline. https://cloud.google.com/container-analysis/docs/vulnerability-scanning
* Kritis is a nice tool built by GCP, https://cloud.google.com/binary-authorization/docs/creating-attestations-kritis#check-only. It supports vulnerability policy like the following and integrates with data from Google Container Analysis:
    ```
    apiVersion: kritis.grafeas.io/v1beta1
    kind: VulnzSigningPolicy
    metadata:
      name: my-vsp
    spec:
      imageVulnerabilityRequirements:
        maximumFixableSeverity: MEDIUM
        maximumUnfixableSeverity: MEDIUM
        allowlistCVEs:
        - projects/goog-vulnz/notes/CVE-2020-10543
        - projects/goog-vulnz/notes/CVE-2020-10878
        - projects/goog-vulnz/notes/CVE-2020-14155
    ```

Using them combined seem to meet our basic needs.
