### ISSUE TITLE
Metadata Writer stopped getting the artifact types

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3971]
All outputs are getting recorded as NoType.
```yaml
annotations:
    pipelines.kubeflow.org/component_spec: >-
      {"name": "Create visualizations", "outputs": [{"name": "Some Url 1",
      "type": "URI"}, {"name": "Some Url 2", "type": {"URI": {"data_type":
      "something"}}}, {"name": "Some HTML", "type": "HTML"}, {"name": "Some
      Markdown", "type": "Markdown"}, {"name": "Some metrics", "type":
      "Metrics"}]}
    pipelines.kubeflow.org/metadata_input_artifact_ids: '[]'
    pipelines.kubeflow.org/metadata_output_artifact_ids: >-
      [{"id": 32, "name": "some_html", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_html.tgz",
      "type": "NoType"}, {"id": 33, "name": "some_markdown", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_markdown.tgz",
      "type": "NoType"}, {"id": 34, "name": "some_metrics", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_metrics.tgz",
      "type": "NoType"}, {"id": 35, "name": "some_url_1", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_url_1.tgz",
      "type": "NoType"}, {"id": 36, "name": "some_url_2", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_url_2.tgz",
      "type": "NoType"}, {"id": 37, "name": "main-logs", "uri":
      "minio://mlpipeline/artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/main.log",
      "type": "NoType"}]
    sidecar.istio.io/inject: 'false'
    workflows.argoproj.io/node-name: create-visualizations-2-7sxmn.create-visualizations
    workflows.argoproj.io/outputs: >-
      {"artifacts":[{"name":"create-visualizations-some_html","path":"/tmp/outputs/Some_HTML/data","s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_html.tgz"}},{"name":"create-visualizations-some_markdown","path":"/tmp/outputs/Some_Markdown/data","s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_markdown.tgz"}},{"name":"create-visualizations-some_metrics","path":"/tmp/outputs/Some_metrics/data","s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_metrics.tgz"}},{"name":"create-visualizations-some_url_1","path":"/tmp/outputs/Some_Url_1/data","s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_url_1.tgz"}},{"name":"create-visualizations-some_url_2","path":"/tmp/outputs/Some_Url_2/data","s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/create-visualizations-some_url_2.tgz"}},{"name":"main-logs","archiveLogs":true,"s3":{"endpoint":"minio-service.default:9000","bucket":"mlpipeline","insecure":true,"accessKeySecret":{"name":"mlpipeline-minio-artifact","key":"accesskey"},"secretKeySecret":{"name":"mlpipeline-minio-artifact","key":"secretkey"},"key":"artifacts/create-visualizations-2-7sxmn/create-visualizations-2-7sxmn-3549616354/main.log"}}]}

```
