### ISSUE TITLE
Cache - Limit the attributes that affect the cache key

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3972]
A customer has reported this issue. They're adding unique run_id labels to the tasks which effectively disables the cache. They want those labels to not prevent cache reuse.

Currently the cache key is based on the whole Argo template spec excluding the outputs.

We may switch to a limited subset:
```yaml
template:
  inputs: ...
  container:
    image: ....
    command: ...
    args: ...
    env: ...
    volumeMounts:
  volumes:
```
