### ISSUE TITLE
De-hardcode output paths in all components

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4100]
Some components are using the deprecated `fileOutputs` attribute. See the [query](
https://github.com/kubeflow/pipelines/search?q=fileOutputs+filename%3Acomponent.yaml&unscoped_q=fileOutputs+filename%3Acomponent.yaml)

The `fileOutputs` was deprecated from the start and should not be used in any non-legacy components.

We need to migrate from the deprecated `fileOutputs` to use the correct `{outputPath: output_name}` command-line placeholders instead.

Example:

Before:
```yaml
implementation:
  container:
    command:
    - my_prog.py
    - --param1
    - value1
    fileOutputs:
      some_output: /some/hardcoded/path
```
After:
```yaml
implementation:
  container:
    command:
    - my_prog.py
    - --param1
    - value1
    - --some-output
    - {outputPath: some_output}
```

The component code should be modified to receive all output paths through command-line arguments instead of hard-codong any paths.

An example of the correction: https://github.com/kubeflow/pipelines/pull/580/files#diff-9c31c4b41f436d2bbdfc9c97d40b9fe1
https://github.com/kubeflow/pipelines/pull/580/files#diff-ec0c67e038e3087e2bb01d439771bddc

There are two main groups of affected components:

- [x] [GCP components](https://github.com/kubeflow/pipelines/search?q=fileOutputs+filename%3Acomponent.yaml+aws&unscoped_q=fileOutputs+filename%3Acomponent.yaml+gcp) Issue: https://github.com/kubeflow/pipelines/issues/4128 PR: https://github.com/kubeflow/pipelines/pull/4123
- [x] [AWS components](https://github.com/kubeflow/pipelines/search?q=fileOutputs+filename%3Acomponent.yaml+aws&unscoped_q=fileOutputs+filename%3Acomponent.yaml+aws) Issue: https://github.com/kubeflow/pipelines/issues/4101 PR: https://github.com/kubeflow/pipelines/pull/4119
- [ ] IBM components. Isssue: https://github.com/kubeflow/pipelines/issues/4129
- [x] The remaining few cases. PR: https://github.com/kubeflow/pipelines/pull/580
