### ISSUE TITLE
Names of file inputs with raw arguments are not properly sanitized by the compiler

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4110]
When passing output references to inputs consumed as files, everything works fine.
When passing constant strings to inputs consumed as files, the artifact names are not sanitized leading to invalid workflows.

```yaml
templates:
    - inputs:
      parameters:
      - {name: model_dir_uri}
      artifacts:
      - raw: {data: ''}
        path: /tmp/inputs/Default_data/data
        name: Default data
```

```
invalid spec: templates.continuous-training-pipeline.tasks.download-from-gcs templates.download-from-gcs.inputs.artifacts[0].name: 'Default data' is invalid: Parameter/Artifact name must consist of alpha-numeric characters, '_' or '-' e.g. my_param_1, MY-PARAM-1
```
