### ISSUE TITLE
De-hardcode output paths in IBM components

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4129]
See the parent issue: https://github.com/kubeflow/pipelines/issues/4100

Some components are using the deprecated `fileOutputs` attribute. See the [query](
https://github.com/kubeflow/pipelines/search?q=fileOutputs+filename%3Acomponent.yaml&unscoped_q=fileOutputs+filename%3Acomponent.yaml)

The `fileOutputs` was deprecated from the start and should not be used in any non-legacy components.

We need to migrate from the deprecated `fileOutputs` to use the correct `{outputPath: output_name}` command-line placeholders instead.

Example:

Before:
```yaml
implementation:
  container:
    command:
    - my_prog.py
    - --param1
    - value1
    fileOutputs:
      some_output: /some/hardcoded/path
```
After:
```yaml
implementation:
  container:
    command:
    - my_prog.py
    - --param1
    - value1
    - --some-output
    - {outputPath: some_output}
```

The component code should be modified to receive all output paths through command-line arguments instead of hard-codong any paths.

An example of the correction: https://github.com/kubeflow/pipelines/pull/580/files#diff-9c31c4b41f436d2bbdfc9c97d40b9fe1
https://github.com/kubeflow/pipelines/pull/580/files#diff-ec0c67e038e3087e2bb01d439771bddc
