### ISSUE TITLE
How to configure artifact storage authenication parameter?

### ISSUE THREAD

**Issue by sakaia** [kubeflow/pipelines#4148]
I want to use kubeflow pipeline with Google Cloud Storage,
because sample code frequently uses `gs://`.
For this case which parameter, should I set?
Just editing configmap of `workflow-controller-configmap`.
Also I checked `kfp diagnose_me', it seems no parameter set for artifact.

```bash
$ kubectl describe configmap workflow-controller-configmap -n kubeflow
```
Some part is follows.

```yaml
{
executorImage: argoproj/argoexec:v2.3.0,
containerRuntimeExecutor: docker,
artifactRepository:
{
    s3: {
        bucket: mlpipeline,
        keyPrefix: artifacts,
        endpoint: minio-service.kubeflow:9000,
        insecure: true,
        accessKeySecret: {
            name: mlpipeline-minio-artifact,
            key: accesskey
        },
        secretKeySecret: {
            name: mlpipeline-minio-artifact,
            key: secretkey
        }
    }
}
}
```

```bash
kfp diagnose_me
```
some part is follows

```shell
================ GET_GCLOUD_DEFAULT ===================
[accessibility]
screen_reader (unset)
[app]
cloud_build_timeout (unset)
promote_by_default (unset)
stop_previous_version (unset)
use_runtime_builders (unset)
[artifacts]
location (unset)
repository (unset)
[auth]
disable_credentials (unset)
impersonate_service_account (unset)
[billing]
quota_project (unset)
[builds]
kaniko_cache_ttl (unset)
timeout (unset)
use_kaniko (unset)
[component_manager]
additional_repositories (unset)
disable_update_check (unset)
[composer]
location (unset)
[compute]
region (unset)
use_new_list_usable_subnets_api (unset)
zone (unset)
[container]
build_timeout (unset)
cluster (unset)
use_application_default_credentials (unset)
use_client_certificate (unset)
[context_aware]
use_client_certificate (unset)
[core]
account = shypervisor@gmail.com
custom_ca_certs_file (unset)
default_regional_backend_service (unset)
disable_color (unset)
disable_file_logging (unset)
disable_prompts (unset)
disable_usage_reporting = True
log_http (unset)
max_log_days (unset)
pass_credentials_to_gsutil (unset)
project = sincere-concept-282022
show_structured_logs (unset)
trace_token (unset)
user_output_enabled (unset)
verbosity (unset)
[dataflow]
disable_public_ips (unset)
print_only (unset)
[datafusion]
location (unset)
[dataproc]
region (unset)
[deployment_manager]
glob_imports (unset)
[filestore]
location (unset)
zone (unset)
[functions]
region (unset)
[game_services]
default_deployment (unset)
default_realm (unset)
location (unset)
[gcloudignore]
enabled (unset)
[healthcare]
dataset (unset)
location (unset)
[interactive]
bottom_bindings_line (unset)
bottom_status_line (unset)
completion_menu_lines (unset)
context (unset)
fixed_prompt_position (unset)
help_lines (unset)
hidden (unset)
justify_bottom_lines (unset)
manpage_generator (unset)
multi_column_completion_menu (unset)
prompt (unset)
show_help (unset)
suggest (unset)
[lifesciences]
location (unset)
[memcache]
region (unset)
[ml_engine]
local_python (unset)
polling_interval (unset)
[notebooks]
location (unset)
[proxy]
address (unset)
password (unset)
port (unset)
rdns (unset)
type (unset)
username (unset)
[redis]
region (unset)
[run]
cluster (unset)
cluster_location (unset)
platform (unset)
region (unset)
[scc]
organization (unset)
[secrets]
locations (unset)
replication-policy (unset)
[spanner]
instance (unset)
[survey]
disable_prompts (unset)
[vmware]
location (unset)
```

Reference
- [Configuring Your Artifact Repository](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#configuring-gcs-google-cloud-storage)

**Comment by sakaia** [comment]
Thank you, my understanding little progressed.

## How to setup sample/core/secret/secret.py on standalone?

I am try to execute sample/core/secret on stamdalone.But It fails.
on `method use_gcp_api_op()`. 
These containers output (describe)attached below.

From seeing the Pipeline Standalone (see Ref), the `use_gcp_secret` can set by follwoing instruction.
From seeing the code of secret.py, it does not use `use_gcp_secret`



## Reference

Cluster setup to use use_gcp_secret for Pipelines Standalone 
  https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/#cluster-setup-to-use-use_gcp_secret-for-pipelines-standalone

## Source code seems follows
###  sample code is here
   https://github.com/kubeflow/pipelines/blob/master/samples/core/secret/secret.py

###  `use_gcp_secret` method is here
  https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/gcp.py#L18

## Container outputs
### `gcs_read_op()` output is follows  (successful)

```yaml
Name:           secret-pipeline-k9hvx-1409361145
Namespace:      kubeflow
Priority:       0
Node:           ip-10-10-174-153/10.10.174.153
Start Time:     Wed, 08 Jul 2020 05:22:10 +0000
Labels:         workflows.argoproj.io/completed=true
                workflows.argoproj.io/workflow=secret-pipeline-k9hvx
Annotations:    workflows.argoproj.io/node-message: timeout after 0s
                workflows.argoproj.io/node-name: secret-pipeline-k9hvx.access-gcs-using-auth-token
                workflows.argoproj.io/template:
                  {"name":"access-gcs-using-auth-token","inputs":{"parameters":[{"name":"url","value":"gs://ml-pipeline/sample-data/shakespeare/shakespeare1...
Status:         Succeeded
IP:             10.1.1.101
Controlled By:  Workflow/secret-pipeline-k9hvx
Containers:
  wait:
    Container ID:  containerd://b5a5cf5ac3b7dba72c2ccd28eea4f4014ba0a920db56227e7e6fe37de97ac3d6
    Image:         argoproj/argoexec:v2.3.0
    Image ID:      docker.io/argoproj/argoexec@sha256:85132fc2c8bc373fca885df17637d5d35682a23de8d1390668a5e1c149f2f187
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 08 Jul 2020 05:22:11 +0000
      Finished:     Wed, 08 Jul 2020 05:22:12 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    secret-pipeline-k9hvx-1409361145 (v1:metadata.name)
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  k8sapi
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pipeline-runner-token-7269p (ro)
  main:
    Container ID:  containerd://cc3a4f74de01b5468d61fc053df485801663c5cdc26fec353a14d497ba59f93f
    Image:         google/cloud-sdk:279.0.0
    Image ID:      docker.io/google/cloud-sdk@sha256:ce27a40af01cefc3f6a1f2d05ad036364a521d0b61dcc5273f2516347792977f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      gsutil ls "$0" && echo "$1"
      gs://ml-pipeline/sample-data/shakespeare/shakespeare1.txt
      Auth token is located at /secret/gcp-credentials/user-gcp-sa.json
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 08 Jul 2020 05:22:12 +0000
      Finished:     Wed, 08 Jul 2020 05:22:13 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pipeline-runner-token-7269p (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  pipeline-runner-token-7269p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pipeline-runner-token-7269p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

### `use_gcp_api_op()` output is follows (failed)

```yaml
kubectl describe pod secret-pipeline-k9hvx-2761039421 -n kubeflow
Name:           secret-pipeline-k9hvx-2761039421
Namespace:      kubeflow
Priority:       0
Node:           ip-10-10-174-153/10.10.174.153
Start Time:     Wed, 08 Jul 2020 05:22:10 +0000
Labels:         workflows.argoproj.io/completed=true
                workflows.argoproj.io/workflow=secret-pipeline-k9hvx
Annotations:    workflows.argoproj.io/node-name: secret-pipeline-k9hvx.using-google-cloud-apis-with-auth
                workflows.argoproj.io/template:
                  {"name":"using-google-cloud-apis-with-auth","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"google/cloud-sdk:279.0....
Status:         Failed
IP:             10.1.1.102
Controlled By:  Workflow/secret-pipeline-k9hvx
Containers:
  wait:
    Container ID:  containerd://797cda2bd5087a30ad8afeea1acfbf7e4355267550d0b4049d02c6d1b87178b7
    Image:         argoproj/argoexec:v2.3.0
    Image ID:      docker.io/argoproj/argoexec@sha256:85132fc2c8bc373fca885df17637d5d35682a23de8d1390668a5e1c149f2f187
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 08 Jul 2020 05:22:11 +0000
      Finished:     Wed, 08 Jul 2020 05:22:18 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    secret-pipeline-k9hvx-2761039421 (v1:metadata.name)
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  k8sapi
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pipeline-runner-token-7269p (ro)
  main:
    Container ID:  containerd://3c28cb98d5ad6899daec0945f5e6a55df9abf9f7316a4096f35bcdbfe6104c93
    Image:         google/cloud-sdk:279.0.0
    Image ID:      docker.io/google/cloud-sdk@sha256:ce27a40af01cefc3f6a1f2d05ad036364a521d0b61dcc5273f2516347792977f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      pip3 install google-cloud-storage && "$0" "$*"
      python3
      -c

      from google.cloud import storage
      storage_client = storage.Client()
      buckets = storage_client.list_buckets()
      print("List of buckets:")
      for bucket in buckets:
          print(bucket.name)

    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 08 Jul 2020 05:22:12 +0000
      Finished:     Wed, 08 Jul 2020 05:22:17 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pipeline-runner-token-7269p (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  pipeline-runner-token-7269p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pipeline-runner-token-7269p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
