### ISSUE TITLE
DSL compilation fails when pipeline has op with the same name as the pipeline itself

### ISSUE THREAD

**Issue by post2web** [kubeflow/pipelines#428]
Here is an example pipeline to recreate the issue:
```python
import kfp
import kfp.dsl as dsl

class ExampleOp(kfp.dsl.ContainerOp):
    def __init__(self, name):
        super(ExampleOp, self).__init__(
            name=name,
            image='gcr.io/metal-celerity-204001/example',
            file_outputs={'return-code': '/tmp/return-code.txt'})

@dsl.pipeline(
    name='Example',
    description='Generated')
def example_pipeline():
    example_op = ExampleOp(name='example')

if __name__ == '__main__':
    import kfp.compiler as compiler
    compiler.Compiler().compile(example_pipeline, 'example.tar.gz')
```
When the pipeline is run, I get an error message:
```
An error occurred
invalid spec: spec.templates[1].name 'example' is not unique
```
This error is triggered because the name of the operation matches the last part of the image url. The pipeline would run as expected if I chnage `ExampleOp(name='example')` to `ExampleOp(name='something_else')`.

**Comment by Ark-kun** [comment]
This is a bug and we will fix it.

BTW, you should probably remove `name` parameter from `def __init__(self, name):` and just set it in the base class constructor call. 
```
 super(ExampleOp, self).__init__(
            name='Example operation',
```
This name no longer needs to be unique among the operations.

P.S.
>file_outputs={'return-code': '/tmp/return-code.txt'}

To future-proof you containers, please make the input and output locations are configurable from the command line. It's also useful to have the `command` set instead of relying on the container entry point:
```
command=['/program_path/program.py'],
arguments=[ '--input', '/inputs/data/file', '--output', '/outputs/return-code/file'],
```

**Comment by vicaire** [comment]
@Ark-kun, is this bug fixed?

**Comment by Ark-kun** [comment]
> This error is triggered because the name of the operation matches the last part of the image url.

I think the actual problem is that op name is the same as the pipeline name.

**Comment by post2web** [comment]
> > This error is triggered because the name of the operation matches the last part of the image url.
> 
> I think the actual problem is that op name is the same as the pipeline name.

The snippet I originally posted doesn't seem to trigger the error anymore. I think this should be closed.

**Comment by David-LiCause** [comment]
I experience a similar issue trying to run a pipeline that has the same 'name' argument as the component.yaml file. 

```
# Example component.yaml 
name: Example
description: |
  Example component description
inputs:
  - {name: Argument 1, type: String, description: 'Argument description'}
  - {name: Argument 2, type: String, description: 'Argument description'}
outputs:
  - {name: Output}


implementation:
  container:
    image: gcr.io/project

    args: [
      --arg1, {inputValue: Argument 1},
      --arg2, {inputValue: Argument 2}
    ]
```

```
# Example pipeline.py
import kfp
import kfp.dsl as dsl
import kfp.gcp as gcp
from kfp.components import load_component_from_file

ExampleOp = load_component_from_file('component.yaml')

@dsl.pipeline(
    name='Example',
    description='Generated')
def example_pipeline(
    arg1=dsl.PipelineParam(name="Argument 1"),
    arg2=dsl.PipelineParam(name="Argument 2")):

    example_op = ExampleOp(
        arg1=arg1,
        arg2=arg2
    ).apply(gcp.use_gcp_secret('user-gcp-sa'))

if __name__ == '__main__':
    import kfp.compiler as compiler
    compiler.Compiler().compile(example_pipeline, 'pipeline.tar.gz')
```

When I run this I get the same error message as above: 
```
An error occurred
invalid spec: spec.templates[1].name 'example' is not unique
```

Changing the 'name' argument in the pipeline fixes the issue for me. I'm using kfp version 0.1.12
