### ISSUE TITLE
Error when using microk8s: failed to save outputs: Error response from daemon: No such container:

### ISSUE THREAD

**Issue by tomalbrecht** [kubeflow/pipelines#4302]
### What steps did you take:
I ran [/samples/core/lightweight_component/lightweight_component.ipynb](https://github.com/kubeflow/pipelines/blob/master/samples/core/lightweight_component/lightweight_component.ipynb). Running all cells seems ok. I did not change the tutorial code.

![image](https://user-images.githubusercontent.com/17781570/89003863-28228380-d301-11ea-9dad-d3df05f54314.png)

### What happened:

When viewing the run, the pipeline crashed within the "add" function.
![image](https://user-images.githubusercontent.com/17781570/89003117-2e176500-d2ff-11ea-89ae-219665b53af1.png)

### What did you expect to happen:

I expected the pipeline to complete without errors.

### Environment:
* Kubeflow: 1.0.2
* Microk8s: v1.18.6-1+64f53401f200a7
* Linux: Ubuntu 18.04
* Notebook Pipeline Version: 1.0.0 (Notebook Server: print("kfp Version: {}".format(kfp.__version__)))

How did you deploy Kubeflow Pipelines (KFP)?
As part of a full Kubeflow 1.0.2 deployment.

KFP version: Build commit: 743746b

KFP SDK version: 
* kfp 1.0.0     
* kfp-server-api 1.0.0   

### Anything else you would like to add:
[logs-from-wait-in-calculation-pipeline-g7df4-1345834039.txt](https://github.com/kubeflow/pipelines/files/5005285/logs-from-wait-in-calculation-pipeline-g7df4-1345834039.txt)

Any workarounds or ideas how to further debug and fix it?

/kind bug

**Comment by Bobgy** [comment]
Can you click the step and see what the error message is?

**Comment by tomalbrecht** [comment]
This step is in Error state with this message: failed to save outputs: Error response from daemon: No such container: d98f03a40af58bc2f1a623005d9da0a6b6838822ebf0d11fcf0894291d3d5782

![image](https://user-images.githubusercontent.com/17781570/89010467-eac4f280-d30e-11ea-9e32-8ba7921b5a38.png)

**Comment by alfsuse** [comment]
Hi, @tomalbrecht  I think I've managed to replicate the error and in my case was due to missing capabilities in a pod security policy. 
Do you have, by any chance, one or more PSP deployed? If so the default PSP has either a missing:
` Allowed Capabilities:
  - SYS_PTRACE
  - NET_ADMIN
  - NET_RAW` 
section or have something like "Drop capabilites - ALL" somewhere in it?

A quick& dirty test, if you have a PSP deployed you may simply add:
` allowedCapabilities:
  - '*'`
 under
`spec:
  allowPrivilegeEscalation: false`
and re-run the example. should be fine.
@Bobgy  maybe we should add this to the troubleshooting section for Jupyter/KFP? I can do that.

**Comment by tomalbrecht** [comment]
@alfsuse Thanks for your help. 

I deployed [these](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/) manifests on microk8s. Within the kustomize directory (`/opt/kubeflow/config/kustomize/kubeflow-roles/base`) I found `cluster-roles.yaml` including several cluster roles. 
* Which of these rule I would need change to run the mentioned tutorial?

When I run the code above as a user (not admin) - added like suggested [here](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#add-static-users-for-basic-auth) -  `calc_pipeline 2020-07-31 05-25-28` will be run in namespace `-n kubeflow`. 
* Is this expected or should the pipeline executed within the users namespace, so I do not have to change any PSPs?

**Comment by alfsuse** [comment]
@tomalbrecht  I'm not sure that the cluster-roles or the user are related in this context. I think the issue relay on the presence of a psp, can you run `kubectl get psp - o yaml` and paste here the result? You should have something like this:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
# this section should be missing
  allowedCapabilities: 
  - '*'
########## end of section
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
```
