### ISSUE TITLE
Pipeline with volume does not work with "k8sapi" argo executor

### ISSUE THREAD

**Issue by nakfour** [kubeflow/pipelines#4326]
### What steps did you take:
As part of Open Data Hub we are trying to get KFP 1.0 working on Openshift 4.x. We must use the "k8sapi" executor since docker is not present. Provided KFP python examples work as long as there are no passing parameters. We are trying to convert the KFP examples with passing parameters to use volumes to get them to work on OCP. We tried one of the simple volume creation examples as pointed here (https://github.com/kubeflow/pipelines/blob/master/samples/core/volume_ops/volume_ops.py) This caused an error stating we need to use volumes or emtpyDir. Looking at the generated yaml file we notice these lines
```
outputs:
      parameters:
      - name: create-pvc-manifest
        valueFrom: {jsonPath: '{}'}
      - name: create-pvc-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: create-pvc-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
```
These need to be placed in emptyDir or volumes. We modified the generated yaml file to exclude the output and that worked. 

Is there a way we can use volumes or emptydir in KFP python without generating these output parameters?

### Environment:
KFP 1.0 on OCP 4.4

**Comment by Ark-kun** [comment]
I think this is a know upstream issue: https://github.com/argoproj/argo/issues/2679

>We must use the "k8sapi" executor since docker is not present.

The pns executor might be the more future-proof way.

As a workaround: All VolumeOp does is just pass the volume YAML to Argo and argo just calls `kubectl create` using that YAML. So, you could just create a custom component that uses `kubectl create` to create a volume. This way you control the outputs.

**Comment by nakfour** [comment]
@Ark-kun we documented why we are not using the pns executer here: https://github.com/opendatahub-io/odh-manifests/issues/117 
The issue is with the DSL generated volume yaml that includes these lines as mentioned before 
```
outputs:
      parameters:
      - name: create-pvc-manifest
        valueFrom: {jsonPath: '{}'}
      - name: create-pvc-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: create-pvc-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
```
These lines are not generated by Argo, they are generated by the python DSL SDK when creating a volume. Is there a way to create a volume in python without any outputs that require EmptyDir?
