### ISSUE TITLE
Unable to run GPU tensorflow image on machine without GPU

### ISSUE THREAD

**Issue by soogui** [kubeflow/pipelines#4339]
### What steps did you take:
I am trying to run a toy pipeline using `tensorflow/tensorflow:latest-gpu-py3` as base image. I have a basic example that loads tensorflow to run a simple computation. Here is my `pipeline.yaml`:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tensorflow-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-08-06T18:53:38.792518',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A toy pipeline to check
      ability to load tensorflow.", "name": "TensorFLow Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: tensorflow-pipeline
  templates:
  - name: load-tf
    container:
      args: []
      command:
      - python3
      - -u
      - -c
      - |
        def load_tf():
            import tensorflow as tf
            print(tf.reduce_sum(tf.random.normal([1000, 1000])))

        import argparse
        _parser = argparse.ArgumentParser(prog='Load tf', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = load_tf(**_parsed_args)
      image: tensorflow/tensorflow:latest-gpu-py3
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["python3", "-u", "-c", "def load_tf():\n    import
          tensorflow as tf\n    print(tf.reduce_sum(tf.random.normal([1000, 1000])))\n\nimport
          argparse\n_parser = argparse.ArgumentParser(prog=''Load tf'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = load_tf(**_parsed_args)\n"],
          "image": "tensorflow/tensorflow:latest-gpu-py3"}}, "name": "Load tf"}',
        pipelines.kubeflow.org/component_ref: '{}'}
  - name: tensorflow-pipeline
    dag:
      tasks:
      - {name: load-tf, template: load-tf}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner

``` 

### What happened:

The pipeline run failed with the following events in the corresponding pod:
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  12m   default-scheduler  Successfully assigned kubeflow/tensorflow-pipeline-qmnw6-3256484862 to minikube
  Normal   Pulled     12m   kubelet, minikube  Container image "gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21" already present on machine
  Normal   Created    12m   kubelet, minikube  Created container startup-lock-init-container
  Normal   Started    12m   kubelet, minikube  Started container startup-lock-init-container
  Normal   Pulled     12m   kubelet, minikube  Container image "argoproj/argoexec:v2.3.0" already present on machine
  Normal   Created    12m   kubelet, minikube  Created container wait
  Normal   Started    12m   kubelet, minikube  Started container wait
  Normal   Pulling    12m   kubelet, minikube  Pulling image "tensorflow/tensorflow:latest-gpu-py3"
  Normal   Pulled     28s   kubelet, minikube  Successfully pulled image "tensorflow/tensorflow:latest-gpu-py3"
  Normal   Created    27s   kubelet, minikube  Created container main
  Warning  Failed     26s   kubelet, minikube  Error: failed to start container "main": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
```

### What did you expect to happen:
Since TensorFlow supports soft device placement, I assume this pipeline should still execute on a device without GPU, as can be confirmed with this command on my local machine (no GPU):
`docker run -it --rm tensorflow/tensorflow:latest-gpu-py3 python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`
Output:
```
2020-08-07 15:28:17.064351: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-08-07 15:28:17.078512: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-08-07 15:28:18.070552: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-07 15:28:18.070579: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (-1)
2020-08-07 15:28:18.070601: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d7f6808b6c97): /proc/driver/nvidia/version does not exist
2020-08-07 15:28:18.071155: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-07 15:28:18.080373: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz
2020-08-07 15:28:18.080954: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5842170 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-07 15:28:18.080981: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
tf.Tensor(-1008.3187, shape=(), dtype=float32)
```

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
MiniKF box version: arrikto/minikf

KFP version: build version v1.0-56-g5ae311f8

KFP SDK version: Version: 1.0.0

### Anything else you would like to add:
Switching to CPU base image would solve the issue. However, I am interested in using the same `gpu` tagged `tensorflow` images in my pipelines, since I want to be able to share them across any machine, whether it has or not GPU.

/kind bug
