### ISSUE TITLE
Create componnet with metadata and metrics

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4379]
Hi team, 

I am trying to create reusable components with UI metadata and metrics persisted. It seems that I need to explicit about outputting metadata and metrics in the `component.yaml` file. For example, [confusion_metric](https://github.com/kubeflow/pipelines/blob/master/components/local/confusion_matrix/component.yaml)

```yaml
name: Confusion matrix
description: Calculates confusion matrix
inputs:
  - {name: Predictions,     type: GCSPath,        description: 'GCS path of prediction file pattern.'} # type: {GCSPath: {data_type: CSV}}
  - {name: Target lambda,   type: String, default: '', description: 'Text of Python lambda function which computes target value. For example, "lambda x: x[''a''] + x[''b'']". If not set, the input must include a "target" column.'}
  - {name: Output dir,      type: GCSPath,  description: 'GCS path of the output directory.'} # type: {GCSPath: {path_type: Directory}}
outputs:
  - {name: MLPipeline UI metadata, type: UI metadata}
  - {name: MLPipeline Metrics,     type: Metrics}
implementation:
  container:
    image: gcr.io/ml-pipeline/ml-pipeline-local-confusion-matrix:1.0.0
    command: [python2, /ml/confusion_matrix.py]
    args: [
      --predictions, {inputValue: Predictions},
      --target_lambda, {inputValue: Target lambda},
      --output,      {inputValue: Output dir},
    ]
    fileOutputs:
      MLPipeline UI metadata: /mlpipeline-ui-metadata.json
      MLPipeline Metrics:     /mlpipeline-metrics.json
```

However, in the [component specification](https://github.com/kubeflow/pipelines/blob/master/components/local/confusion_matrix/component.yaml). It mentions that `fileOutputs` is a `Legacy property` and should not be used. 

They are contradicting each other. Also, I could not find any documentation saying we need to use `fileOutputs` in the `component.yaml` file to persist UI metadata and metrics.

So I wonder what is the correct way to output UI metadata and metrics?

Thanks
Bin
