### ISSUE TITLE
Running compiled workflow on Argo produces error: "failed to save outputs: timed out waiting for the condition"

### ISSUE THREAD

**Issue by ksonbol** [kubeflow/pipelines#4387]
### What steps did you take:
Compile a simple pipeline with one step generating output (from a local file) and another using that as input:
```
import kfp
from kfp import dsl

@dsl.pipeline(
    name="my pipeline",
    description="This is my pipeline")
def pipeline():
    generator_op = dsl.ContainerOp(
        name='Generator',
        image='alpine:latest',
        command=["touch"],
        arguments=[
            "/output.txt",
        ],
        file_outputs={"output": "/output.txt"}
    )
    consumer_op = dsl.ContainerOp(
        name='Consumer',
        image='alpine:latest',
        command=["echo"],
        arguments=[
            generator_op.output
        ]    
    )
```
### What happened:
I get the following YAML file which specifies both an output parameter and an ouptut artifact for the first task. Why does this happen?
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-08-18T19:23:55.564718',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "This is my pipeline",
      "name": "my pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: my-pipeline
  templates:
  - name: consumer
    container:
      args: ['{{inputs.parameters.generator-output}}']
      command: [echo]
      image: alpine:latest
    inputs:
      parameters:
      - {name: generator-output}
  - name: generator
    container:
      args: [/output.txt]
      command: [touch]
      image: alpine:latest
    outputs:
      parameters:
      - name: generator-output
        valueFrom: {path: /output.txt}
      artifacts:
      - {name: generator-output, path: /output.txt}
  - name: my-pipeline
    dag:
      tasks:
      - name: consumer
        template: consumer
        dependencies: [generator]
        arguments:
          parameters:
          - {name: generator-output, value: '{{tasks.generator.outputs.parameters.generator-output}}'}
      - {name: generator, template: generator}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
```

Running the compiled YAML file using the Kubeflow UI works fine. However, running the same workflow using 

`argo submit pipeline.yaml` 

on the same cluster fails with the error:

`failed to save outputs: timed out waiting for the condition`

### What did you expect to happen:
- The pipeline to run successfully using either KFP or argo workflows. I expected the generated YAML file to be directly compatible with Argo Workflows (except for the serviceAccountName line which I removed before submitting to Argo).
- Having only output parameters in the generated YAML file since the output artifact is not used.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

On-premisis.

KFP version: 
0.5.1

KFP SDK version: 
0.5.1 and 1.0.0 produce the same compiled file.

Argo version
2.8.1

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
To illustrate the use case, I am using the KFP SDK to generate Argo workflow files that I can use with an argo. I expected the compiled files to be runnable on any argo-enabled cluster.
/kind bug
