### ISSUE TITLE
Unable to parameterize image/tag in component spec

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#4433]
### What steps did you take:

Attempted to write a `component.yaml` using (only relevant sections shown):

```yaml
inputs:
- {name: Tag, default: latest}
implementation:
  container:
    image: {concat: ['my_image_name:', {inputValue: Tag}]}
```

### What happened:
Compilation error:

```
Error: Structure "OrderedDict([('concat', ['my_image_name:', OrderedDict([('inputValue', 'Tag')])])])" is incompatible with type "<class 'str'>". Structure is not the instance of the type, the type does not have .from_dict method and is not generic.
```

### What did you expect to happen:
Pipeline to compile.

KFP version: 
Build commit: 9c16e12

KFP SDK version: 
kfp                            1.0.0
kfp-server-api                 1.0.0

### Anything else you would like to add:
This can be done in a more explicit fashion using `ContainerOp`, but in my newer pipelines I'm attempting to use components wherever possible.

/kind bug
