### ISSUE TITLE
Components - Add type-checking support for union types for inputs

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4518]
ComponentSpec allows arbitrary complex types. Component library performs type checking when passing outputs to inputs.

We need a way to describe inputs that support more than one type. The type checker should check that the output reference matches at least one of the types in the union.

Proposed `component.yaml` syntax (no changes to ComponentSpec format):

Option 1:
```yaml
inputs:
- name: Model
  type: {Union: {types: [XGBoostModel, TensorflowModel]}}
```
Option 2:
```yaml
inputs:
- name: Model
  type: {Union: [XGBoostModel, TensorflowModel]}
```
