### ISSUE TITLE
Add component metadata to the generated Argo YAML for consumption by the UI

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#452]
I propose passing the Component metadata and interface specs inside Argo template annotation.
This way the UX can get access to descriptions, human-readable input names and types (for validation) 

```
  templates:
  - name: train-op
    metadata:
      annotations:
        component-source:
          name: xgboost4j - Train classifier
          description: Trains a classification boosted tree model using xgboost4j
          inputs:
          - {name: Training data, type: TSV, argoName: training-data}
          - {name: Rounds, type: Integer, default: 30, help: Number of training rounds, argoName: rounds}
          outputs:
          - {name: Trained model, type: XGBoostModel, help: Trained XGBoost model, argoName: trained-model}
    inputs:
      parameters:
      - name: training-data
      - name: rounds
    outputs:
      parameters:
      - trained-model
    container: ...
```
