### ISSUE TITLE
Empty default pipeline arguments are getting ignored by the compiler

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4549]
This leads to failure at Argo workflow submission time if the arguments are not provided.

```python
import kfp

from kfp.components import create_component_from_func

@create_component_from_func
def my_op():
    pass

def my_pipeline(some_param=''):
    my_op()

kfp.compiler.Compiler().compile(my_pipeline, 'pipeline.yaml')
```

```yaml
  arguments:
    parameters:
    - {name: some_param}
```
