### ISSUE TITLE
[Cache Deployer] Discussion - use cert-manager instead?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4695]
I've been looking at how other applications in Kubeflow managed the certificate issue.

I found notebooks is doing the following:
https://github.com/kubeflow/kubeflow/blob/e3cc4eea73a43ed13705b9f0a43a81116f620ffd/components/notebook-controller/config/default/webhookcainjection_patch.yaml
https://github.com/kubeflow/kubeflow/tree/e3cc4eea73a43ed13705b9f0a43a81116f620ffd/components/notebook-controller/config/certmanager

They deploy some declarative custom resources supported by https://cert-manager.io/, so that the opeartor will handle the certificate issuing, signing, ... process.

This might be a good alternative to learn from, if we continue to have a cache webhook.
But maybe not an immediate need

/cc @Ark-kun

**Comment by Bobgy** [comment]
webhook setup is very standard in kubebuilder boilerplate, worth checking out what they do too: https://github.com/kubernetes-sigs/kubebuilder

**Comment by DavidSpek** [comment]
@Bobgy Is implementing this just a question of setting up a cert-manager issuer and requesting a certificate from there or would the cache server need to be modified as well? As https://github.com/kubeflow/pipelines/issues/4505 is the only issue I have to get my on-prem cluster fully functional, I'd like to have this implemented for Kubeflow 1.3 if possible.

**Comment by Bobgy** [comment]
@DavidSpek I am not familiar with cert-manager, but what you said sounds correct

**Comment by DavidSpek** [comment]
It seems https://github.com/kubeflow/manifests/blob/master/admission-webhook/bootstrap/base/config-map.yaml is doing something similar things to https://github.com/kubeflow/pipelines/blob/master/backend/src/cache/deployer/webhook-create-signed-cert.sh.

Simply creating a certificate, such as the ones linked above will not result in a correct certificate as it gives the error `open /etc/webhook/certs/cert.pem: no such file or directory`.

The certificate I created for reference:
```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cache-server.kubeflow
  namespace: kubeflow
  labels:
    app: cache-server
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    kustomize.component: kubeflow-pipelines
spec:
  commonName: cache-server.kubeflow.svc
  dnsNames:
  - cache-server
  - cache-server.kubeflow
  - cache-server.kubeflow.svc
  - cache-server.kubeflow.svc.cluster.local
  isCA: true
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-tls
EOF
```
