### ISSUE TITLE
AWS Kubeflow : Pipeline fail - No healthy upstream

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4730]
### What steps did you take:

I am following this documentation: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
Using this tutorial I successfully installed Kubeflow on EKS
After I installed I did:

```
kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
```

This starts kubeflow on local host `127.0.0.1:8080` . But when I try to upload a new `pipeline.tar.gz ` file I get error: 
```
pipeline version creation failed 
```

see below screen shot for reference

https://github.com/ajinkya933/Assignment_solution/blob/master/pipelines.png

yaml file used for deployment:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubeflow-cluster
  region: us-east-2
nodeGroups:
  - name: kubenodegroup
    labels: { role: workers }
    instanceType: t3.xlarge
    desiredCapacity: 1
    volumeSize: 80
```

### What happened:
pipeline version creation failed  error
### What did you expect to happen:
I expected the pipeline to execute normally

/kind bug
