### ISSUE TITLE
Can not mount volume in Container op

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/pipelines#477]
[Running Pipelines on **Minikube**]
I am trying to mount a folder from the Minikube VM into the containers of my pipeline.

I have a `data_processing` folder in the Minikube VM that I want to be accessible by the Pipelines containers:

```bash
$> minikube ssh ls /data_processing
data.csv
```

I created a PersistentVolume using:
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-processing
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data_processing
```

I tried to test the mount in a Pipelines Lightweight component:
```python
def data_loader():
    import pandas as pd
    data = pd.read_csv('/data_processing/data.csv', sep=',',header=None)
    print(data)

data_loading_op = comp.func_to_container_op(data_loader, base_image='tensorflow/tensorflow:1.11.0-py3')

import kfp.dsl as dsl
@dsl.pipeline(
   name='DataLoading Pipeline',
   description='Test.'
)
def phenology_pipeline():
    data_loading_task = data_loading_op(data_path).add_volume(k8s_client.V1VolumeMount(
          mount_path='/data_processing',
          name='data-processing'))

# ...
```

But the folder can not be found. Any ideas on how to solve this?
