### ISSUE TITLE
SDK - Components - Support passing a list of values as an argument for a single component input

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4801]
This feature is non-trivial and solves a fundamental problem that KFP graph components have.

The interface of KFP components is static. Each component has a fixed number of inputs.
A KFP task (`TaskSpec`) has the `arguments` map that maps each component input to a single argument (either constant or an upstream reference).

This makes it impossible to pass multiple arguments to a single input. This makes it impossible to create components that, for example, build a JSON object from a variable number of arguments. Or selects the maximum number from a variable number of arguments.

The described scenario is possible with Argo and ContainerOp is a limited way (since they support text-based placeholders), but not with graph components which use structural placeholders.

Proposed `TaskSpec` syntax:

```yaml
componentRef: ...
arguments:
  normal_arg1: "Hello"
  normal_arg2: {taskOutput: {taskId: upstream1, outputName: output1}}

  # Variant 1:
  list_arg: {JsonArray: ["Hello", {taskOutput: {taskId: upstream1, outputName: output1}}, {taskOutput: {taskId: upstream2, outputName: output2}}]}

  # Variant 2:
  list_arg: ["Hello", {taskOutput: {taskId: upstream1, outputName: output1}}, {taskOutput: {taskId: upstream2, outputName: output2}}]
```

We might need to modify the type checker to explicitly recognize list types and type check argument lists.

Component-side behavior proposals:

Option 1: JSON-serialized list

The component does not have any special options. The component code receives a JSON-serialized list containing the textual representation of the argument values. The component implementation can use the `inputValue` and `inputPath` palceholders as usual.

Pros:
* Easy to implement for the 80% case

Cons:
* Does not work for binary data containing `\x00`.
* Harder to implement to properly handle arbitrary values that might contain arbitrary characters that might break JSON

Option 2: Variable-length arguments

Similar to Python's `*args`.
The component interface should annotate the input to tell the system that it's variable-length. For implementation there are two options:
Option 2a (preferred): No new placeholders. `{inputValue: name}` resolves to a list of command-line arguments. `{inputPath: name}` resolves to a list of command-line arguments (paths).

Option 2b: Special placeholder to loop through the arguments. Pretty hard to design cleanly.

P.S. There can be a similar possible feature which mimics Python's `**kwargs`.
