### ISSUE TITLE
SDK - Components - Support constructing and passing JSON structures to components.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4802]
Related to https://github.com/kubeflow/pipelines/issues/4801 and relies on it.
Fixes https://github.com/kubeflow/pipelines/issues/4776

This is a high-level feature.

The user must be able to construct a valid JSON structure where the values can come from component outputs.

In KFP this is possible in some cases, but is not fully supported.

* Simple solutions like `my_op(in={"param1": task1.output, "param2": task2.output})` can lead to invalid JSON
* Graph components cannot support such pipelines due to static number of inputs. See https://github.com/kubeflow/pipelines/issues/4801

Proposed solution:
* Implement https://github.com/kubeflow/pipelines/issues/4801
* Create a component that creates a JSON object from a JSON template and a list of arguments
* The SDK should insert this component when a dict is passed to a component as an argument to ensure that a valid JSON file is constructed

Example of a JSON component task spec:

```yaml
componentRef:
  name: "builtin:construct_json"
arguments:
  json_template: |
    '{
        "param1": "{{placeholder: {index: 0, type: int} }}",
        "param2": "{{placeholder: {index: 1, type: str} }}",
     }'
  replacements: [{taskOutput: {...}}, {taskOutput: {...}}]
```
