### ISSUE TITLE
SDK - Components - Type inheritance

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4803]
Related to https://github.com/kubeflow/pipelines/issues/4794

Possible syntax:
```yaml
inputs:
- {name: gcs_uri, type: {GcsUri: {base_type: {Uri: {base_type: String}}}}}
# or
- {name: gcs_uri, type: {GcsUri: {base_types: [Uri, String]}}}
outputs:
- {name: gcs_uri, type: {GcsUri: {base_type: {Uri: {base_type: String}}}}}
# or
- {name: gcs_uri, type: {GcsUri: {base_types: [Uri, String]}}}
```

---
P.S. 
Actually, the type inheritance does not make sense for inputs. According to the Liskov substitution principle, the input can only accept and argument of the most derived type.

The only way to specify that the input can accept multiple types is the (proposed) `Union` type syntax: https://github.com/kubeflow/pipelines/issues/4518
```yaml
inputs:
- {name: gcs_uri, type: {Union: [GcsUri, Uri, String]}}
```
