### ISSUE TITLE
[SDK] Support `dnsConfig` field

### ISSUE THREAD

**Issue by ohke** [kubeflow/pipelines#4836]
Is there any way to set up `dnsConfig` using the SDK?

To avoid [DNS failure due to the default `ndots: 5`](https://github.com/kubernetes/dns/issues/159#issuecomment-336449931), I have added the following directly to the compiled YAML file.
(Argo has supported dnsConfig since [2.3.0](https://github.com/argoproj/argo/releases/tag/v2.3.0).)
```yaml
  dnsConfig:
    options:
    - {name: ndots, value: '1'}
```
