### ISSUE TITLE
Unresolved PipelineParam when static list passed to dsl.ParallelFor contains pipelineParam

### ISSUE THREAD

**Issue by radcheb** [kubeflow/pipelines#4890]
### What steps did you take:
When a dsl.ParallelFor is created with static list containing a pipeline param, the compiler fails with error message: `RuntimeError: Internal compiler error: Found unresolved PipelineParam.`

### What happened:

You can reproduce with the following code:
```python
from kfp import dsl, components, compiler
def print_op(s: str):
    print(f"a is {s}")
    
PRINT_OP = components.func_to_container_op(print_op, base_image="python:3.7")

@dsl.pipeline(name="test pipeline")
def my_pipeline(name: str):
    
    texts = [{"val":"toot"}, {"val": str(name)}]
    
    with dsl.ParallelFor(texts) as text:
        PRINT_OP(s=text.val)

compiler_instance = compiler.Compiler()
compiler_instance.compile(pipeline_func=my_pipeline, package_path="my_pipeline.yaml")
```
Here is the error:
![image](https://user-images.githubusercontent.com/5963615/101994778-52c81400-3cc5-11eb-82de-018811d4eab2.png)

### What did you expect to happen:
I expect it to compile.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow deployed on EKS

KFP version: `1.0.4`

KFP SDK version: `1.0.4`

### Anything else you would like to add:
I analysed YAML and it seems the pipeline param is not resolved inside YAML.

/kind bug
/area sdk

**Comment by radcheb** [comment]
Actually when I comment the ` _validate_workflow(workflow)` line in compiler, I get this YAML:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2, pipelines.kubeflow.org/pipeline_compilation_time: '2020-12-12T22:10:40.304274',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "name", "type": "String"}],
      "name": "test pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2}
spec:
  entrypoint: test-pipeline
  templates:
  - name: for-loop-for-loop-28d0eb78-1
    inputs:
      parameters:
      - {name: loop-item-param-28d0eb78-subvar-val}
      - {name: name}
    dag:
      tasks:
      - name: print-op
        template: print-op
        arguments:
          parameters:
          - {name: loop-item-param-28d0eb78-subvar-val, value: '{{inputs.parameters.loop-item-param-28d0eb78-subvar-val}}'}
          - {name: name, value: '{{inputs.parameters.name}}'}
  - name: print-op
    container:
      args: [--s, '{{inputs.parameters.loop-item-param-28d0eb78-subvar-val}}', --a,
        '{{inputs.parameters.name}}']
      command:
      - python3
      - -u
      - -c
      - |
        def print_op(s, a):
            print(f"a is {s}")

        import argparse
        _parser = argparse.ArgumentParser(prog='Print op', description='')
        _parser.add_argument("--s", dest="s", type=str, required=True, default=argparse.SUPPRESS)
        _parser.add_argument("--a", dest="a", type=str, required=True, default=argparse.SUPPRESS)
        _parsed_args = vars(_parser.parse_args())

        _outputs = print_op(**_parsed_args)
      image: python:3.7
    inputs:
      parameters:
      - {name: loop-item-param-28d0eb78-subvar-val}
      - {name: name}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--s", {"inputValue": "s"}, "--a", {"inputValue": "a"}], "command":
          ["python3", "-u", "-c", "def print_op(s, a):\n    print(f\"a is {s}\")\n\nimport
          argparse\n_parser = argparse.ArgumentParser(prog=''Print op'', description='''')\n_parser.add_argument(\"--s\",
          dest=\"s\", type=str, required=True, default=argparse.SUPPRESS)\n_parser.add_argument(\"--a\",
          dest=\"a\", type=str, required=True, default=argparse.SUPPRESS)\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = print_op(**_parsed_args)\n"],
          "image": "python:3.7"}}, "inputs": [{"name": "s", "type": "String"}, {"name":
          "a", "type": "String"}], "name": "Print op"}', pipelines.kubeflow.org/component_ref: '{}',
        pipelines.kubeflow.org/arguments.parameters: '{"a": "{{inputs.parameters.name}}",
          "s": "{{inputs.parameters.loop-item-param-28d0eb78-subvar-val}}"}'}
  - name: test-pipeline
    inputs:
      parameters:
      - {name: name}
    dag:
      tasks:
      - name: for-loop-for-loop-28d0eb78-1
        template: for-loop-for-loop-28d0eb78-1
        arguments:
          parameters:
          - {name: loop-item-param-28d0eb78-subvar-val, value: '{{item.val}}'}
          - {name: name, value: '{{inputs.parameters.name}}'}
        withItems:
        - {val: toot, key: keey}
        - {val: '{{pipelineparam:op=;name=name}}', key: str(name)}
  arguments:
    parameters:
    - {name: name}
  serviceAccountName: pipeline-runner
```

So the problem comes from the `withItems` containing unresolved pipelineparam:
```yaml
        withItems:
        - {val: toot, key: keey}
        - {val: '{{pipelineparam:op=;name=name}}', key: str(name)}
```
