### ISSUE TITLE
gcp-credentials volumes are added to workflow multiple times

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#494]
From our Kubeflow sample:
```
  volumes:
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
```
