### ISSUE TITLE
Cannot deploy Kubefow 1.2.0 in CLI mode: it is impossible to deploy in a custom VPC

### ISSUE THREAD

**Issue by krish0005** [kubeflow/pipelines#5213]
See comments already posted here: https://github.com/kubeflow/manifests/issues/1577#issuecomment-777587661

My cluster.yaml as follows:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: aip-kubeflow-mgmt # {"$kpt-set":"name"}
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
spec:
  location: europe-west1-b # {"$kpt-set":"location"}
  initialNodeCount: 3
  workloadIdentityConfig:
    identityNamespace: acn-cpaascgp.svc.id.goog # {"$kpt-set":"wi-pool"}
  releaseChannel:
    channel: REGULAR
  networkRef:
    external: https://www.googleapis.com/compute/v1/projects/myproject/global/networks/myproject-dev
  subnetworkRef:
    external: https://www.googleapis.com/compute/v1/projects/myproject/regions/europe-west1-b/myproject/public
```

What i get when i build:

```
make apply-cluster

make -f ./upstream/management/Makefile hydrate-cluster
make[1]: Entering directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
The management cluster name "myproject-mgmt" is valid.
# Delete the directory so any resources that have been removed
# from the manifests will be pruned
rm -rf build/cluster
mkdir -p build/cluster
kustomize build ./instance/cluster -o build/cluster
make[1]: Leaving directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
make -f ./upstream/management/Makefile apply-cluster
make[1]: Entering directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
# Create the cluster
anthoscli apply -f build/cluster
I0211 15:34:40.932055   15959 main.go:230] reconcile serviceusage.cnrm.cloud.google.com/Service container.googleapis.com
I0211 15:34:42.070023   15959 main.go:230] reconcile container.cnrm.cloud.google.com/ContainerCluster myproject-mgmt
Unexpected error: error reconciling objects: error reconciling ContainerCluster:mygcpproject/myproject-mgmt: error creating GKE cluster myproject-mgmt: googleapi: Error 400: Project "mygcpproject" has no network named "default".
make[1]: *** [apply-cluster] Error 1
make[1]: Leaving directory `/home/myproject-dev/kubeflow/myproject-gcp-dex-mgmt_cluster/management'
make: *** [apply-cluster] Error 2
```
