### ISSUE TITLE
Cache Webhook "disabled" by default in Azure

### ISSUE THREAD

**Issue by allenc97** [kubeflow/pipelines#5244]
### What happened:
[A clear and concise description of what the bug is.]
Right now, mutating webhooks are used for components such as the cache-server. Previously there was an issue with the knative webhook, so the label "control-plane" was attached to prevent the webhook from triggering all the time. (Refer to https://github.com/kubeflow/kubeflow/issues/4511).  However, Azure by default adds the below namespace selector to mutatingwebhooks to prevent applying to AKS internal namespaces. (https://github.com/Azure/AKS/issues/1771)
```
namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
```
As the KF namespace comes with "control-plane: kubeflow", this causes the cache server to fail to mutate any pods in Kubeflow.  

### What did you expect to happen:
It seems unfair to expect Kubeflow to fix this issue, as this dependency is inherently caused by Azure upstream. Perhaps we can update the Azure docs / default deploy to tell the users that these components won't work as intended? 
### Environment:

Azure

How did you deploy Kubeflow Pipelines (KFP)?

KFP version:  1.2

KFP SDK version:  1.4

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by allenc97** [comment]
@dtzar @eedorenko @sudivate

**Comment by andre-lx** [comment]
In azure, the problem is that istio pods are not being injected to the pods in kubeflow. 

Azure enforces that the `MutatingWebhookConfiguration - istio-sidecar-injector` in kubeflow is being automatically edited by AKS to add the following match expression in the namespaceSelector:

```
matchExpressions:
- key: control-plane
  operator: DoesNotExist
```

So the MutatingWebhookConfiguration looks like this:

```
namespaceSelector:
	matchExpressions:
    - key: control-plane
      operator: DoesNotExist
	matchLabels:
  		istio-injection: enabled
```

This will exclude the kubeflow namespace, since the namespace have the label:

```
labels:
    control-plane: kubeflow
```

To solve this issue, you need to deactivate the admission enforcer from aks, using the following annotation in the MutatingWebhookConfiguration:

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    admissions.enforcer/disabled: "true"
  name: istio-sidecar-injector
```

I believe, that the following issues are all related to this, so you don't need to disable istio (changing the DestinationRules from ISTIO_MUTUAL to DISABLE):

https://github.com/kubeflow/pipelines/issues/4469
https://github.com/kubeflow/kubeflow/issues/5271
https://github.com/kubeflow/kubeflow/issues/5277
https://github.com/Azure/AKS/issues/1771

+info:
https://docs.microsoft.com/en-us/azure/aks/faq#can-i-use-admission-controller-webhooks-on-aks

**Comment by allenc97** [comment]
Yes, the point of my issue was suggesting we can go around it by adding `admissions.enforcer/disabled: "true"`, preferably in the azure overlays.

**Comment by danishsamad** [comment]
@andre-lx I updated the istio-sidecar-injector MutatingWebhookConfiguration by adding the annotation as you described but istio sidecars were not injected with the pipeline components. I tried deleting the pods, restarting the deployments and even deleted and applied the pipeline component. Adding a label instead of an annotation also seemed to have no effect.

Then I edited the istio-sidecar-injector and removed the matchExpression added by AKS in the namespaceSelector and that solved the issue.

Did you recommend to add the annotation / label in the  istio-sidecar-injector MutatingWebhookConfiguration only or is there more to it?

**Comment by andre-lx** [comment]
Hi @danishsamad. Not sure, actually. 

In my case, deleting the match expression in my case didn't solve the issue, since AKS automatically add that match expression. 

I'm not sure if I did the manual delete or if the annotation deleted it.

Maybe I added the annotation and eliminated the match expression manually.

Anyway, in new clusters, the annotation worked as expected -> the match expression is not added and the istio pods are injected to the pipelines pods.

**Comment by DavidSpek** [comment]
@andre-lx Thanks for the fix. I'll be looking at adding this to the Istio installation used by [ArgoFlow-Azure](https://github.com/argoflow/argoflow-azure), which is still in the very early stages but will hopefully have more integrations with Azure soon. Any help to add Azure integrations to this deployment are greatly appreciated.

**Comment by TobiasGoerke** [comment]
I just ran into the same problem installing manifests 1.3.1 using kustomize.
Adding the label `admissions.enforcer/disabled: "true"` at runtime (even after restrting all cluster pods) did not work for me.
Adding the annotation before the installation, however, **did work** (i.e. modfying or overlaying the MutatingWebhookConfiguration in common/istio-1-9/istio-install/base/install.yaml). No other modifications needed.
Thanks!

**Comment by Roman-Ka** [comment]
Hi, k8s newbie here, do you mind providing more details on how to solve this issue @TobiasGoerke ?

**Comment by TobiasGoerke** [comment]
Hello @Roman-Ka, there's a file in your manifests folder at `common/istio-1-9/istio-install/base/install.yaml` that you will somehow need to modify. The easiest (but least maintainable way) is to just edit the file directly. 
There a resource hidden in there that looks like this:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    app: sidecar-injector
    release: istio
  ....
```

Here you will need to add the annotation so that it looks like this:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  annotations: 
    admissions.enforcer/disabled: "true"
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    app: sidecar-injector
    release: istio
  ....
```

Then install Kubeflow using that folder and you should be good.

Hope that helps!
