### ISSUE TITLE
dsl ResourceOp with parameterized manifest is throwing validation error

### ISSUE THREAD

**Issue by deepk2u** [kubeflow/pipelines#5247]
### What steps did you take:
I am trying to pass the output of one step to resourceOp instead of the actual manifest

```
c_op = dsl.ContainerOp(
          name='patch',
          image='docker.intuit.com/data-mlplatform/mlp-components/service/patch',
          command=['python3','mlp/components/patch.py'],
          arguments=[ "--manifest", manifest,
                      "--patch", patch],
          file_outputs={'train': '/output.txt'}
      )
  
  #create training job
  op = dsl.ResourceOp(
        name="train",
        action="create",
        k8s_resource=c_op.outputs['train'],
        success_condition="status.trainingJobStatus==Completed,status.secondaryStatus==Completed",
        failure_condition="status.trainingJobStatus==Failed,status.secondaryStatus==Failed",
        attribute_outputs={
            "job-name": "{.status.sageMakerTrainingJobName}",
            "model-path": "{.status.modelPath}",
            "cloud-watch-url": "{.status.cloudWatchLogUrl}"
        })
```

### What happened:
it throws following error during workflow validation

`Error: time="2021-03-04T22:09:12-08:00" level=fatal msg="/dev/stdin: templates.test-pipeline.tasks.train templates.train.resource.manifest must be a valid yaml"`

After checking the workflow manifest, manifest value is separated by | (see below) which is the actual reason behind the issue, workflow writer should not have appended this | in case if the manifest is parameterized.

```
 - name: train
    resource:
      action: create
      successCondition: status.trainingJobStatus==Completed,status.secondaryStatus==Completed
      failureCondition: status.trainingJobStatus==Failed,status.secondaryStatus==Failed
      manifest: |
        '{{inputs.parameters.patch-train}}'
    inputs:
      parameters:
      - {name: patch-train}
    outputs:
      parameters:
      - name: train-cloud-watch-url
        valueFrom: {jsonPath: '{.status.cloudWatchLogUrl}'}
      - name: train-job-name
        valueFrom: {jsonPath: '{.status.sageMakerTrainingJobName}'}
      - name: train-manifest
        valueFrom: {jsonPath: '{}'}
      - name: train-model-path
        valueFrom: {jsonPath: '{.status.modelPath}'}
      - name: train-name
        valueFrom: {jsonPath: '{.metadata.name}'}
  ```
### What did you expect to happen:
The compiler should write the value of manifest as `manifest: '{{inputs.parameters.patch-train}}'` in case if manifest value is parameterized. 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
local

KFP version: 1.4.0

KFP SDK version: 1.4.0

### Anything else you would like to add:
When I fixed the workflow manually by removing | and ran the `argo lint` command which workflow validator does, it passes

/kind bug

pipeline.yaml
```
import os

from kfp import dsl, components
from training_component import mlp_train_op
    
training_manifest = """
    apiVersion: sagemaker.aws.amazon.com/v1
    kind: TrainingJob
    metadata:
    name: xgboost-mnist
    spec:
    roleArn: SAGEMAKER_EXECUTION_ROLE_ARN  
    region: us-east-1
    algorithmSpecification:
        trainingImage: 811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest
        trainingInputMode: File
    outputDataConfig:
        s3OutputPath: s3://BUCKET_NAME/xgboost-mnist/models/
    inputDataConfig:
        - channelName: train
        dataSource:
            s3DataSource:
            s3DataType: S3Prefix
            s3Uri: s3://BUCKET_NAME/xgboost-mnist/train/
            s3DataDistributionType: FullyReplicated
        contentType: text/csv
        compressionType: None
        - channelName: validation
        dataSource:
            s3DataSource:
            s3DataType: S3Prefix
            s3Uri: s3://BUCKET_NAME/xgboost-mnist/validation/
            s3DataDistributionType: FullyReplicated
        contentType: text/csv
        compressionType: None
    resourceConfig:
        instanceCount: 1
        instanceType: ml.m4.xlarge
        volumeSizeInGB: 5
    hyperParameters:
        - name: max_depth
        value: "5"
        - name: eta
        value: "0.2"
        - name: gamma
        value: "4"
        - name: min_child_weight
        value: "6"
        - name: silent
        value: "0"
        - name: objective
        value: multi:softmax
        - name: num_class
        value: "10"
        - name: num_round
        value: "10"
    stoppingCondition:
        maxRuntimeInSeconds: 86400
"""

@dsl.pipeline(
    name="Test Pipeline",
    description="Kubeflow test pipeline")
def pipeline():
    train = mlp_train_op(manifest=training_manifest, patch='')

if __name__ == "__main__":
    kfp.compiler.Compiler().compile(pipeline, __file__ + ".zip")

```

training_component.yaml

```
import logging
import os
import argparse
from kfp import dsl, components
import yaml

def mlp_train_op(manifest, patch):
  
  c_op = dsl.ContainerOp(
          name='patch',
          image='docker.intuit.com/data-mlplatform/mlp-components/service/patch',
          command=['python3','mlp/components/patch.py'],
          arguments=[ "--manifest", manifest,
                      "--patch", patch],
          file_outputs={'train': '/output.txt'}
      )
  
  #create training job
  op = dsl.ResourceOp(
        name="train",
        action="create",
        k8s_resource=c_op.outputs['train'],
        success_condition="status.trainingJobStatus==Completed,status.secondaryStatus==Completed",
        failure_condition="status.trainingJobStatus==Failed,status.secondaryStatus==Failed",
        attribute_outputs={
            "job-name": "{.status.sageMakerTrainingJobName}",
            "model-path": "{.status.modelPath}",
            "cloud-watch-url": "{.status.cloudWatchLogUrl}"
        })
  return op
  
  ```
