### ISSUE TITLE
Feature gap between `ContainerOp` and YAML component: hydra argument support

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#5281]
Using `ContainerOp` to define component, users can use [hydra](https://hydra.cc/) arguments like shown below.
```
import kfp.dsl as dsl
import kfp.gcp as gcp
import kfp.compiler as compiler
....
        transform = dsl.ContainerOp(
            name="transform",
            image="gcr.io/{}/image:latest".format(PROJECT),
            arguments=[
                "component={}/transformer".format(TEMPLATE_PRJ),
                "common={}".format(ENV),
                "common.template_prj={}".format(TEMPLATE_PRJ),
                "common.project_api_key={}".format(project_api_key),
                "common.data_api_key={}".format(data_api_key),
                "common.model_id={}".format(model_id),
            ],
        )
```

However, this is not easily achievable via YAML component. The following code results compile error when loading the component YAML.
```
name: TransformOp
inputs:
- {name: project_api_key, type: String}
- {name: data_api_key, type: String}
- {name: model_id, type: String}
implementation:
  container:
    image: gcr.io/%s/kubeflow-projects/causal_discovery
    args:
    - component=%s/transformer
    - common=%s
    - common.template_prj=%s
    - common.project_api_key={inputValue: project_api_key}
    - common.data_api_key={inputValue: data_api_key}
    - common.model_id={inputValue: model_id}
```
This is because when we load and parse the YAML, `common.project_api_key={inputValue` is taken as a key of a dictionary, while `project_api_key}` is taken as the the value for the key, which is apparently wrong. 
So we have a limitation here that a placeholder like `{inputValue: project_api_key}` must be on its own line (the list item).

/kind feature
/area sdk

**Comment by Ark-kun** [comment]
Are you sure that hydra does not support the normal way of specifying command-line arguments that 99% of other command-line tools use (separating flag and value, instead of joining them with `=`)?

In any case, the `ComponentSpec`/`component.yaml` format supports such command lines via the `concat`: placeholders:

```yaml
name: TransformOp
inputs:
- {name: template_prj, type: String}
- {name: template_prj, type: String}
- {name: env, type: String}
- {name: data_api_key, type: String}
- {name: model_id, type: String}
implementation:
  container:
    image: gcr.io/my-org/kubeflow-projects/causal_discovery
    args:
    - concat: ["component=", {inputValue: template_prj}, "/transformer"]
    - concat: ["common=", {inputValue: env}]
    - concat: ["common.template_prj=", {inputValue: template_prj}]
    - concat: ["common.project_api_key=", {inputValue: project_api_key}]
    - concat: ["common.data_api_key=", {inputValue: data_api_key}]
    - concat: ["common.model_id=", {inputValue: model_id}]
```

>This is because when we load and parse the YAML, common.project_api_key={inputValue is taken as a key of a dictionary, while project_api_key} is taken as the the value for the key, which is apparently wrong.
So we have a limitation here that a placeholder like {inputValue: project_api_key} must be on its own line (the list item).

I'm not sure that's the case. `- common.project_api_key={inputValue: project_api_key}` is just wrong YAML syntax. An item should wither be a string or dict, but not string-o-dict. Using quoting prevents parts of the value from being parsed as dict by the YAML parser. `- "common.project_api_key={inputValue: project_api_key}"`. However this does not solve the user issue - a string is just a string. The placeholder won't be substituted. We decided not to invent a new placeholder language that needs to be parsed. We use the YAML language instead. Placeholders are clearly distinguished from the verbatim strings by their type: verbatim strings are strings while placeholders are maps. For a proper solution, see the above code.
