### ISSUE TITLE
[bug] manifests: Metadata VirtualService is missing

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5398]
### What steps did you take

Install KFP from multi-user manifests.

### What happened:

The KFP Metadata UI is missing erroring out because it is missing a VirtualService. We tested with the following VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: metadata-grpc
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /ml_metadata
    rewrite:
      uri: /ml_metadata
    route:
    - destination:
        host: ml-pipeline-ui.kubeflow.svc.cluster.local
        port:
          number: 80
```
