### ISSUE TITLE
[bug] Argo kustomization does not replace namespace in ClusterRoleBinding ServiceAccount reference

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5402]
### What steps did you take

```sh
kustomize build pipelines/manifests/kustomize/env/platform-agnostic-multi-user
```

### What happened:

The generated ClusterRoleBinding has the namespace set as `argo`, even though kustomize sets it as `kubeflow`.
Here is the generated YAML:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
```

### What did you expect to happen:

Kustomize should have replaced the namespace with `kubeflow`:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: kubeflow
```

The reason that didn't happen is because the ClusterRoleBinding is defined as:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
```

but the ServiceAccount is defined as:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
```

because of that, kustomize doesn't register the ServiceAccount reference and doesn't substitute the namespace.

We tried to include a patch that removes the namespace line from the `ClusterRoleBinding` and it worked, so we will PR that.
