### ISSUE TITLE
[sdk] Task.after() on Condition OpsGroup vs ContainerOp

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#5422]
We have few questions on how the condition is constructed in Argo. e.g. using the below condition example
 https://github.com/kubeflow/pipelines/blob/master/samples/core/condition/condition.py

When we try to define a containerOp that run after dsl.condition or containerOp inside the condition block, it creates the same result when compiles to Argo. We are wondering is it the expected DSL behavior where the task dependencies should point to the Argo condition task in both cases?

```python
@dsl.pipeline(
    name='Conditional execution pipeline',
    description='Shows how to use dsl.Condition().'
)
def flipcoin_pipeline():
    flip = flip_coin_op()
    with dsl.Condition(flip.output == 'heads') as cond_a:
        random_num_head = random_num_op(0, 9)
        random_num_head2 = random_num_op(0, 9)

    with dsl.Condition(flip.output == 'tails') as cond_b:
        random_num_tail = random_num_op(10, 19)
        random_num_tail2 = random_num_op(10, 19)

    # print_output and print_output2 produce the same dependencies
    print_output = print_op('after cond_a cond_b').after(cond_a).after(cond_b)
    print_output2 = print_op('after random_num_head random_num_tail').after(random_num_head).after(random_num_tail)
```

In Argo dag:
```
    dag:
      tasks:
      - name: condition-1
        template: condition-1
        when: '"{{tasks.flip-coin.outputs.parameters.flip-coin-output}}" == "heads"'
        dependencies: [flip-coin]
      - name: condition-2
        template: condition-2
        when: '"{{tasks.flip-coin.outputs.parameters.flip-coin-output}}" == "tails"'
        dependencies: [flip-coin]
      - {name: flip-coin, template: flip-coin}
      - name: print
        template: print
        dependencies: [condition-1, condition-2]
      - name: print-2
        template: print-2
        dependencies: [condition-1, condition-2]
```

Thanks.

related docs: https://docs.google.com/document/d/1QPWKoeiPFDcI1JWH-nMe7x_xIJekL11bhu7Fp3fNT24/edit#
