### ISSUE TITLE
mlpipeline-ui-metadata.json not shown in output artifacts, using common pipeline volume. 

### ISSUE THREAD

**Issue by jagadeeshi2i** [kubeflow/pipelines#5460]
## Approach 1:
https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/
As mentioned in the above link, we tried to write mlpipeline-ui-metadata.json to `/mlpipeline-ui-metadata.json`
this throws the below error

`invalid mount config for type "bind": invalid specification: destination can't be '/`

Sample code from component yaml
```
    name: Training
    description: |
      Training for PyTorch.
    inputs:
      - {name: dataset}
      - {name: params, type: JsonArray}
    outputs:
      - {name: output}
      - {name: tensorboard_root}
      - {name: MLPipeline UI metadata, type: UI metadata}
    implementation:
      container:
        image: "pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime"
    .....
    fileOutputs: 
      MLPipeline UI metadata: /mlpipeline-ui-metadata.json
```

## Approach 2:
Tried writing the metadata information to a custom path as well using outputPath keyword.
We did not face the error faced in previous approach, yet we could not find the tar file in the output artifacts.

Sample code from component yaml
```
    name: Training
    description: |
      Training for PyTorch.
    inputs:
      - {name: dataset}
      - {name: params, type: JsonArray}
    outputs:
      - {name: output}
      - {name: tensorboard_root}
      - {name: MLPipeline UI metadata, type: UI metadata}
    implementation:
      container:
        image: "pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime"
    .....
    args:
    - {outputPath: MLPipeline UI metadata}
```

### What happened:
In approach 1 the training failed with the given error and in approach 2 the metadata file is not found.

### What did you expect to happen:
Metadata information should be shown in output artifacts and the corresponding visualization should be shown.

### Environment:
*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 1.4.1

*  KFP SDK version: 
kfp                                   1.4.0          
kfp-pipeline-spec                     0.1.7          
kfp-server-api                        1.4.1 

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
