### ISSUE TITLE
[v2 sample test] separate samples from tests?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5506]
> I think we might want to have some separation between what we show to the users and the internal test infra machinery.
> I'm not sure we should show the users with that test infra code.

_Originally posted by @Ark-kun in https://github.com/kubeflow/pipelines/pull/5473#discussion_r616266440_

**Comment by Bobgy** [comment]
@Ark-kun what kind of folder structure do you propose?

**Comment by Bobgy** [comment]
I don't strongly feel that we need to hide tests, maybe users also want to know how they can
* test their pipelines
* extract results from their pipelines in an external system

Also, for user facing samples, they are already in separate folders, so each folder only contains a few files. It's very easy to identify that some files ending with `_test.py` are the tests.

**Comment by Bobgy** [comment]
Also, we want new sample contributors to be able to easily setup a new test.

**Comment by Ark-kun** [comment]
> @Ark-kun what kind of folder structure do you propose?

I wonder whether we can reduce each test case to just an item in the test config YAML.
```yaml
- pipelineCodePath: path/to/sample.py
  compile:
    mode: V2Compat
    pipelineFunc: my_pipeline  # Optional
    arguments:  # Optional
      param1: value1
      param2: value2
- pipelineCodePath: path/to/sample2.py
...
```

P.S. This is only for trivial tests (compile, submit, wait for success). For non-trivial ones I fully support keeping tests near the samples.
