### ISSUE TITLE
[sdk] mlpipelines-metrics path is wrong when using kfp.components.load_component_from_text

### ISSUE THREAD

**Issue by santiagoolivar2017** [kubeflow/pipelines#5548]
Let me describe what my problem is:

- I am using load_component_from_text to define my components
- In the pipeline I am generating a mlpipeline-metrics artifact
- After compiling the pipeline I am checking the yaml file that is created
- Within the yaml file, I was expecting the path of this artifact to be **/mlpipeline-metrics.json**, but instead I am getting  **/tmp/outputs/MLPipeline_Metrics/data**
- This is causing Kubeflow UI to not show any output metrics.
- I am changing the paths on the yaml file to be **/mlpipeline-metrics.json** (as expected) and everything works as expected

Before I used to do this with ContainerOp and the paths seemed to be generated properly, which makes me think that there may be something wrong with how the aths are generated when the pipeline is compiled

### Steps to reproduce

```
load_component_from_text('''
    name: name_of_component        
    outputs:
      - {name: MLPipeline Metrics, type: Metrics}
    implementation:
        container:
            image: image_name
            command: [python, -u, script_name.py]
            args: [
                ...
                --metrics_path, {outputPath: MLPipeline Metrics}]
''')
```

### Expected result

yaml file with that contains the following information

```
name: model-training
    container:
      args: [ ...
        --metrics_path, /mlpipeline-metrics.json]
      command: [python, -u, script_name.py]
      image: image_name
    ... 
    ...
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /mlpipeline-metrics.json}
```

### Instead of the expected output I am getting the next output

```
name: model-training
    container:
      args: [ ...
        --metrics_path, /tmp/outputs/MLPipeline_Metrics/data]
      command: [python, -u, script_name.py]
      image: image_name
    ... 
    ...
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path:/tmp/outputs/MLPipeline_Metrics/data}
```
