### ISSUE TITLE
kubeflow 1.2.0 (kfctl_aws.v1.2.0.yaml) install failed to build LoadBalancer configuration on AWS (eks cluster).

### ISSUE THREAD

**Issue by amalendur** [kubeflow/pipelines#5929]
/kind bug.

I have deployed a EKS cluster and on top of that cluster I am trying to deploy "Kubeflow" through GitLab pipeline.
In the pipeline script I have set the Kube-context before execute the Kubeflow config-file(kfctl_aws.v1.2.0.yaml).
I have executed the steps in the following order;
1. Deploy EKS cluster with Nodegrop (deploy through terraform)
2. Download the Kubeflow config-file from "https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_aws.v1.2.0.yaml"
3. Update the config-file with 
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-1-3-1-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cluster-local-gateway-1-3-1
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: istio/istio/base
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/oidc-authservice
    name: oidc-authservice
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/dex-auth
    name: dex
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: spark/spark-operator/overlays/application
    name: spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: aws/istio-ingress/base_v3
    name: istio-ingress
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/spartakus
    name: spartakus
  plugins:
  - kind: KfAwsPlugin
    metadata:
      name: aws
    spec:
      auth:
        basicAuth:
          password: <password>
          username: admin
      region: <aws_default_region>
      #enablePodIamPolicy: true
      roles:
      - <eks_node_role>
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
```

```
<aws_region> : AWS Region, where the cluster has been created.
<eks_node_role> : Name of the IAM role for the nodegroup.
<password> : Admin password
```

4. Set the Kube-context;
`aws eks --region ${AWS_REGION} update-kubeconfig --name ${CLUSTER_NAME}`
5. Set the environment;
```
wget https://github.com/kubeflow/kfctl/releases/download/v1.2.0/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz --no-check-certificate && tar -xvzf kfctl_v1.2.0-0-gbc038f9_linux.tar.gz && chmod +x kfctl && cp ./kfctl /usr/local/bin/kfctl
curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator && chmod +x ./aws-iam-authenticator && cp ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
export AWS_CLUSTER_NAME=${CLUSTER_NAME}
export KF_NAME=${AWS_CLUSTER_NAME}
KF_DIR = /opt/ar-usv-poc-plt
kfctl build -f kfctl_aws.v1.2.0.yaml -V
kfctl apply -f kfctl_aws.v1.2.0.yaml -V
```

Getting the following error:
`E0628 14:56:25.659557       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/\u003ccluster name\u003e tag with a value of shared or owned and the kubernetes.io/role/elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were []"  "controller"="alb-ingress-controller" "request"={"Namespace":"istio-system","Name":"istio-ingress"}`
