### ISSUE TITLE
[bug] condition sample stuck in running state with argo v3.1.0

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5937]
### What steps did you take

1. run v2 sample test

### What happened:

1. it times out waiting for condition sample to finish
2. the sample runs and gets cached as usual
![image](https://user-images.githubusercontent.com/4957653/123727051-9847d980-d8c3-11eb-8793-6e9a8724ab65.png)
3. but the workflow itself is always stuck in running state

### What did you expect to happen:

the sample should finish as normal

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)?  KFP standalone 1.6.0-alpha.1

*  KFP SDK version: master

### Anything else you would like to add:

Here's status of the argo workflow, it's also stuck in running. So this is not a problem with persistence agent.

```
status:
  artifactRepositoryRef:
    default: true
  conditions:
  - status: "False"
    type: PodRunning
  finishedAt: null
  nodes:
    single-condition-pipeline-xb2hw:
      children:
      - single-condition-pipeline-xb2hw-690456091
      displayName: single-condition-pipeline-xb2hw
      finishedAt: null
      id: single-condition-pipeline-xb2hw
      inputs:
        parameters:
        - name: force_flip_result
          value: heads
        - name: text
          value: condition test
      name: single-condition-pipeline-xb2hw
      phase: Running
      progress: 4/4
      startedAt: "2021-06-28T13:58:12Z"
      templateName: single-condition-pipeline
      templateScope: local/single-condition-pipeline-xb2hw
      type: DAG
    single-condition-pipeline-xb2hw-151083147:
      boundaryID: single-condition-pipeline-xb2hw
      children:
      - single-condition-pipeline-xb2hw-329071385
      - single-condition-pipeline-xb2hw-1404454342
      displayName: condition-1
      finishedAt: "2021-06-28T13:59:30Z"
      id: single-condition-pipeline-xb2hw-151083147
      inputs:
        parameters:
        - name: text
          value: condition test
      name: single-condition-pipeline-xb2hw.condition-1
      outboundNodes:
      - single-condition-pipeline-xb2hw-1421231961
      - single-condition-pipeline-xb2hw-1404454342
      phase: Succeeded
      progress: 3/3
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-28T13:58:50Z"
      templateName: condition-1
      templateScope: local/single-condition-pipeline-xb2hw
      type: DAG
    single-condition-pipeline-xb2hw-329071385:
      boundaryID: single-condition-pipeline-xb2hw-151083147
      children:
      - single-condition-pipeline-xb2hw-1421231961
      displayName: flip-coin-2
      finishedAt: "2021-06-28T13:58:56Z"
      id: single-condition-pipeline-xb2hw-329071385
      name: single-condition-pipeline-xb2hw.condition-1.flip-coin-2
      outputs:
        artifacts:
        - name: flip-coin-2-Output
          path: /tmp/outputs/Output/data
          s3:
            key: artifacts/single-condition-pipeline-982vv/2021/06/28/single-condition-pipeline-982vv-3001282121/flip-coin-2-Output.tgz
        - name: main-logs
          s3:
            key: artifacts/single-condition-pipeline-982vv/2021/06/28/single-condition-pipeline-982vv-3001282121/main.log
        exitCode: "0"
        parameters:
        - name: flip-coin-2-Output
          value: heads
          valueFrom:
            path: /tmp/outputs/Output/data
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-28T13:58:50Z"
      templateName: flip-coin-2
      templateScope: local/single-condition-pipeline-xb2hw
      type: Pod
    single-condition-pipeline-xb2hw-690456091:
      boundaryID: single-condition-pipeline-xb2hw
      children:
      - single-condition-pipeline-xb2hw-151083147
      displayName: flip-coin
      finishedAt: "2021-06-28T13:58:41Z"
      hostNodeName: gke-kfp-std-default-pool-1c1207aa-2eyx
      id: single-condition-pipeline-xb2hw-690456091
      inputs:
        parameters:
        - name: force_flip_result
          value: heads
      name: single-condition-pipeline-xb2hw.flip-coin
      outputs:
        artifacts:
        - name: flip-coin-Output
          path: /tmp/outputs/Output/data
          s3:
            key: artifacts/single-condition-pipeline-xb2hw/2021/06/28/single-condition-pipeline-xb2hw-690456091/flip-coin-Output.tgz
        - name: main-logs
          s3:
            key: artifacts/single-condition-pipeline-xb2hw/2021/06/28/single-condition-pipeline-xb2hw-690456091/main.log
        exitCode: "0"
        parameters:
        - name: flip-coin-Output
          value: heads
          valueFrom:
            path: /tmp/outputs/Output/data
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 7
        memory: 2
      startedAt: "2021-06-28T13:58:12Z"
      templateName: flip-coin
      templateScope: local/single-condition-pipeline-xb2hw
      type: Pod
    single-condition-pipeline-xb2hw-1404454342:
      boundaryID: single-condition-pipeline-xb2hw-151083147
      displayName: print-msg-3
      finishedAt: "2021-06-28T13:59:02Z"
      hostNodeName: gke-kfp-std-default-pool-1c1207aa-2eyx
      id: single-condition-pipeline-xb2hw-1404454342
      inputs:
        parameters:
        - name: text
          value: condition test
      name: single-condition-pipeline-xb2hw.condition-1.print-msg-3
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: artifacts/single-condition-pipeline-982vv/2021/06/28/single-condition-pipeline-982vv-3511891414/main.log
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-28T13:58:50Z"
      templateName: print-msg-3
      templateScope: local/single-condition-pipeline-xb2hw
      type: Pod
    single-condition-pipeline-xb2hw-1421231961:
      boundaryID: single-condition-pipeline-xb2hw-151083147
      displayName: print-msg-2
      finishedAt: "2021-06-28T13:59:09Z"
      id: single-condition-pipeline-xb2hw-1421231961
      inputs:
        parameters:
        - name: flip-coin-2-Output
          value: heads
      name: single-condition-pipeline-xb2hw.condition-1.print-msg-2
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: artifacts/single-condition-pipeline-982vv/2021/06/28/single-condition-pipeline-982vv-3528669033/main.log
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-28T13:59:00Z"
      templateName: print-msg-2
      templateScope: local/single-condition-pipeline-xb2hw
      type: Pod
    single-condition-pipeline-xb2hw-3316531579:
      boundaryID: single-condition-pipeline-xb2hw
      displayName: print-msg
      finishedAt: "2021-06-28T13:59:04Z"
      hostNodeName: gke-kfp-std-default-pool-1c1207aa-2eyx
      id: single-condition-pipeline-xb2hw-3316531579
      inputs:
        parameters:
        - name: flip-coin-Output
          value: heads
      name: single-condition-pipeline-xb2hw.print-msg
      outputs:
        artifacts:
        - name: main-logs
          s3:
            key: artifacts/single-condition-pipeline-982vv/2021/06/28/single-condition-pipeline-982vv-1648329963/main.log
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-06-28T13:58:50Z"
      templateName: print-msg
      templateScope: local/single-condition-pipeline-xb2hw
      type: Pod
  phase: Running
  progress: 5/5
  resourcesDuration:
    cpu: 7
    memory: 2
  startedAt: "2021-06-28T13:58:12Z"
```

### Labels

/area sdk

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
