### ISSUE TITLE
[sdk] Some keys in json used in ParallelFor break compilation

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/pipelines#6020]
### Environment

*  KFP SDK version: 1.6.3
*  All dependencies version:
  * kfp 1.6.3
  * kfp-pipeline-spec 0.1.8
  * kfp-server-api 1.4.1

### Steps to reproduce

Create a pipeline where `dsl.ParallelFor` either:
* accepts a list literal with the first item being a dictionary with `"name"` key
* accesses its item's `.name` field
* both (behaves like the first one)

In the first and third case, the compilation fails with a bizarre errors. In the second case, it simply produces wrong yaml.

Example of the first case:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

@dsl.pipeline("decomposition test: non-dict")
def decomposition_test_00():
  string_list_literal = ["foo", "bar"]
  with dsl.ParallelFor(string_list_literal) as item:
    PrintOp(f"{item}")

@dsl.pipeline("decomposition test: dict without 'name' key")
def decomposition_test_01():
  dict_ok_list_literal = [
    {
      "_name": "foo",
      "_value": 42,
    },
    {
      "_name": "bar",
      "_value": 3141592
    }
  ]
  with dsl.ParallelFor(dict_ok_list_literal) as item:
    name = item._name
    value = item._value
    PrintOp(f"{name}={value}")

@dsl.pipeline("decomposition test: dict with 'name' key")
def decomposition_test_02():
  dict_err_list_literal = [
    {
      "name": "foo",
      "value": 42,
    },
    {
      "name": "bar",
      "value": 3141592
    }
  ]
  with dsl.ParallelFor(dict_err_list_literal) as item:
    name = item.name
    value = item.value
    PrintOp(f"{name}={value}")

decomposition_tests = [
  decomposition_test_00,
  decomposition_test_01,
  decomposition_test_02,
]

if __name__ == '__main__':
  from kfp.compiler import Compiler
  for i, decomposition_test in enumerate(decomposition_tests):
    print(decomposition_test._component_human_name)
    Compiler().compile(decomposition_test, __file__.replace('.py', f'-{i}.argo.yaml'))
```

The compilation breaks in two distinct ways, I'm not sure what determines which is triggered, as they seem to interleave when I call the script multiple times.

First one:
```
$ python3 decompose.py
decomposition test: non-dict
decomposition test: dict with 'name' key
Traceback (most recent call last):
  File "(...)/decompose.py", line 71, in <module>
    Compiler().compile(decomposition_test, __file__.replace('.py', f'-{i}.argo.yaml'))
  File "(...)/site-packages/kfp/compiler/compiler.py", line 1053, in compile
    self._create_and_write_workflow(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 1106, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 946, in _create_workflow
    workflow = self._create_pipeline_workflow(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 713, in _create_pipeline_workflow
    templates = self._create_dag_templates(pipeline, op_transformers)
  File "(...)/site-packages/kfp/compiler/compiler.py", line 653, in _create_dag_templates
    inputs, outputs = self._get_inputs_outputs(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 303, in _get_inputs_outputs
    if loop_group.loop_args.name in param.name:
TypeError: 'in <string>' requires string as left operand, not LoopArgumentVariable
```

Second one:
```
$ python3 decompose.py
decomposition test: non-dict
decomposition test: dict with 'name' key
Traceback (most recent call last):
  File "(...)/decompose.py", line 71, in <module>
    Compiler().compile(decomposition_test, __file__.replace('.py', f'-{i}.argo.yaml'))
  File "(...)/site-packages/kfp/compiler/compiler.py", line 1053, in compile
    self._create_and_write_workflow(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 1106, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "(...)/site-packages/kfp/compiler/compiler.py", line 896, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "(...)/decompose.py", line 56, in decomposition_test_02
    with dsl.ParallelFor(dict_err_list_literal) as item:
  File "(...)/site-packages/kfp/dsl/_ops_group.py", line 226, in __init__
    loop_args = _for_loop.LoopArguments(
  File "(...)/site-packages/kfp/dsl/_for_loop.py", line 76, in __init__
    LoopArgumentVariable(
  File "(...)/site-packages/kfp/dsl/_for_loop.py", line 159, in __init__
    super().__init__(
  File "(...)/site-packages/kfp/dsl/_pipeline_param.py", line 171, in __init__
    raise ValueError(
ValueError: Only letters, numbers, spaces, "_", and "-" are allowed in name.
Must begin with a letter. Got name: {{pipelineparam:op=;name=loop-item-param-2-subvar-name}}-subvar-value
```

If the json is passed as a parameter instead of a literal:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

@dsl.pipeline("decomposition test: non-dict")
def decomposition_test_00(
  string_list_literal = ["foo", "bar"]
):
  with dsl.ParallelFor(string_list_literal) as item:
    PrintOp(f"{item}")

@dsl.pipeline("decomposition test: dict without 'name' key")
def decomposition_test_01(
  dict_ok_list_literal = [
    {
      "_name": "foo",
      "_value": 42,
    },
    {
      "_name": "bar",
      "_value": 3141592
    }
  ]
):
  with dsl.ParallelFor(dict_ok_list_literal) as item:
    name = item._name
    value = item._value
    PrintOp(f"{name}={value}")

@dsl.pipeline("decomposition test: dict with 'name' key")
def decomposition_test_02(
  dict_err_list_literal = [
    {
      "name": "foo",
      "value": 42,
    },
    {
      "name": "bar",
      "value": 3141592
    }
  ]
):
  with dsl.ParallelFor(dict_err_list_literal) as item:
    name = item.name
    value = item.value
    PrintOp(f"{name}={value}")

decomposition_tests = [
  decomposition_test_00,
  decomposition_test_01,
  decomposition_test_02,
]

if __name__ == '__main__':
  from kfp.compiler import Compiler
  for i, decomposition_test in enumerate(decomposition_tests):
    print(decomposition_test._component_human_name)
    Compiler().compile(decomposition_test, __file__.replace('.py', f'-{i}.argo.yaml'))
```

then all three compile, but there is a vital difference between the second and third pipeline:

Second pipeline (no `"name"` key used):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: decomposition-test-dict-without-name-key-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-07-12T15:38:57.369128',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[{\"_name\": \"foo\",
      \"_value\": 42}, {\"_name\": \"bar\", \"_value\": 3141592}]", "name": "dict_ok_list_literal",
      "optional": true}], "name": "decomposition test: dict without ''name'' key"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: decomposition-test-dict-without-name-key
  templates:
  - name: decomposition-test-dict-without-name-key
    dag:
      tasks:
      - name: for-loop-1
        template: for-loop-1
        arguments:
          parameters:
          - {name: dict_ok_list_literal-loop-item-subvar-_name, value: '{{item._name}}'}
          - {name: dict_ok_list_literal-loop-item-subvar-_value, value: '{{item._value}}'}
        withParam: '{{workflow.parameters.dict_ok_list_literal}}'
  - name: for-loop-1
    inputs:
      parameters:
      - {name: dict_ok_list_literal-loop-item-subvar-_name}
      - {name: dict_ok_list_literal-loop-item-subvar-_value}
    dag:
      tasks:
      - name: print
        template: print
        arguments:
          parameters:
          - {name: dict_ok_list_literal-loop-item-subvar-_name, value: '{{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_name}}'}
          - {name: dict_ok_list_literal-loop-item-subvar-_value, value: '{{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_value}}'}
  - name: print
    container:
      args: []
      command: ['echo {{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_name}}={{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_value}}']
      image: alpine:3.6
    inputs:
      parameters:
      - {name: dict_ok_list_literal-loop-item-subvar-_name}
      - {name: dict_ok_list_literal-loop-item-subvar-_value}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image": "alpine:3.6"}},
          "inputs": [{"name": "msg"}], "name": "print", "outputs": [{"name": "stdout"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "759d33433106734a4f8d748310b0ec7fc618e428176f270b6e33b782526870c8"}',
        pipelines.kubeflow.org/arguments.parameters: '{"msg": "{{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_name}}={{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_value}}"}'}
  arguments:
    parameters:
    - {name: dict_ok_list_literal, value: '[{"_name": "foo", "_value": 42}, {"_name":
        "bar", "_value": 3141592}]'}
  serviceAccountName: pipeline-runner
```

Third pipeline (`"name"` used):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: decomposition-test-dict-with-name-key-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-07-12T15:38:57.381484',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[{\"name\": \"foo\",
      \"value\": 42}, {\"name\": \"bar\", \"value\": 3141592}]", "name": "dict_err_list_literal",
      "optional": true}], "name": "decomposition test: dict with ''name'' key"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: decomposition-test-dict-with-name-key
  templates:
  - name: decomposition-test-dict-with-name-key
    dag:
      tasks:
      - {name: for-loop-1, template: for-loop-1, withParam: '{{workflow.parameters.dict_err_list_literal}}'}
  - name: for-loop-1
    dag:
      tasks:
      - {name: print, template: print}
  - name: print
    container:
      args: []
      command: [echo dict_err_list_literal-loop-item=None]
      image: alpine:3.6
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image": "alpine:3.6"}},
          "inputs": [{"name": "msg"}], "name": "print", "outputs": [{"name": "stdout"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "759d33433106734a4f8d748310b0ec7fc618e428176f270b6e33b782526870c8"}',
        pipelines.kubeflow.org/arguments.parameters: '{"msg": "dict_err_list_literal-loop-item=None"}'}
  arguments:
    parameters:
    - {name: dict_err_list_literal, value: '[{"name": "foo", "value": 42}, {"name":
        "bar", "value": 3141592}]'}
  serviceAccountName: pipeline-runner
```

The key difference being:
```
<  command: ['echo {{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_name}}={{inputs.parameters.dict_ok_list_literal-loop-item-subvar-_value}}']
---
>  command: [echo dict_err_list_literal-loop-item=None]
```
`dict_err_list_literal-loop-item=None` is nothing like the `"name"` field of the item.

### Expected result

The compilation either working just fine and producing results which are analogous.

### Materials and Reference

While the second case was very puzzling for me, the second error message of the first case certainly looks like stringified PipelineParam of a sub-var, i.e. `LoopArguments`. So I took a look at its code and [here is what I found](https://github.com/kubeflow/pipelines/blob/a0fd14b276bc05fb1ddcd3681621e9f44a23bb2a/sdk/python/kfp/dsl/_for_loop.py#L59-L76):
```python
if isinstance(items, list) and isinstance(items[0], dict):
  subvar_names = set(items[0].keys())
  for item in items:
    if not set(item.keys()) == subvar_names:
      raise ValueError(
          'If you input a list of dicts then all dicts should have the same keys. '
          'Got: {}.'.format(items))

  # then this block creates loop_args.variable_a and loop_args.variable_b
  for subvar_name in subvar_names:
    if not self._subvar_name_is_legal(subvar_name):
      raise ValueError(
          "Tried to create subvariable named {} but that's not a legal Python variable "
          'name.'.format(subvar_name))
    setattr(
        self, subvar_name,
        LoopArgumentVariable(
            self.name, subvar_name, loop_args_op_name=self.op_name))
```
i.e. if a literal if used, an attribute gets assigned to the class.

But later on in the class, custom attribute accessor [is defined anyway](https://github.com/kubeflow/pipelines/blob/a0fd14b276bc05fb1ddcd3681621e9f44a23bb2a/sdk/python/kfp/dsl/_for_loop.py#L91-L96):
```python
def __getattr__(self, item):
  # this is being overridden so that we can access subvariables of the
  # LoopArguments (i.e.: item.a) without knowing the subvariable names ahead
  # of time
  self.referenced_subvar_names.append(item)
  return LoopArgumentVariable(self.name, item, loop_args_op_name=self.op_name)
```

So when I removed the first fragment entirely, I immediately got rid of the error and the first case produced yaml similar to the second case, i.e. containing `command: [echo loop-item-param-2=None]`. That explains the difference between literal and non-literal versions. But why both contain any error in general?

Because `LoopArguments` is a subclass of `PipelineParam`, I checked [its code](https://github.com/kubeflow/pipelines/blob/a0fd14b276bc05fb1ddcd3681621e9f44a23bb2a/sdk/python/kfp/dsl/_pipeline_param.py#L140-L183):
```python
class PipelineParam(object):
  """(...)
  Args:
    name: name of the pipeline parameter.
    (...)
    value: The actual value of the PipelineParam. If provided, the PipelineParam
      is "resolved" immediately. For now, we support string only.
    (...)
  """

  def __init__(self,
               name: str,
               op_name: Optional[str] = None,
               value: Optional[str] = None,
               param_type: Optional[Union[str, Dict]] = None,
               pattern: Optional[str] = None):
    valid_name_regex = r'^[A-Za-z][A-Za-z0-9\s_-]*$'
    if not re.match(valid_name_regex, name):
      raise ValueError(
          'Only letters, numbers, spaces, "_", and "-" are allowed in name. '
          'Must begin with a letter. Got name: {}'.format(name))

    if op_name and value:
      raise ValueError('op_name and value cannot be both set.')

    self.name = name
    # ensure value is None even if empty string or empty list
    # so that serialization and unserialization remain consistent
    # (i.e. None => '' => None)
    self.op_name = op_name if op_name else None
    self.value = value
```

Which explains `dict_err_list_literal-loop-item=None` --- it's the `LoopArgument`'s `name` field, `=`, and the default value of the `value` field --- `None`.

Now, that's inconsistent with how the user can access any other field in the list of json objects/dicts. What's worse: adding a new field in PipelineParam can potentially break the now-working-fine user pipelines.

I expect few users used `name` and `value` of `LoopArguments` expecting the ones from `PipelineParam` --- in fact, I don't think its fields are useful to users in general, as they describe the internal compiler info, like what's the name (most of the time it's similar to the name of variable, so why would user need that?), its default value (it's written directly in the signature, so why would user need that?) or the task that produced it (PipelineParams are produced either in pipeline-or-graph signatures, `dsl.ParallelFor(...) as item` or `.output`/`.outputs[...]` --- why would user need that?). Besides, it seems to me that it's much easier to explain to the user that ALL of the fields accessed in `LoopArguments` are simply it's keys. Therefore, I assume it's ok to simply change it so that during the pipeline building, all fields of `LoopArguments` are treated as json fields, and it only turns back to the behaviour of the regular `PipelineParam` inside of the `Compiler`.

## Proposed solution (early POC)
For that, I created a POC with the following changes:
* remove the above-mentioned setting attributes in `LoopArguments` --- as already shown, it's not really needed for the syntax to work fine (alternatively, one may add a check which only sets the attribute if it's not there yet)
* change attribute access in PipelineParam's magical methods methods to `object.__getattribute__` so that e.g. `__str__` (which used a lot) works just like before no matter where it's used
* introduce a global variable `loop_arguments_decomposing`, defaulting to `True`
* temporarily set that variable to `False` in `LoopArgument`'s constructor (otherwise, `object.__getattribute__` would need to be used again, which is more effort), and placing it inside of try-catch or some context manager so that exceptions won't affect setting it back
* change `__getattr__` method into a `__getattribute__` method with the following implementation (very similar to the previous one, except for checking for `loop_arguments_decomposing` and `object.__getattribute__` (could use `super()` too):
  ```python
  def __getattribute__(self, item):
    global loop_arguments_decomposing
    if not loop_arguments_decomposing:
      return object.__getattribute__(self, item)

    referenced_subvar_names = object.__getattribute__(self, 'referenced_subvar_names')
    name = object.__getattribute__(self, 'name')
    op_name = object.__getattribute__(self, 'op_name')

    referenced_subvar_names.append(item)
    return LoopArgumentVariable(name, item, loop_args_op_name=op_name)
  ```
* temporarily set the `loop_arguments_decomposing` to `False` in `_create_workflow` in compiler.py, right after the `pipeline_func` call, and placing it inside of try-catch or some context manager so that exceptions won't affect setting it back
* (optional) add `__getitem__` to `LoopArguments` to be able to access keys that aren't valid Python identifiers, e.g. containing `-` --- it should work fine with the `loop_arguments_decomposing`, as it's a magical method

When I did all of that, I got both cases (with literals and without literals) working just fine:

With literals:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: decomposition-test-dict-with-name-key-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-07-12T17:27:43.321192',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "decomposition test: dict with
      ''name'' key"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: decomposition-test-dict-with-name-key
  templates:
  - name: decomposition-test-dict-with-name-key
    dag:
      tasks:
      - name: for-loop-3
        template: for-loop-3
        arguments:
          parameters:
          - {name: loop-item-param-2-subvar-name, value: '{{item.name}}'}
          - {name: loop-item-param-2-subvar-value, value: '{{item.value}}'}
        withItems:
        - {name: foo, value: 42}
        - {name: bar, value: 3141592}
  - name: for-loop-3
    inputs:
      parameters:
      - {name: loop-item-param-2-subvar-name}
      - {name: loop-item-param-2-subvar-value}
    dag:
      tasks:
      - name: print
        template: print
        arguments:
          parameters:
          - {name: loop-item-param-2-subvar-name, value: '{{inputs.parameters.loop-item-param-2-subvar-name}}'}
          - {name: loop-item-param-2-subvar-value, value: '{{inputs.parameters.loop-item-param-2-subvar-value}}'}
  - name: print
    container:
      args: []
      command: ['echo {{inputs.parameters.loop-item-param-2-subvar-name}}={{inputs.parameters.loop-item-param-2-subvar-value}}']
      image: alpine:3.6
    inputs:
      parameters:
      - {name: loop-item-param-2-subvar-name}
      - {name: loop-item-param-2-subvar-value}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image": "alpine:3.6"}},
          "inputs": [{"name": "msg"}], "name": "print", "outputs": [{"name": "stdout"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "759d33433106734a4f8d748310b0ec7fc618e428176f270b6e33b782526870c8"}',
        pipelines.kubeflow.org/arguments.parameters: '{"msg": "{{inputs.parameters.loop-item-param-2-subvar-name}}={{inputs.parameters.loop-item-param-2-subvar-value}}"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
```

With pipeline parameter:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: decomposition-test-dict-with-name-key-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-07-12T17:27:52.110929',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[{\"name\": \"foo\",
      \"value\": 42}, {\"name\": \"bar\", \"value\": 3141592}]", "name": "dict_err_list_literal",
      "optional": true}], "name": "decomposition test: dict with ''name'' key"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: decomposition-test-dict-with-name-key
  templates:
  - name: decomposition-test-dict-with-name-key
    dag:
      tasks:
      - name: for-loop-1
        template: for-loop-1
        arguments:
          parameters:
          - {name: dict_err_list_literal-loop-item-subvar-name, value: '{{item.name}}'}
          - {name: dict_err_list_literal-loop-item-subvar-value, value: '{{item.value}}'}
        withParam: '{{workflow.parameters.dict_err_list_literal}}'
  - name: for-loop-1
    inputs:
      parameters:
      - {name: dict_err_list_literal-loop-item-subvar-name}
      - {name: dict_err_list_literal-loop-item-subvar-value}
    dag:
      tasks:
      - name: print
        template: print
        arguments:
          parameters:
          - {name: dict_err_list_literal-loop-item-subvar-name, value: '{{inputs.parameters.dict_err_list_literal-loop-item-subvar-name}}'}
          - {name: dict_err_list_literal-loop-item-subvar-value, value: '{{inputs.parameters.dict_err_list_literal-loop-item-subvar-value}}'}
  - name: print
    container:
      args: []
      command: ['echo {{inputs.parameters.dict_err_list_literal-loop-item-subvar-name}}={{inputs.parameters.dict_err_list_literal-loop-item-subvar-value}}']
      image: alpine:3.6
    inputs:
      parameters:
      - {name: dict_err_list_literal-loop-item-subvar-name}
      - {name: dict_err_list_literal-loop-item-subvar-value}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image": "alpine:3.6"}},
          "inputs": [{"name": "msg"}], "name": "print", "outputs": [{"name": "stdout"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "759d33433106734a4f8d748310b0ec7fc618e428176f270b6e33b782526870c8"}',
        pipelines.kubeflow.org/arguments.parameters: '{"msg": "{{inputs.parameters.dict_err_list_literal-loop-item-subvar-name}}={{inputs.parameters.dict_err_list_literal-loop-item-subvar-value}}"}'}
  arguments:
    parameters:
    - {name: dict_err_list_literal, value: '[{"name": "foo", "value": 42}, {"name":
        "bar", "value": 3141592}]'}
  serviceAccountName: pipeline-runner
```

It seems to me that this solution is quite simple and very general, as one can add as many fields to the `PipelineParam` as they like as no non-magical methods are expected to be available to the user (the only one I can think of is `ignore_type`, but I don't think it's really used with pipeline items? we could add it as an exception in `__getattribute__`, but I'd rather avoid that, as it has the same problems as `"name"` and `"value"`, just a little less probable to be used, maybe --- it seems easier to explain to the user that they need to use a function `ignore_type` instead of a method `.ignore_type()`, rather than explain why they can't have a field called `"ignore_type"` in their json...) and all magical methods are implemented using `object.__getattribute__` instead of the usual dot access --- which isn't much, considering it's just two classes with a little amount of methods, most of which are only used in the compiler where the dot access is fine.

What do you think? Does that solution sound ok?

I will post a PR later on, after I polish the code a little bit.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
