### ISSUE TITLE
[sdk] ParallelFor does not apply parallelism on the right template.

### ISSUE THREAD

**Issue by dithyrambe** [kubeflow/pipelines#6588]
### Environment

*  KFP SDK version: `1.8.2`
*  All dependencies version:
```bash
kfp                      1.8.2
kfp-pipeline-spec        0.1.10
kfp-server-api           1.7.0
```

### Steps to reproduce

```python
#pipeline.py

import kfp


@kfp.components.func_to_container_op
def dummy_op(arg):
    pass


@kfp.components.func_to_container_op
def other_op(arg):
    pass


@kfp.dsl.pipeline(name="For loop pipeline")
def pipeline(args: list):
    with kfp.dsl.ParallelFor(args, parallelism=2) as item:
        task1 = dummy_op(item)
        task2 = other_op(item)

        task2.after(task1)

```

### Expected result

The pipelines runs but compiling this pipeline with `dsl-compile --py pipeline.py --output ./pipeline.yaml` puts the `parallelism: 2` on a supposedly wrong template. Thus, when running this pipeline with 4 items in `args`, all 4 task are scheduled at once instead of keeping a maximum parallelism at 2. In the compiled YAML I was expecting to see `parallelism: 2` within the `entrypoint` template (the one with the `withParam` section). 
Actually, when manually moving `parallelism: 2` to the entrypoint template, it works as intended.

See below
Actual output:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: for-loop-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-09-27T18:40:10.602539',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "args", "type": "JsonArray"}],
      "name": "For loop pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.2}
spec:
  entrypoint: for-loop-pipeline
  templates:
  - name: dummy-op
    container:
      args: [--arg, '{{inputs.parameters.args-loop-item}}']
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def dummy_op(arg):
            pass

        import argparse
        _parser = argparse.ArgumentParser(prog='Dummy op', description='')
        _parser.add_argument("--arg", dest="arg", type=str, required=True, default=argparse.SUPPRESS)
        _parsed_args = vars(_parser.parse_args())

        _outputs = dummy_op(**_parsed_args)
      image: python:3.7
    inputs:
      parameters:
      - {name: args-loop-item}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.2
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--arg", {"inputValue": "arg"}], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf
          \"%s\" \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n",
          "def dummy_op(arg):\n    pass\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Dummy
          op'', description='''')\n_parser.add_argument(\"--arg\", dest=\"arg\", type=str,
          required=True, default=argparse.SUPPRESS)\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = dummy_op(**_parsed_args)\n"], "image": "python:3.7"}}, "inputs": [{"name":
          "arg"}], "name": "Dummy op"}', pipelines.kubeflow.org/component_ref: '{}',
        pipelines.kubeflow.org/arguments.parameters: '{"arg": "{{inputs.parameters.args-loop-item}}"}'}
  - name: for-loop-1
    parallelism: 2
    inputs:
      parameters:
      - {name: args-loop-item}
    dag:
      tasks:
      - name: dummy-op
        template: dummy-op
        arguments:
          parameters:
          - {name: args-loop-item, value: '{{inputs.parameters.args-loop-item}}'}
      - name: other-op
        template: other-op
        dependencies: [dummy-op]
        arguments:
          parameters:
          - {name: args-loop-item, value: '{{inputs.parameters.args-loop-item}}'}
  - name: for-loop-pipeline
    dag:
      tasks:
      - name: for-loop-1
        template: for-loop-1
        arguments:
          parameters:
          - {name: args-loop-item, value: '{{item}}'}
        withParam: '{{workflow.parameters.args}}'
  - name: other-op
    container:
      args: [--arg, '{{inputs.parameters.args-loop-item}}']
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def other_op(arg):
            pass

        import argparse
        _parser = argparse.ArgumentParser(prog='Other op', description='')
        _parser.add_argument("--arg", dest="arg", type=str, required=True, default=argparse.SUPPRESS)
        _parsed_args = vars(_parser.parse_args())

        _outputs = other_op(**_parsed_args)
      image: python:3.7
    inputs:
      parameters:
      - {name: args-loop-item}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.2
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--arg", {"inputValue": "arg"}], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf
          \"%s\" \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n",
          "def other_op(arg):\n    pass\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Other
          op'', description='''')\n_parser.add_argument(\"--arg\", dest=\"arg\", type=str,
          required=True, default=argparse.SUPPRESS)\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = other_op(**_parsed_args)\n"], "image": "python:3.7"}}, "inputs": [{"name":
          "arg"}], "name": "Other op"}', pipelines.kubeflow.org/component_ref: '{}',
        pipelines.kubeflow.org/arguments.parameters: '{"arg": "{{inputs.parameters.args-loop-item}}"}'}
  arguments:
    parameters:
    - {name: args}
  serviceAccountName: pipeline-runner
```
Applying this diff fixes the issue:
```diff
--- pipeline.yaml	2021-09-27 18:40:10.608158969 +0200
+++ fixed.yaml	2021-09-27 18:42:43.469024168 +0200
@@ -50,3 +50,2 @@
   - name: for-loop-1
-    parallelism: 2
     inputs:
@@ -68,2 +67,3 @@
   - name: for-loop-pipeline
+    parallelism: 2
     dag:
```

### Materials and Reference

Am I somehow using `ParallelFor` in a wrong way ?

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
