### ISSUE TITLE
ml-pipeline, metadata-grpc, ml-pipeline-persistentagent restart constantly

### ISSUE THREAD

**Issue by konsloiz** [kubeflow/pipelines#6922]
Hello everyone. We are trying to deploy KFP in an enterprise cluster. Unfortunately, the ml-pipeline, metadata-grpc, ml-pipeline-persistentagent pods are not initialized and they are constantly being restarted. Any ideas?

**ml-pipeline-persistentagent logs**

```bash
time="2021-11-18T11:51:41Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1beta1/healthz: dial tcp 10.254.96.234:8888: connect: connection refused: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1beta1/healthz: dial tcp 10.254.96.234:8888: connect: connection refused"
```

**metadata-grpc logs**
Empty

**ml-pipeline logs**

```bash
I1118 11:48:35.998899       7 client_manager.go:160] Initializing client manager
I1118 11:48:35.998974       7 config.go:57] Config DBConfig.ExtraParams not specified, skipping
```

![KFP pods](https://user-images.githubusercontent.com/22999070/142410060-542cc67c-2835-41cc-9499-eb03b358b0bd.png)

**Comment by zijianjoy** [comment]
Can you look at the the yaml definition, events and logs in `ml-pipeline`? 

```
kubectl logs my-pod --previous 
```

https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods

**Comment by konsloiz** [comment]
> kubectl logs my-pod --previous

Thanks for the reply. 

**ml-pipelines: logs**

```bash
I1119 07:39:09.049099       7 client_manager.go:160] Initializing client manager
I1119 07:39:09.049182       7 config.go:57] Config DBConfig.ExtraParams not specified, skipping
```

**ml-pipelines: events**

```bash
25m         Warning   Unhealthy   pod/ml-pipeline-f55c9d8cf-xbd2m                     Readiness probe failed:
9m53s       Warning   BackOff     pod/ml-pipeline-f55c9d8cf-xbd2m                     Back-off restarting failed container
5m1s        Warning   Unhealthy   pod/ml-pipeline-f55c9d8cf-xbd2m                     Liveness probe failed:
```

ml-pipelines-apiserver-deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline
  name: ml-pipeline
spec:
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - env:
        - name: AUTO_UPDATE_PIPELINE_DEFAULT_VERSION
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: autoUpdatePipelineDefaultVersion
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OBJECTSTORECONFIG_SECURE
          value: "false"
        - name: OBJECTSTORECONFIG_BUCKETNAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: bucketName
        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DBCONFIG_DBNAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: pipelineDb
        - name: DBCONFIG_HOST
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: dbHost
        - name: DBCONFIG_PORT
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: dbPort
        - name: DBCONFIG_CONMAXLIFETIMESEC
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: ConMaxLifeTimeSec
        - name: OBJECTSTORECONFIG_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
        - name: OBJECTSTORECONFIG_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
        image: registry.app.corpintra.net/dna/ml-pipeline/api-server:dummy
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-api-server
        ports:
        - name: http
          containerPort: 8888
        - name: grpc
          containerPort: 8887
        readinessProbe:
          exec:
            command:
              - wget
              - -q # quiet
              - -S # show server response
              - -O
              - "-" # Redirect output to stdout
              - http://localhost:8888/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - wget
              - -q # quiet
              - -S # show server response
              - -O
              - "-" # Redirect output to stdout
              - http://localhost:8888/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
      serviceAccountName: ml-pipeline
```

Also, I want to add here (maybe this can help) that the DBs are not created inside the MySQL Pod


![image](https://user-images.githubusercontent.com/22999070/142585587-e5fbf748-425c-4262-b673-2afce4dcf927.png)


Let me know if you need anything more. Thanks for helping me out.
