### ISSUE TITLE
Not using secret when pulling from private Registry

### ISSUE THREAD

**Issue by rummens** [kubeflow/pipelines#695]
Hello,

I am trying out the new Pipeline Features but I cannot get a Pipeline working pulling containers from a private (Azure) Registry. I tried pulling everything localy and it works. I created a secret using these instructions [https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/](url)

I also added the secret to the yaml of the pipeline (also is there a way to this using the compiling tool?):

```
- container:
      args:
      - --project
      - '{{inputs.parameters.project}}'
      - --mode
      - cloud
      - --bucket
      - '{{inputs.parameters.bucket}}'
      - --start_year
      - '{{inputs.parameters.startyear}}'
      image: kubtestregistry.azurecr.io/babyweight:v1
      imagePullSecrets:
      - name: regcred
    inputs:
      parameters:
      - name: bucket
      - name: project
      - name: startyear
```

But still the pipeline fails with an authentication error, here are the last events of the corresponding pod: 

```
Events:
  Type     Reason     Age                From                               Message
  ----     ------     ----               ----                               -------
  Normal   Scheduled  77s                default-scheduler                  Successfully assigned kubeflow/babyweight-2lnns-1712976165 to aks-agentpool-34799199-0
  Normal   Pulling    74s                kubelet, aks-agentpool-34799199-0  pulling image "argoproj/argoexec:v2.2.0"
  Normal   Pulled     65s                kubelet, aks-agentpool-34799199-0  Successfully pulled image "argoproj/argoexec:v2.2.0"
  Normal   Started    60s                kubelet, aks-agentpool-34799199-0  Started container
  Normal   Created    60s                kubelet, aks-agentpool-34799199-0  Created container
  Warning  Failed     31s (x3 over 75s)  kubelet, aks-agentpool-34799199-0  Failed to pull image "kubtestregistry.azurecr.io/babyweight:v1": rpc error: code = Unknown desc = Error response from daemon: Get https://kubtestregistry.azurecr.io/v2/babyweight/manifests/v1: unauthorized: authentication required
  Warning  Failed     31s (x3 over 75s)  kubelet, aks-agentpool-34799199-0  Error: ErrImagePull
  Normal   Pulling    31s (x3 over 76s)  kubelet, aks-agentpool-34799199-0  pulling image "kubtestregistry.azurecr.io/babyweight:v1"
  Normal   BackOff    7s (x4 over 58s)   kubelet, aks-agentpool-34799199-0  Back-off pulling image "kubtestregistry.azurecr.io/babyweight:v1"
  Warning  Failed     7s (x4 over 58s)   kubelet, aks-agentpool-34799199-0  Error: ImagePullBackOff
```

Thanks very much.
Marcel
