### ISSUE TITLE
Why is certificates.k8s.io/v1 used in Cache Deployer instead of OpenSSL?

### ISSUE THREAD

**Issue by konsloiz** [kubeflow/pipelines#7437]
Caching is one of the most crucial features of KFP. Each time a pipeline step is the same as an already executed, the results are loaded from the cache server. Caching is accomplished in KFP via two interdependent modules: the cache deployer and the cache server. 

While trying to set up the modules in an enterprise cluster ([Mercedes-Benz AG](https://github.com/mercedes-benz/DnA)), it was noted that the installation couldn’t be completed. The reason was that the cache deployer is built to generate a Signed Certificate for the cache server by referring to the Kubernetes Certificate-SigningRequest API.

``` yaml
...

# create  server cert/key CSR and  send to k8s API
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

..

``` 

The usage of API server certificates in our enterprise environment is restricted because those allow permission escalation. The security risk is critical, as by using this API, users can order certificates that let them impersonate both Kubernetes control plane and cluster team access.

To adjust the cache deployer’s certificate generation process without affecting the actual functionality to avoid loosening the security restrictions, we [used](https://github.com/mercedes-benz/DnA/blob/9c2487e111490285ee57dc241aa27778a1acc774/deployment/dockerfiles/kubeflow/kfp/backend/src/cache/deployer/webhook-create-signed-cert.sh#L98) the widely-known OpenSSL.

Is there any specific reason for using the K8s API? 
If not, would the community be interested in an upstream contribution?
