### ISSUE TITLE
[feature] add `component_id` and `component_version` to Component YAML spec

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#7832]
### Feature Area

/area components 

### What feature would you like to see?

Right now, Kubeflow Pipelines has no native concept of "versioning" the same Component YAML over time.
If changes are made to a Component's YAML, existing pipelines may break or do unexpected things.

Given this, the only sensible strategy is __treating each Component YAML as atomic__, and creating a new YAML file for every change (never updating the old ones).

This is fine, but we can make this workflow easier, by providing:

1. A first-class way to indicate that two Component YAMLs actually describe the same component:
     - For example, a `component_id` field that specifies a unique identifier for their component
2. A first-class way to indicate what version this YAML represents:
     - For example, a `component_version` field that specifies the version of the component

### Example:

These examples show two "versions" of the same component.

```yaml
name: My Component
description: ""

component_id: example.com/my-component
component_version: 1.0.0

inputs:
  - ...
outputs:
  - ...
implementation:
  ...
```

```yaml
name: My Component
description: ""

component_id: example.com/my-component
component_version: 2.0.0

inputs:
  - ...
outputs:
  - ...
implementation:
  ...
```

### Other Comments:

I am aware that some components [use an annotation called `cannonical_location`](https://github.com/kubeflow/pipelines/blob/340318625c527836af1c9abc0fd0d76c0a466333/components/contrib/git/clone/component.yaml#L6) to uniquely idenfiy components.

However, I think adding id/version as a first-class part of the spec will provide many benefits, including the possibility of building proper "catalogs" of KFP components (which the Python SDK can be natively aware of).

Related to https://github.com/kubeflow/pipelines/issues/1025 (from 2019)

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.
