### ISSUE TITLE
[sdk] The component method .after() not working properly with multiple components from the same spec.yaml file

### ISSUE THREAD

**Issue by msvensson222** [kubeflow/pipelines#7947]
### Environment

*  KFP SDK version: 
2.0.0a5

### Purpose
I am trying to build and run a pipeline using a reusable component, leveraging an image hosted in Google Container Registry, a `component-spec.yaml` file as well as the `load_component_from_file()` function. The pipeline consists of three components, where the first two should be executed independently (and loaded from the same reusable file), and the third one should be executed after the two first have been completed.

For context, this component takes as input argument a tablename (which exists in our data warehouse (DWH)), and dumps it in a Google Cloud Storage Bucket (GCS). Because of this, having it as a reusable component is very convenient.

### Steps to reproduce
I define a pipeline as such:
```python
from kfp import dsl, compiler
from kfp.components import load_component_from_file


@dsl.pipeline(
    name='my-pipeline',
    description='Pipeline with a reusable component',
    pipeline_root='gs://my-bucket/pipeline'
)
def pipeline(
        tablename_1: str = 'table1',
        tablename_2: str = 'table2',
        some_file_path: str = 'gs://my-bucket/some_folder/'
):
    # Snowflake queries and dump data
    dwh_to_gcs_0 = load_component_from_file("dwh-to-gcs.yaml")
    dwh_to_gcs_0(
        tablename=tablename_1
    )
    dwh_to_gcs_1 = load_component_from_file("dwh-to-gcs.yaml")
    dwh_to_gcs_1(
        tablename=tablename_2
    )

    final_component = load_component_from_file("final-component.yaml")
    final_component(
        file_path=some_file_path
    ) \
        .after(dwh_to_gcs_0) \
        .after(dwh_to_gcs_1)


if __name__ == '__main__':
    compiler.Compiler().compile(
        pipeline_func=pipeline,
        package_path="./pipeline.json"
    )
```
With the following component specification yaml-files:
`dwh-to-gcs.yaml` ("Reusable"):
```yaml
name: DWHtoGCS
description: Dumps a table in the DWH as a csv-file into GS.
inputs:
  - {name: tablename, type: String}
implementation:
  container:
    image: eu.gcr.io/my-project/my-image:latest
    command: [
      python3, main.py,
      --tablename, {inputValue: tablename}
    ]
```
and `final-component.yaml`:
```yaml
name: FinalComponent
description: Makes some computations from some files.
inputs:
  - {name: file_path, type: String}
implementation:
  container:
    image: eu.gcr.io/my-project/my-image:latest
    command: [
      python3, main.py,
      --file_path, {inputValue: file_path}
    ]
```
When compiling the pipeline, by running `python3 pipeline.py`, I get the following `pipeline.json` file:
```json
{
  "components": {
    "comp-dwhtogcs": {
      "executorLabel": "exec-dwhtogcs",
      "inputDefinitions": {
        "parameters": {
          "tablename": {
            "parameterType": "STRING"
          }
        }
      }
    },
    "comp-dwhtogcs-2": {
      "executorLabel": "exec-dwhtogcs-2",
      "inputDefinitions": {
        "parameters": {
          "tablename": {
            "parameterType": "STRING"
          }
        }
      }
    },
    "comp-finalcomponent": {
      "executorLabel": "exec-finalcomponent",
      "inputDefinitions": {
        "parameters": {
          "file_path": {
            "parameterType": "STRING"
          }
        }
      }
    }
  },
  "defaultPipelineRoot": "gs://my-bucket/pipeline",
  "deploymentSpec": {
    "executors": {
      "exec-dwhtogcs": {
        "container": {
          "command": [
            "python3",
            "main.py",
            "--tablename",
            "{{$.inputs.parameters['tablename']}}"
          ],
          "image": "eu.gcr.io/my-project/my-image:latest"
        }
      },
      "exec-dwhtogcs-2": {
        "container": {
          "command": [
            "python3",
            "main.py",
            "--tablename",
            "{{$.inputs.parameters['tablename']}}"
          ],
          "image": "eu.gcr.io/my-project/my-image:latest"
        }
      },
      "exec-finalcomponent": {
        "container": {
          "command": [
            "python3",
            "main.py",
            "--file_path",
            "{{$.inputs.parameters['file_path']}}"
          ],
          "image": "eu.gcr.io/my-project/my-image:latest"
        }
      }
    }
  },
  "pipelineInfo": {
    "name": "my-pipeline"
  },
  "root": {
    "dag": {
      "tasks": {
        "dwhtogcs": {
          "cachingOptions": {
            "enableCache": true
          },
          "componentRef": {
            "name": "comp-dwhtogcs"
          },
          "inputs": {
            "parameters": {
              "tablename": {
                "componentInputParameter": "tablename_1"
              }
            }
          },
          "taskInfo": {
            "name": "dwhtogcs"
          }
        },
        "dwhtogcs-2": {
          "cachingOptions": {
            "enableCache": true
          },
          "componentRef": {
            "name": "comp-dwhtogcs-2"
          },
          "inputs": {
            "parameters": {
              "tablename": {
                "componentInputParameter": "tablename_2"
              }
            }
          },
          "taskInfo": {
            "name": "dwhtogcs-2"
          }
        },
        "finalcomponent": {
          "cachingOptions": {
            "enableCache": true
          },
          "componentRef": {
            "name": "comp-finalcomponent"
          },
          "dependentTasks": [
            "dwhtogcs"
          ],
          "inputs": {
            "parameters": {
              "file_path": {
                "componentInputParameter": "some_file_path"
              }
            }
          },
          "taskInfo": {
            "name": "finalcomponent"
          }
        }
      }
    },
    "inputDefinitions": {
      "parameters": {
        "some_file_path": {
          "defaultValue": "gs://my-bucket/some_folder/",
          "parameterType": "STRING"
        },
        "tablename_1": {
          "defaultValue": "table1",
          "parameterType": "STRING"
        },
        "tablename_2": {
          "defaultValue": "table2",
          "parameterType": "STRING"
        }
      }
    }
  },
  "schemaVersion": "2.1.0",
  "sdkVersion": "kfp-2.0.0-alpha.5"
}
```
Within this pipeline definition, note that the final component only has **one** dependant task:
```yaml
...
"finalcomponent": {
          "cachingOptions": {
            "enableCache": true
          },
          "componentRef": {
            "name": "comp-finalcomponent"
          },
          "dependentTasks": [
            "dwhtogcs"
          ],
          "inputs": {
            "parameters": {
              "file_path": {
                "componentInputParameter": "some_file_path"
              }
            }
          },
          "taskInfo": {
            "name": "finalcomponent"
          }
        }
...
```
### Expected result

To clarify further, I specify in my `pipeline.py` file that the final component should be after **BOTH** previous steps;
```python
    final_component(
        file_path=some_file_path
    ) \
        .after(dwh_to_gcs_0) \
        .after(dwh_to_gcs_1)
```
I expect that to be reflected in the pipeline.json definition, but there, only **ONE** is listed (the name (lower-case) of the reusable component);
```yaml
"dependentTasks": [
            "dwhtogcs"
          ],
```

Moreover, to verify that the pipeline is also behaving this way if executed, I submitted it to Vertex AI, where it also displays the same behaviour.

**Is this a bug, or am I somehow using the SDK in a non-ideal way?**

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
