### ISSUE TITLE
[question] How does `importer` work under the hood?

### ISSUE THREAD

**Issue by deepyaman** [kubeflow/pipelines#8067]
I'm trying to find/understand the underlying Argo YAML for an `importer`. Is https://github.com/kubeflow/pipelines/blob/3e734ed19146f569e910f75627d12239ec2e86dc/backend/src/v2/compiler/argocompiler/testdata/importer.yaml the right place to look (for an example, of how https://github.com/kubeflow/pipelines/blob/c6125ffc44df0eced27ae83451c6243b8fc8d73f/sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_importer.py gets converted)? If so, where is the logic to actually download the artifact from Google Cloud Storage? I feel like, looking at definitions for importer nodes and importer specs, I'm not able to trace back to the place where the downloading is actually happening.

My current thought is it's happening on some `kfp-launcher` Docker image, but I'm not sure if that's right, and--even if so--I would like to be able to see the underlying logic getting called.

edit: I've looked into this more over the past few days, and I've understood that:

1. [The `artifactUri` is extracted from the `ImporterSpec` and returned from `ImportSpecToMLMDArtifact`](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/importer_launcher.go#L191-L207).
2. [Find and return a matched artifact (if any)](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/importer_launcher.go#L159-L164). Is the implementation of finding the matched artifact dependent on the execution backend? I got a bit lost trying to trace back in there.
3. [Execute](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/importer_launcher.go#L143-L145).

I'm still not sure, for example, if you have an `importer` like https://github.com/kubeflow/pipelines/blob/c6125ffc44df0eced27ae83451c6243b8fc8d73f/sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_importer.py#L55-L59

* How does it know how to download an artifact from `gs://` vs `s3://` vs `http://`, etc.? I'm sure there must be some logic to determine protocol, etc., but it's happening somewhere I can't identify.
* Is there a reasonable approximation in Argo? Maybe something like:

```yaml
  arguments:
    parameters:
    - name: raw_green_data_url
      value: https://raw.githubusercontent.com/deepyaman/azureml-examples/main/sdk/jobs/pipelines/2c_nyc_taxi_data_regression/data/greenTaxiData.csv

  templates:
  - name: nyc-taxi-data-regression
    steps:
    - - name: download-raw-green-data
        template: importer
        arguments:
          artifacts:
            - name: uri
              http:  # The artifact parameter (this line and the one below) have to be generated programmatically by parsing the URI string.
                url: "{{workflow.parameters.raw_green_data_url}}"

  - name: importer
    inputs:
      artifacts:
      - name: uri
        path: /tmp/data
    outputs:
      artifacts:
      - name: artifact
        path: /tmp/data
    container:
      image: hello-world
```
