### ISSUE TITLE
[backend] disabling task caching doesn't appear to work

### ISSUE THREAD

**Issue by ptitzler** [kubeflow/pipelines#8184]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
  ```
  $ kubectl version --short
  Client Version: v1.24.4
  Kustomize Version: v4.5.4
  Server Version: v1.20.2
  ```

   - minikube v1.18.1
   - kubernetes v1.20.2

*  KFP version: Deployed using [kubeflow/manifests v1.5.0](https://github.com/kubeflow/manifests/archive/refs/tags/v1.5.0.tar.gz)

*  KFP SDK version: 

   ```
   $ pip list | grep kfp 
   kfp                      1.8.13
   kfp-pipeline-spec        0.1.16
   kfp-server-api           1.8.4
  kfp-tekton               1.3.1
  ```

### Steps to reproduce

Create a ContainerOp and use [`set_caching_options(False)`](https://kubeflow-pipelines.readthedocs.io/en/1.8.13/source/kfp.dsl.html#kfp.dsl.ContainerOp.set_caching_options) to disable task caching

```
from kfp import dsl
from kfp.compiler import Compiler

@dsl.pipeline(name='ContainerOp caching test', description='')
def pipeline():
  co = dsl.ContainerOp(
    name='sample ContainerOp',
    image='busybox',
    command=['echo', 'Hello KFP!'],
  )

  co.set_caching_options(False)

if __name__ == '__main__':
    Compiler().compile(pipeline, __file__ + '.yaml')
```

Compile the pipeline. The compiled pipeline looks as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: containerop-caching-test-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.13, pipelines.kubeflow.org/pipeline_compilation_time: '2022-08-23T08:20:01.620863',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "ContainerOp caching test"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.13}
spec:
  entrypoint: containerop-caching-test
  templates:
  - name: containerop-caching-test
    dag:
      tasks:
      - {name: sample-containerop, template: sample-containerop}
  - name: sample-containerop
    container:
      command: [echo, Hello KFP!]
      image: busybox
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.13
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "false"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
```

Run the pipeline multiple times and review the run info in the Central Dashboard.

![image](https://user-images.githubusercontent.com/13068832/186090182-846f6837-af23-4e2b-a1c8-3cc743ebf0db.png)

fwiw the following labels are defined on the pod:
```
Labels:       pipeline/runid=40313ed7-32c0-4d01-9588-7c1f033b1b14
              pipelines.kubeflow.org/cache_enabled=true
              pipelines.kubeflow.org/cache_id=813
              pipelines.kubeflow.org/enable_caching=false
              pipelines.kubeflow.org/kfp_sdk_version=1.8.13
              pipelines.kubeflow.org/metadata_execution_id=28
              pipelines.kubeflow.org/metadata_written=true
              pipelines.kubeflow.org/pipeline-sdk-type=kfp
              pipelines.kubeflow.org/reused_from_cache=true
              workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=lambda-4mk5p
```

Note `pipelines.kubeflow.org/cache_enabled=true` and `pipelines.kubeflow.org/enable_caching=false`

### Expected result

Task results are not re-used across multiple pipeline runs. Not sure what (if anything) I am missing. Disabling caching for entire pipelines or the entire KFP deployment is not a viable option since the caching requirements vary. Please advise. Thank you!

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
