### ISSUE TITLE
[bug] visualization keep showing nothing ?

### ISSUE THREAD

**Issue by TranThanh96** [kubeflow/pipelines#8348]
### Environment

Kubeflow 1.6 on AWS

### Steps to reproduce
my code:
```
import argparse
import json
from pathlib import Path
from collections import namedtuple


def main(args):
    metadata = {
        'outputs' : [{
        'type': 'web-app',
        'storage': 'inline',
        'source': '<h1>Hello, World!</h1>',
        }]
    }
    print('>> meta data: ', metadata)
    output = namedtuple('HelloWorldOutput', ['echo', 'mlpipeline_ui_metadata'])
    # return output(name + ': Hello, Wolrd!', json.dumps(metadata))

    Path(args.mlpipeline_ui_metadata_path).parent.mkdir(parents=True, exist_ok=True)
    with open(args.mlpipeline_ui_metadata_path, 'w') as metadata_file:
        json.dump(metadata, metadata_file)

    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Argparse for com 1')
    parser.add_argument('--mlpipeline_ui_metadata_path', type=str, help='mlpipeline_ui_metadata_path, log output ')
    args = parser.parse_args()
    main(args)
    
```

my component:

```
name: download data
description: download data from s3 bucket
metadata:
  annotations:
    author: ThanhTM

outputs:
  - {name: mlpipeline_ui_metadata_path, type: String, description: 'mlpipeline_ui_metadata_path visualize'} 

implementation:
  container:
    image: 80************03.dkr.ecr.us-east-1.amazonaws.com/cnndha@sha256:dc54c86e43ac49d3a543c3c0df725c715abfa4e06c928d449537c3454eb25de9
    command: [python3, /pipelines/component/src/main.py]
    args: [
      --mlpipeline_ui_metadata_path, {outputPath: mlpipeline_ui_metadata_path}
    ]
```
my code create pipeline:
```
visual_component = kfp.components.load_component_from_file('component.yaml')

@kfp.dsl.pipeline(
    name="demo pipeline",
    description="hi"
)
def my_pipeline(
):

    
    download_data_step = visual_component()

arguments = {}
client.create_run_from_pipeline_func(my_pipeline, arguments=arguments)
```
and my result:
![image](https://user-images.githubusercontent.com/26323599/195058505-beaada91-99e6-4b1c-a60c-dd63bcba94f3.png)
