### ISSUE TITLE
[bug] component pull image from docker local registry

### ISSUE THREAD

**Issue by TranThanh96** [kubeflow/pipelines#8396]
I am using kubeflow deploy on k3AI.
I have a local docker registry on ip: 1.2.3.4
then I create a component and push into 1.2.3.4/hello-world:v0.0.1
I have a pipeline that uses the component above:
```
name: hello world
description: hello world
metadata:
  annotations:
    author: ThanhTM

inputs:
  - {name: input, type: String, description: 'data'}


implementation:
  container:
    image: 1.2.3.4/hello-world:v0.0.1
    command: [python3, /pipelines/component/src/main.py]
    args: [
      --input, {inputValue: data_uri_s3}, # input
    ]
```

but error keep happening:
This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image "1.2.3.4/hello-world:v0.0.1"

Any tutorial to tackle this issue? thank you
