### ISSUE TITLE
[sdk] Component parameters with a default value of `None` are incorrectly interpreted as required when compiling to yaml

### ISSUE THREAD

**Issue by suned** [kubeflow/pipelines#8558]
### Environment

*  KFP version: 2.0.0b8

*  KFP SDK version: 2.0.0b8

*  All dependencies version:
    * kfp                              2.0.0b8
    * kfp-pipeline-spec                0.1.16
    * kfp-server-api                   2.0.0a6

### Steps to reproduce

Example:

```python
from typing import Optional

from kfp.dsl import component
from kfp.compiler import Compiler

@component
def example(optional_param: Optional[str] = None):
    pass

Compiler().compile(example, 'example.yaml')
```

Output:
```yaml
# example.yaml

components:
  comp-example:
    executorLabel: exec-example
    inputDefinitions:
      parameters:
        optional_param:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-example:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - example
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.0-beta.8'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef example(optional_param: Optional[str] = None):\n    pass\n\n"
        image: python:3.7
pipelineInfo:
  name: example
root:
  dag:
    tasks:
      example:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-example
        inputs:
          parameters:
            optional_param:
              componentInputParameter: optional_param
        taskInfo:
          name: example
  inputDefinitions:
    parameters:
      optional_param:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.0-beta.8
```

### Expected result

`optional_param` in the above example should have a default value under the `defaultValue` key in the output yaml.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
