### ISSUE TITLE
[backend] Cache Server referencing the wrong file in secret webhook-server-tls

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/pipelines#8565]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? 

KFP was deployed via Manifests with Kubeflow v1.6.1 onto K8S 1.24.8 on baremetal with Ubuntu 22.04 host OS.

*  KFP version: 

See the below problem description for info on what images were used

*  KFP SDK version: 

See the below problem description.

### Steps to reproduce

```
  git clone https://github.com/kubeflow/manifests.git
  pushd manifests
  git checkout tags/v1.6.1
  export CD_REGISTRATION_FLOW=true

  while ! ../kustomize build example | kubectl $APPLY -f -; do echo "Retrying to $APPLY resources"; sleep 10; done
  
  git switch -
```

CacheServer (Server Pod) fails to execute properly.  See the logs:
```
2022/12/12 17:19:41 Initing client manager....
2022/12/12 17:19:41 Database created
2022/12/12 17:19:42 execution_caches
2022/12/12 17:19:42 open /etc/webhook/certs/cert.pem: no such file or directory
```

The file in question should be served up via a volume mount:
```
spec:
  containers:
    - name: server
      image: gcr.io/ml-pipeline/cache-server:2.0.0-alpha.5
      args:
        - '--db_driver=$(DBCONFIG_DRIVER)'
        - '--db_host=$(DBCONFIG_HOST_NAME)'
        - '--db_port=$(DBCONFIG_PORT)'
        - '--db_name=$(DBCONFIG_DB_NAME)'
        - '--db_user=$(DBCONFIG_USER)'
        - '--db_password=$(DBCONFIG_PASSWORD)'
        - '--namespace_to_watch=$(NAMESPACE_TO_WATCH)'
      volumeMounts:
        - name: webhook-tls-certs
          readOnly: true
          mountPath: /etc/webhook/certs
  volumes:
    - name: webhook-tls-certs
      secret:
        secretName: webhook-server-tls
        defaultMode: 420
```

Secret webhook-server-tls:
```
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: kubeflow
type: kubernetes.io/tls
data:
  ca.crt: <hidden>
  tls.crt: <hidden>
  tls.key: <hidden>
```

As you can see, there is no `cert.pem` file

### Expected result

The correct behavior should be that the Cache Server is properly configured to consume the TLS certificate resources that its configured to consume.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
