### ISSUE TITLE
[sdk] No longer possible to compile components that use `PipelineTaskFinalStatus`

### ISSUE THREAD

**Issue by suned** [kubeflow/pipelines#8649]
### Environment

*  KFP version: N/A

*  KFP SDK version: 2.0.0b10

*  All dependencies version:

```
kfp                      2.0.0b10
kfp-pipeline-spec        0.1.17
kfp-server-api           2.0.0a6
```

### Steps to reproduce

In version 1.x.x it was possible to compile components that uses `PipelineTaskFinalStatus`, e.g using:

```python
from kfp.v2.dsl import component, PipelineTaskFinalStatus, pipeline, ExitHandler
from kfp.components import load_component_from_file


@component(output_component_file='example.yaml')
def example(status: PipelineTaskFinalStatus):
    print(status)


loaded_component = load_component_from_file('example.yaml')

@pipeline
def example_pipeline():
    with ExitHandler(loaded_component()):
        pass
```

In version 2.0.0bx we expected this to still be possible, e.g with

```python
from kfp.dsl import component, PipelineTaskFinalStatus, pipeline, ExitHandler
from kfp.compiler import Compiler
from kfp.components import load_component_from_file


@component
def example(status: PipelineTaskFinalStatus):
    print(status)


Compiler().compile(example, 'example.yaml')

loaded_component = load_component_from_file('example.yaml')

@pipeline
def example_pipeline():
    with ExitHandler(loaded_component()):
        pass
```

However, this is no longer possible for what seems like a variety of reasons. First of all the sdk explicitly forbids it in 

https://github.com/kubeflow/pipelines/blob/fdf3ee7b68b2293d08e14c389b0dab9a57854e2a/sdk/python/kfp/compiler/pipeline_spec_builder.py#L333-L338

I tried commenting out the above check, which does produce valid component yaml: 

```yaml
# PIPELINE DEFINITION
# Name: example
# Inputs:
#    status: dict
components:
  comp-example:
    executorLabel: exec-example
    inputDefinitions:
      parameters:
        status:
          isOptional: true
          parameterType: STRUCT
deploymentSpec:
  executors:
    exec-example:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - example
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.0-beta.10'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef example(status: PipelineTaskFinalStatus):\n    print(status)\n\
          \n"
        image: python:3.7
pipelineInfo:
  name: example
root:
  dag:
    tasks:
      example:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-example
        inputs:
          parameters:
            status:
              componentInputParameter: status
        taskInfo:
          name: example
  inputDefinitions:
    parameters:
      status:
        isOptional: true
        parameterType: STRUCT
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.0-beta.10
```

Unfortunately, the input type of the `status` parameter is converted to `STRUCT` in the process, so loading in the component yaml results in a component that fails at runtime because the `status` argument is not provided by the backend as expected.
### Expected result

It should be possible to compile components that use `PipelineTaskFinalStatus` for feature parity with version 1.x.x

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
