### ISSUE TITLE
[bug] 1.6 manifests with systemd MinIO configured (improperly)| /tmp/outputs/Output/data: no such file or directory

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8782]
@chensun  I spun off this new issue related to `/tmp/outputs/Output/data: no such file or directory`

![image](https://user-images.githubusercontent.com/4308024/214195224-97f16a56-0f6d-4034-bc56-b656da247507.png)

_Originally posted by @MatthewRalston in https://github.com/kubeflow/pipelines/issues/8683#issuecomment-1401289909_

**Comment by chensun** [comment]
Hi @MatthewRalston , you need to create parent directories for the output path, before you can write the data. See example: https://github.com/kubeflow/pipelines/blob/61a6172e7d88e21ee90af8b3ecf63b0224b8172c/sdk/python/test_data/pipelines/pipeline_with_outputs.py#L36

**Comment by MatthewRalston** [comment]
@chensun that's a nice example, and thank you so much, but it doesn't alone solve this issue for users!

Specifically, the developer should suggest documentation pages! Examples of this behavior elsewhere! Where in the documentation does it connect the filename, the component's OutputPath returned, how that name gets acquired, and why/where the user needs to specify, instead of Kubeflow, the output directory path and then the user has to make it themselves????


This isn't remotely solved!

**Comment by MatthewRalston** [comment]
Still really confused about this. This seems confusing that Kubeflow doesn't manage files on its own. Is this a syntax issue, or is my Kubeflow instance malformed?

@chensun can you maybe tag someone from the Manifests group to review this configuration?


Minikube, kustomize, minio

    minikube 1.28.0
    kustomize 3.2.0
    kubernetes/kubectl 1.22.2
    docker 20.10.21
    containerd v1.6.10


```bash
>kustomize version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T16:26:36Z GoOs:linux GoArch:amd64}
>minio --version
minio version RELEASE.2023-01-20T02-05-44Z (commit-id=0f591d245d3a1810b0e6aebbf3f32937227f68f8)
Runtime: go1.19.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-0000 MinIO, Inc.
>minikube addons enable istio
>istioctl install --set revision=canary
>minikube kubectl -- create -f config/profile.yaml
```

* `config/profile.yaml`

```yaml

  resourceQuotaSpec:    # resource quota can be set optionally
   hard:
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
    name: user
spec:
    owner:
        kind: User
        name: email@example.org
    recourceQuotaSpec:
        hard:
            cpu: "3000m"
           memory: 100Gi
           pods: "24"
           requests.nvidia.com/gpu: "1"
           persistentvolumeclaims: "1"
           requests.storage: "200Gi"
     
```


Then, I do various obvious port-forwarding routines locally to expose the Kubeflow dashboard.


After starting vanilla minikube, I apply the 1.6.1 Kubeflow/manifests to the cluster as per instructions.

Do I need to adjust something in my configuration, or is this, as @chensun suggests, simply a v1.8 syntax issue requiring me to create directories for output files to somehow be managed by kubeflow?
