### ISSUE TITLE
[bug] 1.6 Kubeflow manifests produces| /tmp/outputs/Output/data: no such file or directory. v1.8 decompression/gzip example.

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8868]
### Environment

Minikube v1.28.0
kubernetes 1.22.2
Kustomize v3.2.0
kubectl v1.25.5
Manifests v1.6.1

    KFP SDK version:

    All dependencies version:

kfp 2.0.0b9
kfp-pipeline-spec 0.1.16
kfp-server-api 2.0.0a6

### Steps to reproduce

From arch Linux

```bash
yay -S minikube docker containerd minio
```

* `/etc/docker/daemon.json`
```json
{
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
	"max-size": "100m"
    },
    "data-root": "/var/lib/docker",
    "storage-driver": "overlay2",
    "rootless": false
}
```

* Default configurations otherwise, except Minio service paths/users

1. Launch minikube
2. Enable istio
3. `istioctl install --set revision=canary`
4. Use Kustomize to install Kubeflow 1.6 manifests
5. Port-fowarding 
6. Use Kubeflow/pipelines dashboard to invoke a python kfp pipeline.

* `components/gunzip.yaml`
```yaml
name: gunzip
description: Gunzips an Input file to an Ouput filepath
inputs:
- {name: infile, type: String, description: 'Data for gzip decompression'}
outputs:
- {name: Output, type: String, description: 'Output decompressed plaintext'}
implementation:
  container:
    image: alpine:latest
    # command is a list of strings (command-line arguments). 
    # The YAML language has two syntaxes for lists and you can use either of them. 
    # Here we use the "flow syntax" - comma-separated strings inside square brackets.
    command: [
    sh,
    -c,
    zcat,
    {inputPath: infile},
    '>',
    {outputPath: Output}
    ]

```

* `pipeline.py`
```python
#!/bin/env python

import os
import sys
import argparse

from pathlib import Path
import gzip

import kfp.dsl as dsl
import kfp.components as comp
import kfp


components_dir = os.path.join(os.path.dirname(__file__), "components")

gunzip = comp.load_component_from_file(os.path.join(components_dir, "gunzip.yaml"))
echo = comp.load_component_from_file(os.path.join(components_dir, "echo.yaml"))

is_unzip_needed = comp.load_component_from_file(os.path.join(components_dir, "is_unzip_needed.yaml"))



@dsl.pipeline(
    name='kubeflow-barebone-demo',
    description='kubeflow demo with minimal setup'
)
def rnaseq_pipeline(fastq1:str):
    #Path(str(decompressed_fastq1)).parent.mkdir(parents=True, exist_ok=True)

    gunzip1 = gunzip(infile=fastq1).set_cpu_request('1').set_cpu_limit('1').set_memory_request('512Mi').set_memory_limit('512Mi')

        


if __name__ == "__main__":
    logger = get_root_logger(2)
    
    kfp.compiler.Compiler().compile(rnaseq_pipeline, 'pipeline.yaml')


```

### Expected result

Expected behavior should be that Kubeflow + manifests handles the creation of output `tmp` directories. I did not get an appropriate answer from [issue](https://github.com/kubeflow/pipelines/issues/8782). Either the requirement for users to create their own directories (as @chensun suggested) should be a documented *feature* of Kubeflow, or the correct way to handle file outputs with MinIO should be well documented. I'm a fairly tech savvy average user of Kubeflow, and with about 8+ hours in the documentation, I'm running into a crippling bug for my small business. Namely, the correct way to pass data from one step to antother, saving the output in the `/tmp/Output/output` directory. If that's where Kubeflow wants to put output datasets:

* why can't it also manage the creation of such a directory?
*  Is this a kubeflow or manifests issue?
* What would be the proper way to produce/retrieve kfp outputs using 1.8 kfp syntax?

### Materials and reference

![Screenshot from 2023-01-28 10-33-36](https://user-images.githubusercontent.com/4308024/219900360-a637789d-4040-4799-9fa7-967b05ea4c2f.png)

### Labels

/area backend
/area sdk
/area testing

/area component

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
> Either the requirement for users to create their own directories (as @chensun suggested) should be a documented feature of Kubeflow, or the correct way to handle file outputs with MinIO should be well documented.

Agree that we could have done a better job on documentation, but the need of `mkdir` was indeed show cased in the [documentation](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/component-development/) as well as [numerous component samples](https://github.com/kubeflow/pipelines/search?q=%22mkdir+-p%22).
(Note: above is for KFP v1, v2 has a different syntax I'll explain shortly)

> why can't it also manage the creation of such a directory?

This is by design for KFP v1, while I don't know the full history or limitation, my understanding is a component that runs as a container is fully responsible for the file i/o happened within the container, the orchestration engine (Argo) only picks up artifacts and persists them in object store (Minio) post execution. 

> Is this a kubeflow or manifests issue?

Neither, (as explained above)

> What would be the proper way to produce/retrieve kfp outputs using 1.8 kfp syntax?

Assuming you refer to KFP SDK 1.8 and import from `kfp` namespace (instead of `kfp.v2` namespace), user code needs to make directories of output paths. 
If you're importing from `kfp.v2` namespace in KFP SDK 1.8, or if you are using KFP SDK 2.0, for Python-function component (created via `@component` decorator), you don't need to make directories--that's handled by our injected executor code that runs in the same container prior to the execution of user code. For more details about v2 syntax, please check: https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/component-io/

Hope this clarifies.

**Comment by MatthewRalston** [comment]
Thank you, this clarifies quite a bit. I will visit this during the week and close if I cannot manage the syntax issues between v1.8 (which I am using) or the v2 SDK.

**Comment by MatthewRalston** [comment]
First of all @chensun , I noticed that the documentation needs revision. Here is my minimal example:


https://www.kubeflow.org/docs/components/pipelines/v1/sdk/component-development/
Straight from the documentation:

```
def gunzip_func(ifile, ofile):
    for line in ifile:
        ofile.write(line)

    logger.info("Decompression completed...")

    return





@dsl.pipeline(
    name='kubeflow-barebone-demo',
    description='kubeflow demo with minimal setup'
)
def rnaseq_pipeline(fastq1:str, decompressed_fastq1:str):
    Path(str(decompressed_fastq1)).parent.mkdir(parents=True, exist_ok=True)


    with gzip.open(fastq1) as ifile:
        with open(decompressed_fastq1, 'w') as ofile:
            gunzip_func(ifile, ofile)

if __name__ == "__main__":
    logger = get_root_logger(2)
    
    kfp.compiler.Compiler().compile(rnaseq_pipeline, 'pipeline.yaml')

```




```
Traceback (most recent call last):
  File "./pipeline.py", line 73, in <module>
    kfp.compiler.Compiler().compile(rnaseq_pipeline, 'pipeline.yaml')
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1178, in compile
    package_path=package_path)
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1229, in _create_and_write_workflow
    pipeline_conf)
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1005, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "./pipeline.py", line 62, in rnaseq_pipeline
    with gzip.open(fastq1) as ifile:
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/gzip.py", line 57, in open
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file
```

**Comment by MatthewRalston** [comment]
It seems like the example produces a wrapper (PipelineParam), which I'm assuming implements its own `open` interface). This is not compatible with gzip. No matter what I try, I cannot use either Python or the following container interface to decompress a file. 

```yaml
name: gunzip
description: Gunzips an Input file to an Ouput filepath
inputs:
- {name: infile, type: String, description: 'Data for gzip decompression'}
outputs:
- {name: Output, type: String, description: 'Output decompressed plaintext'}
implementation:
  container:
    image: alpine:latest
    # command is a list of strings (command-line arguments). 
    # The YAML language has two syntaxes for lists and you can use either of them. 
    # Here we use the "flow syntax" - comma-separated strings inside square brackets.
    command: [
    sh,
    -c,
    mkdir,
    --parents,
    '$(dirname ',
    {outputPath: Output},
    ')',
    '&&',
    zcat,
    {inputPath: infile},
    '>',
    {outputPath: Output}
    ]
```


AGAIN the real issue is that kfp, as you stated above, requires the following directory to be created *INDEPENEDENTLY OF THE DATASET HANDLING*. It's a smell.

```
/tmp/outputs/Output/
```

As you can see, the directory should be created in the container code above, but it fails with the following:

```
time="2023-03-01T14:41:04.951Z" level=error msg="cannot save artifact /tmp/outputs/Output/data" argo=true error="stat /tmp/outputs/Output/data: no such file or directory"
```

Instead it fails *before* the zcat command on the mkdir command. THe mkdir command :


```yaml
    'mkdir -p $(dirname ',
    {outputPath: Output}
    ')'
```
```


Here is the containerspec from the logs
```
 {"description": "Gunzips an Input file to an Ouput filepath",
      "implementation": {"container": {"command": ["sh", "-c", "echo 'mkdir
      --parents \\$(dirname $output) && zcat $input '", {"outputPath":
      "Output"}, "&&", "mkdir --parents '$(dirname '", {"outputPath": "Output"},
      ")", "&&", "zcat", {"inputPath": "infile"}, ">", {"outputPath":
      "Output"}], "image": "alpine:latest"}}, "inputs": [{"description": "Data
      for gzip decompression", "name": "infile", "type": "String"}], "name":
      "gunzip", "outputs": [{"description": "Output decompressed plaintext",
      "name": "Output", "type": "String"}]}
```
