### ISSUE TITLE
[sdk] Fail running Containerized Python components from kfp v2.0.0.b12 on Vertex

### ISSUE THREAD

**Issue by anifort** [kubeflow/pipelines#8883]
### Environment

*  KFP version: Running on Vertex

*  KFP SDK version: 
kfp = 2.0.0b12 

*  All dependencies version:
kfp = 2.0.0b12 \
kfp-pipeline-spec = 0.2.0 \
kfp-server-api = 2.0.0a6

### Steps to reproduce
create a simple component and decorate with vertex ai artifact registry uri, for example:
```
@component(
    base_image='python:3.7',
    target_image="us-central1-docker.pkg.dev/PROJECT_ID/REPO_NAME/COMPONENT_NAME:latest",
    packages_to_install=[]
    
)
```
run command to upload component container:

`kfp component build PATH_TO_COMPONENT --component-filepattern my_component.py --build-image --push-image --overwrite-dockerfile`

Load component as a pipeline operator 
`component_op = components.load_component_from_file('PATH_TO_COMPONENT_CONFIG.yaml')`

 run pipeline on Google cloud Vertex AI

### Error returned: 
component execution fails during setup with error : 
`exec /bin/sh: exec format error`

This error seems related to the component_config,yaml that is generated and points to the container commands that are executed:
```
deploymentSpec:
  executors:
    .....:
      container:
        args:
        - ...
        - ...
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'google-cloud-aiplatform==1.22.0'\
          \ && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.components.executor_main
        
```

### Expected result
execut component successfully 

### Materials and Reference
N/A
---

Impacted by this bug? Give it a 👍.
