### ISSUE TITLE
[sdk] One can't set environment on v2 YamlComponent

### ISSUE THREAD

**Issue by rodrigocaus** [kubeflow/pipelines#9005]
### Environment
*  Python Version: 3.10.6
*  PIP Version: 22.3.1 (with Pipenv 2022.12.19)
*  KFP version: kfp 2.0.0b12

*  KFP SDK version: kfp 2.0.0b12

*  All dependencies version:

```
kfp                              2.0.0b12
kfp-pipeline-spec                0.2.0
kfp-server-api                   2.0.0a6
```

### Steps to reproduce

Given the V1 Yaml ComponentSpec:
```yaml
name: Write Lines
description: Writes text to a file.
inputs:
- {name: text, type: String}
outputs:
- {name: data, type: Data}
implementation:
  container:
    image: busybox
    command:
    - sh
    - -c
    - |
      mkdir -p "$(dirname "$1")"
      echo "$GREETING $0" > "$1"
    args:
    - {inputValue: text}
    - {outputPath: data}
    env:
      GREETING: "Hello,"
```

The generated artifact only contain the input "text" value.

### Expected result

The generated artifact should have both Environment and Input values.

### Materials and Reference

The code used to load YamlComponent:
```python
from kfp import components
yaml_component = components.load_component_from_file("filewriter.yml")
```
And the pipeline is as simple as it could be:
```python
@dsl.pipeline(
    name='filewriter-pipeline',
    pipeline_root=PIPELINE_ROOT
)
def workflow(text: str):
    filewriter_op = yaml_component(text=text)
```

Should be noticed that ComponenSpec [does create environment variables definitions](https://github.com/kubeflow/pipelines/blob/2.0.0b12/sdk/python/kfp/components/structures.py#L632) from file:
```python
...
env = {
    key:
    placeholders.maybe_convert_v1_yaml_placeholder_to_v2_placeholder(
        command, component_dict=component_dict)
    for key, command in container.get('env', {}).items()
}
container_spec = ContainerSpecImplementation.from_container_dict({
    'image': container['image'],
    'command': command,
    'args': args,
    'env': env
})
```
But ContainerSpecImplementation.from_container_dict [just ignores env existence](https://github.com/kubeflow/pipelines/blob/2.0.0b12/sdk/python/kfp/components/structures.py#L329):
```python
return ContainerSpecImplementation(
            image=container_dict['image'],
            command=container_dict.get('command'),
            args=container_dict.get('args'),
            env=None,  # can only be set on tasks
            resources=None)  # can only be set on tasks
```

Is there any reason to do so? Is there any other means to set environment in runtime?

---

Impacted by this bug? Give it a 👍.
