### ISSUE TITLE
[backend] Resource limits and requests not working in KFP v2

### ISSUE THREAD

**Issue by gkcalat** [kubeflow/pipelines#9087]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Standalone KFP from master

*  KFP SDK version: 
2.0.0-beta.13

### Steps to reproduce

1. Create a pipeline version with `.set_memory_limit(A).set_memory_request(B).set_cpu_limit(C).set_cpu_request(D)`
2. Create a run from the pipeline
3. Check the corresponding pod's `spec.requests`

### Expected result

```yaml
    resources:
      limits:
        cpu: C
        memory: A
      requests:
        cpu: D
        memory: B
```

### Materials and Reference

```yaml
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 32Mi
```

The values are hardcoded and do not depend on what we set as `A`, `B`, `C`, and `D`.

They seem to come from `workflow-controller-configmap`. The change was probably introduced in #5695.

---

Impacted by this bug? Give it a 👍.
