### ISSUE TITLE
[sdk] Bug when trying to iterate a list of dictionaries with ParallelFor

### ISSUE THREAD

**Issue by lucasvbalves** [kubeflow/pipelines#9366]
### Environment

*  KFP SDK version: 
kfp==2.0.0b16
*  All dependencies version:
kfp==2.0.0b16
kfp-pipeline-spec==0.2.2
kfp-server-api==2.0.0b1

### Steps to reproduce

When running the code snippet below the following error is raised:

`kfp.components.types.type_utils.InconsistentTypeException: Incompatible argument passed to the input 'val_a' of component 'add': Argument type 'STRING' is incompatible with the input type 'NUMBER_INTEGER'`

```python
@dsl.component()
def add(val_a: int, val_b: int) -> int:
    return val_a + val_b


@dsl.pipeline()
def model_training_pipeline() -> None:
    with dsl.ParallelFor(
        items=[{"a": 1, "b": 10}, {"a": 2, "b": 20}], parallelism=1
    ) as item:
        task = add(val_a=item.a, val_b=item.b)


compiler.Compiler().compile(
    pipeline_func=model_training_pipeline, package_path="/app/pipeline.yaml"
)
```

### Expected result

According to the [ParallelFor documentation](https://kubeflow-pipelines.readthedocs.io/en/2.0.0b16/source/dsl.html#kfp.dsl.ParallelFor), the code sample above should compile without errors. The `add` component should receive the values of the dictionaries as integer arguments.

### Materials and Reference

The code snippet below is a modification of the code snippet above, changing the `add` component to accept string arguments. 

```python
@dsl.component()
def add(val_a: str, val_b: str) -> int:
    return int(val_a) + int(val_b)


@dsl.pipeline()
def model_training_pipeline() -> None:
    with dsl.ParallelFor(
        items=[{"a": 1, "b": 10}, {"a": 2, "b": 20}], parallelism=1
    ) as item:
        task = add(val_a=item.a, val_b=item.b)


compiler.Compiler().compile(
    pipeline_func=model_training_pipeline, package_path="/app/pipeline.yaml"
)
```

The pipeline compiles without errors with this modification, however it fails to run in Google Vertex Pipelines. The `add` component doesn't even run and throws the following error in the UI:

`Failed to evaluate the expression with error: INVALID_ARGUMENT: Failed to parseJson from string.; Failed to evaluate the parameter_expression_selector.`

As the component's code is not even executed, it seems that the problem occurs when executing the DAG.

Here is the content of the `pipeline.yaml` that was compiled.

```yaml
# PIPELINE DEFINITION
# Name: model-training-pipeline
components:
  comp-add:
    executorLabel: exec-add
    inputDefinitions:
      parameters:
        val_a:
          parameterType: STRING
        val_b:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_INTEGER
  comp-for-loop-2:
    dag:
      tasks:
        add:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-add
          inputs:
            parameters:
              val_a:
                componentInputParameter: pipelinechannel--loop-item-param-1
                parameterExpressionSelector: parseJson(string_value)["a"]
              val_b:
                componentInputParameter: pipelinechannel--loop-item-param-1
                parameterExpressionSelector: parseJson(string_value)["b"]
          taskInfo:
            name: add
    inputDefinitions:
      parameters:
        pipelinechannel--loop-item-param-1:
          parameterType: STRUCT
deploymentSpec:
  executors:
    exec-add:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.0-beta.16'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef add(val_a: str, val_b: str) -> int:\n    return int(val_a) +\
          \ int(val_b)\n\n"
        image: python:3.7
pipelineInfo:
  name: model-training-pipeline
root:
  dag:
    tasks:
      for-loop-2:
        componentRef:
          name: comp-for-loop-2
        iteratorPolicy:
          parallelismLimit: 1
        parameterIterator:
          itemInput: pipelinechannel--loop-item-param-1
          items:
            raw: '[{"a": 1, "b": 10}, {"a": 2, "b": 20}]'
        taskInfo:
          name: for-loop-2
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.0-beta.16

```

---

Impacted by this bug? Give it a 👍.
