### ISSUE TITLE
[frontend] Kubeflow Pipelines UI not showing pipeline input parameters

### ISSUE THREAD

**Issue by erhwenkuo** [kubeflow/pipelines#9441]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

    Use https://github.com/kubeflow/manifests to deploy kubeflow.
    
      ```bash
      git clone https://github.com/kubeflow/manifests.git
      cd manifests
      git checkout v1.7-branch
      ```
      
      Modify `manifests/apps/pipeline/upstream/base/pipeline/kustomization.yaml`:
      
      ```
      ...
      images:
        - name: gcr.io/ml-pipeline/api-server
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/persistenceagent
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/scheduledworkflow
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/frontend
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/viewer-crd-controller
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/visualization-server
          newTag: 2.0.0-rc.1
      ```
      
     Then, use one command to apply these manifest:
     
      ```bash
      while ! kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
      ```

*  KFP version: 

      version: 2.0.0-rc.1

### Steps to reproduce

1. Create sample pipeline (v2)

    ```python
    from kfp import dsl
    
    @dsl.component
    def square(x: float) -> float:
        return x ** 2
    
    @dsl.component
    def add(x: float, y: float) -> float:
        return x + y
    
    @dsl.component
    def square_root(x: float) -> float:
        return x ** .5
    
    @dsl.pipeline
    def pythagorean(a: float, b: float) -> float:
        a_sq_task = square(x=a)
        b_sq_task = square(x=b)
        sum_task = add(x=a_sq_task.output, y=b_sq_task.output)
        return square_root(x=sum_task.output).output
    
    compiler.Compiler().compile(pythagorean, 'pipeline.yaml')
    ```

2. Click "Pipelines" menu, then click "Upload pipeline"

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/f70c81ec-6163-417a-bc59-49df85db53c1)
    
3. Click "Create experiment" button and input experiment name
    
    ![image](https://github.com/kubeflow/pipelines/assets/5875719/ee41344b-c2b3-4b63-b930-9338cda72e30)

4. Configure "Start a run" (issues is here!!)

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/97f7f486-426e-4e5a-b8f8-8b204111e95d)

### Expected result

"Start a run" UI should show pipeline input parameters according to pipeline IR Yaml. However, it is showing "This pipeline has no parameters".

![image](https://github.com/kubeflow/pipelines/assets/5875719/efeea381-9ebe-4bd9-ac99-96ab1630a13f)

But, if we click "Skip this step" and click "Create run" run on Experiment UI

![image](https://github.com/kubeflow/pipelines/assets/5875719/f424be8b-a968-4feb-8d1d-dfffa8b3cedc)

The pipeline input parameters will appear on the UI (as show below)

![image](https://github.com/kubeflow/pipelines/assets/5875719/9af52e8f-79c2-413b-bf89-f13d0f374154)

Impacted by this bug? Give it a 👍.
