### ISSUE TITLE
[bug] Pipeline component input parameters has been altered from "y" to "true"

### ISSUE THREAD

**Issue by erhwenkuo** [kubeflow/pipelines#9451]
*  How did you deploy Kubeflow Pipelines (KFP)?

    Use https://github.com/kubeflow/manifests to deploy kubeflow.
    
      ```bash
      git clone https://github.com/kubeflow/manifests.git
      cd manifests
      git checkout v1.7-branch
      ```
      
      Modify `manifests/apps/pipeline/upstream/base/pipeline/kustomization.yaml`:
      
      ```
      ...
      images:
        - name: gcr.io/ml-pipeline/api-server
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/persistenceagent
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/scheduledworkflow
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/frontend
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/viewer-crd-controller
          newTag: 2.0.0-rc.1
        - name: gcr.io/ml-pipeline/visualization-server
          newTag: 2.0.0-rc.1
      ```
      
     Then, use one command to apply these manifest:
     
      ```bash
      while ! kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
      ```

*  KFP version: 

      version: 2.0.0-rc.1

*  KFP SDK version:

      version: 2.0.0-rc.1

### Steps to reproduce

1. Create two sample pipeline (v2)

    - pipeline - **pipeline-add(x,y)**

    ```python
    from kfp import dsl
    from kfp import compiler
    
    @dsl.component
    def square(x: float) -> float:
        return x ** 2
    
    @dsl.component
    def add(x: float, y: float) -> float:
        return x + y
    
    @dsl.component
    def square_root(x: float) -> float:
        return x ** .5
    
    @dsl.pipeline
    def pythagorean(a: float, b: float) -> float:
        a_sq_task = square(x=a)
        b_sq_task = square(x=b)
        sum_task = add(x=a_sq_task.output, y=b_sq_task.output)
        return square_root(x=sum_task.output).output
    
    compiler.Compiler().compile(pythagorean, 'pipeline-add(x,y).yaml')
    ```

- pipeline - **pipeline-add(x,z)**

    ```python
    from kfp import dsl
    from kfp import compiler
    
    @dsl.component
    def square(x: float) -> float:
        return x ** 2
    
    @dsl.component
    def add(x: float, z: float) -> float:
        return x + z
    
    @dsl.component
    def square_root(x: float) -> float:
        return x ** .5
    
    @dsl.pipeline
    def pythagorean(a: float, b: float) -> float:
        a_sq_task = square(x=a)
        b_sq_task = square(x=b)
        sum_task = add(x=a_sq_task.output, z=b_sq_task.output)
        return square_root(x=sum_task.output).output
    
    compiler.Compiler().compile(pythagorean, 'pipeline-add(x,z).yaml')
    ```
    Note: The key difference of these two pipelines is the input parameter's naming for **add()** component. _add(x,y)_ v.s _add(x,z)_!!

2. Click "Pipelines" menu, then click "Upload pipeline" for these two testing pipeline IR yaml

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/3a414de3-ea65-40ba-9860-2e78bb364c15)

3. Verify "Pipeline Spec" for _add(x,y)_ 

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/f731f4f4-4bcc-4afb-bd70-d42a08479af7)

    You can find at line#6, the input parameter of "y" has changed to "true" which cause the pipeline fail.

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/56af5920-7cae-4a0a-901d-216ccd5ae7a9)

    Line#227 also indicating the same situation.

    Then I try to review the IR yaml that generate by compiler "pipeline-add(x,y).yaml", and the format is correct. We can see two input parameters "x" and "y".

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/cd4b8f4e-a2e4-4dac-805e-18fac8da1791)

4. Verify "Pipeline Spec" for _add(x,z)_ 
    I am suspect what cause the issue, so the other version pipeline just change the input parameters from "y" to "z". Checking the "Pipeline Spec" and the result is the same as "pipeline-add(x,z).yaml".

    ![image](https://github.com/kubeflow/pipelines/assets/5875719/4f6e2062-5a52-45df-9235-1bc53e671fa2)

    Base on this observation, I think the pipeline api backend might be the one which alter the "y" to "true".

### Expected result

"Pipeline Spec" representation & structure shoud be identical as IR yaml.

### Materials and reference

I put two version of IR yaml as attachment.

[pipeline-add.zip](https://github.com/kubeflow/pipelines/files/11504160/pipeline-add.zip)

### Labels

/area backend

---

Impacted by this bug? Give it a 👍.
