### ISSUE TITLE
How to Apply node affinity and toleration in kubeflow components deployment?

### ISSUE THREAD

**Issue by TalhaNaeem101** [kubeflow/pipelines#9567]
Hey,
I have been using kubeflow for 3-4 months. I was using kubeflow v1.5, managed its deployment with kusotmize. 
Now, after upgrading the kubeflow version to [v1.7](https://awslabs.github.io/kubeflow-manifests/release-v1.7.0-aws-b1.0.1/docs/), as we get [terraform deployment option](https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide-terraform/) with this version. But I could not find a way to pass configuration for [node affinity ](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/)and [toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for kubeflow components.

Please help me out if there's some way to pass configuration for node affinity and tolerations to the manifests of kubeflow components.

**Comment by tClelford** [comment]
```python
from kfp import dsl
from kubernetes.client import V1Toleration

def apply_toleration(toleration: str, container_op: dsl.ContainerOp) -> None:
    container_op.add_toleration(
        V1Toleration(
            key=toleration,
            operator="Equal",
            value="true",
            effect="NoSchedule",
        )
    )

def add_node_selector(label_name: str, label_value: str, container_op: dsl.ContainerOp) -> None:
    container_op.add_node_selector_constraint(label_name=label_name, label_values=label_value)
  
```

here you go :)

**Comment by TalhaNaeem101** [comment]
Thank you for your reply!
Can you please tell me specifically in which file do I need to put this piece of code? I am using kustomize option for deployment of kubelfow v1.7. Plus I am using "rds-s3" deployment option. [[Reference](https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/#20-set-up-rds-s3-and-configure-secrets:~:text=%5BRDS%20and%20S3%5D%20Deploy%20both%20RDS%20and%20S3)]

Your quick response would be highly appreciated.
@tClelford

**Comment by tClelford** [comment]
Those are examples to demonstrate how tolerations and node selectors work in KFP rather than code you should copypaste --  apply_toleration, for example, is applying a toleration that you might not want. You should apply the tolerations and node selectors as part of your component definition.

Also, I think you'd be better off using stackoverflow or something for this sort of thing, you're much more likely to get responses

**Comment by TalhaNaeem101** [comment]
Got it, Thank you @tClelford 
But actually I am using Kustomize for deployment of whole Kubeflow components stack. And applying a patch to kustomization. Here's my patch.yaml
```apiVersion: apps/v1
kind: Not-imp 
metadata:
  name: not-important
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - kubeflow
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "kubeflow"
        effect: "NoSchedule"
````

And updated the kustomization ( `kubeflow-manifests/deployments/rds-s3/kustomization.yaml` ) file:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./base
resources:
  # Configured for AWS RDS and AWS S3

  # AWS Secret Manager
  - ../../awsconfigs/common/aws-secrets-manager
  # Kubeflow Pipelines
  - ../../awsconfigs/apps/pipeline
  # Katib
  - ../../awsconfigs/apps/katib-external-db-with-kubeflow
patches:
  - path: ./patch.yaml
    target:
      kind: Deployment
  - path: ./patch.yaml
    target:
      kind: Job
  - path: ./patch.yaml
    target:
      kind: StatefulSet
```

If anyone else can help me with this, would be quite helpful for me.
