### ISSUE TITLE
[frontend] tqdm logs not displayed correctly

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9593]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? manifests

*  KFP version: [2.0.0-rc.1](https://github.com/kubeflow/pipelines/releases/tag/2.0.0-rc.1)

### Steps to reproduce

Here is an example of kubeflow components:
```yaml
name: Example
description: Pass

implementation:
  container:
    image: python:alpine3.18
    command:
      - /bin/sh
    args:
      - "-c"
      - "pip install tqdm && seq 9999999 | tqdm --bytes | wc -l"
```

A simple pipeline
```python
from kfp.components import load_component_from_file
import kfp.dsl as dsl

example_op = load_component_from_file("example.yaml")

@dsl.pipeline
def example():
    example_op()
```
### Expected result

When fetching logs from the pod using **kubectl**, we get the following logs:

![image](https://github.com/kubeflow/pipelines/assets/42176370/3f8ef6e0-59d1-4bfa-85cc-8dbb653ceb1a)

However in the kubeflow logs tab:

![image](https://github.com/kubeflow/pipelines/assets/42176370/5fa58e86-7118-41bc-99b6-dacc13f96e09)

The logs are not returning in lines.

In the logs endpoint (`pipeline/k8s/pod/logs?podname=...`) we get:
![image](https://github.com/kubeflow/pipelines/assets/42176370/9d9bc718-a201-40ce-ae67-76ec70a7c3c6)

## Investigation

Using notepad++, we can see the differences between the ends of lines:

CR = Carriage Return (\r)
LF = Line Feed (\n)

![image](https://github.com/kubeflow/pipelines/assets/42176370/f0fe5258-b5ff-46a0-82a1-9c8ae3d55cb2)

---

Impacted by this bug? Give it a 👍.
