### ISSUE TITLE
[feature] remove hard-coded configs in KFP V2 launcher

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#9689]
### Feature Area

/area backend

## Problem

Currently, we are hardcoding a few important configs in KFP V2's launcher and cache code.
This is making it difficult for distributions to support KFP v2 in a generic way.

__Launcher - The minio credentials secret is hard-coded as `mlpipeline-minio-artifact`:__

https://github.com/kubeflow/pipelines/blob/35f750703dcf4d1073a90708375459d1491085dd/backend/src/v2/objectstore/object_store.go#L292

__Launcher - The minio credentials secret keys are hard-coded as `accesskey` and `secretkey`:__

https://github.com/kubeflow/pipelines/blob/35f750703dcf4d1073a90708375459d1491085dd/backend/src/v2/objectstore/object_store.go#L324-L325

__Launcher - The minio endpoint is hard-coded as `minio-service.kubeflow:9000`:__

https://github.com/kubeflow/pipelines/blob/35f750703dcf4d1073a90708375459d1491085dd/backend/src/v2/objectstore/object_store.go#L291

__Cache - The `ml-pipeline` endpoint is hard-coded as `ml-pipeline.kubeflow:8887`:__

https://github.com/kubeflow/pipelines/blob/35f750703dcf4d1073a90708375459d1491085dd/backend/src/v2/cacheutils/cache.go#L26

## Solution

We want to allow the above configs to be changed from their defaults, preferably on a per-namespace basis.

I propose we add these configs to the `ConfigMap/kfp-launcher` which already exists in each profile namespace to set `defaultPipelineRoot`.

 For example, a new `ConfigMap/kfp-launcher` in a profile namespace might look like this:

```yaml
data:
  defaultPipelineRoot: "minio://mlpipeline/v2/artifacts"
 
  ## minio endpoint config
  minioEndpoint: "minio.example.com:9000"
 
  ## minio auth configs
  minioAuthSecret: "mlpipeline-minio-artifact"
  minioAuthSecretAccessKeyKey: "access_key"
  minioAuthSecretAccessKeyKey: "access_key"

  ## ml pipeline endpoint config
  mlPipelineEndpoint: "ml-pipeline.kubeflow:8887"
```

The question now becomes how to propagate these configs to the `kfp-launcher` container in each workflow Pod.
I think there are two options:

- OPTION 1: have the `kfp-launcher` container read the `ConfigMap/kfp-launcher`
    - [when it executes](https://github.com/kubeflow/pipelines/blob/dbebbde2001f7d2a7372a8abfd9c5c5a0eaea2b8/backend/src/v2/component/launcher_v2.go#L132), it can pass the minio configs down as it calls [`objectstore.OpenBucket`](https://github.com/kubeflow/pipelines/blob/dbebbde2001f7d2a7372a8abfd9c5c5a0eaea2b8/backend/src/v2/component/launcher_v2.go#L163) 
    - setting `mlPipelineEndpoint` has to be done before it runs [`cacheutils.NewClient()`](https://github.com/kubeflow/pipelines/blob/dbebbde2001f7d2a7372a8abfd9c5c5a0eaea2b8/backend/src/v2/component/launcher_v2.go#L115)
- OPTION 2:  read the `ConfigMap/kfp-launcher` in [`RootDAG` at the same time as we read the `defaultPipelineRoot`](https://github.com/kubeflow/pipelines/blob/eadeb3096b9cb3d3c8495491a461154b973b4e2a/backend/src/v2/driver/driver.go#L146)
    - (this approach reduces the number of API calls to read `ConfigMap/kfp-launcher`)

## Other Thoughts

We could make this slightly more advanced to allow for "selecting" credentials based on the pipelines, because not all pipelines have to use the default [bucket_root](https://kubeflow-pipelines.readthedocs.io/en/latest/source/client.html?h=root#kfp.client.Client.run_pipeline.pipeline_root), so might need different credentials.

For example, we could extend `ConfigMap/kfp-launcher` like this:

```yaml
data:
  defaultPipelineRoot: "minio://my-bucket/v2/artifacts"

  ## minio endpoint config
  minioEndpoint: "minio.example.com:9000"

  ## ml pipeline endpoint config
  mlPipelineEndpoint: "ml-pipeline.kubeflow:8887"

  ## bucket auth configs (as a YAML string)
  bucketAuth: |
    ## list of "auth providers" for minio
    minio:

      ## specifies auth for objects under "minio://my-bucket/v2/artifacts/"
      - bucketName: "my-bucket"
        keyPrefix: "v2/artifacts/"
        authFromSecret:
          secretName: "my-secret-in-profile-namespace"
          accessKeyKey: "access_key"
          secretKeyKey: "secret_key"

    ## similar, but for s3 buckets
    s3: []

    ## similar, but for gcs buckets
    gcs: []

```

---

Love this idea? Give it a 👍.
