### ISSUE TITLE
[backend] Optional parameters to custom component appear oddly if not provided

### ISSUE THREAD

**Issue by starpit** [kubeflow/pipelines#9708]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Using the recommended `kubectl apply -k`, i.e.
```shell
ENV=dev
CRDS="github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$KFP_VERSION"
RSRC="github.com/kubeflow/pipelines/manifests/kustomize/env/${ENV}?ref=$PIPELINE_VERSION"
$KUBECTL apply -k $CRDS
$KUBECTL wait --for condition=established --timeout=60s crd/applications.app.k8s.io
$KUBECTL apply -k $RSRC
```

*  KFP version: 2.0.0

*  KFP SDK version: 2.latest

### Steps to reproduce

Create a component.yaml with optional parameters such as:

```yaml
inputs:
  - {name: name, type: String, description: 'Name of Application.'}
  - {name: namespace, type: String, description: 'Namespace of Application.', optional: True}
  - {name: script, type: String, description: 'Name of your Python entry point file [defaults to {name}.py].', optional: True}
...
args: [
      -a, {inputValue: name},
      -n, {inputValue: namespace},
      -s, {inputValue: script}
    ]
```

And then use it in a pipeline:
```python
app = components.load_component_from_url('http://components.kubeflow/application/component.yaml')
...
 app(name="test4-step1")
```

the component impl (just a shell script, for now) echos the three argument values that were passed in.  looking at the test4-step1 pipeline-runner pod's logs, i see

```
name=test4-step1 namespace={{$.inputs.parameters['namespace']}} script={{$.inputs.parameters['script']}}
```

i.e. the not-provided optional parameters appear with funky handlebar leftovers.

### Expected result

Not-provided optional parameters should have null or empty-string values?

### Materials and Reference

---

Impacted by this bug? Give it a 👍.
