### ISSUE TITLE
[bug] runtimeValue constant not correct when concatenating parameters with file components

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9709]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)? manifest

*  KFP version: 2.0.0-rc.1

*  KFP SDK version: 2.0.0

#### `component.yaml`
```yaml
name: echo variable
description: pass

inputs:
- {name: variable, type: String}

implementation:
  container:
    image: python:3.10
    command:
    - echo
    args:
    - {inputValue: variable}
```

#### `pipeline.py`

```
from kfp.components import load_component_from_file
import kfp.dsl as dsl

echo = load_component_from_file("component.yaml")

@dsl.pipeline
def pipeline(
        variable_a: str = "hello",
        variable_b: str = "world",
):
    echo(variable=f'{variable_a} {variable_b}')

```

### Expected result

`hello world` would expected but got `{{$.inputs.parameters['pipelinechannel--variable_a']}} {{$.inputs.parameters['pipelinechannel--variable_b']}}
`

### Materials and reference

This is working file when using function components.

### Labels

/area backend
/area sdk

/area components

---

Impacted by this bug? Give it a 👍.
