### ISSUE TITLE
[feature] request a minimum amount of GPU VRAM for scheduling 

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9880]
### Feature Area

/area sdk

### What feature would you like to see?

When using the GPU Operator a lot of labels are generated[^1] to the nodes such as:
- `nvidia.com/gpu.memory` (Integer) 
- `nvidia.com/cuda.runtime.major`  (Integer)
etc..

It is possible in Kubernetes to add nodeAffinity with comparaison (greater, lower). The following syntax can be used for a pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.memory
            operator: Gt
            values:
            - 50
...
```

This would allows to specify the minimum amount of memory required, or the minimum cuda version, or the interval allowed.
The kfp[kubernetes] package have the `add_node_selector` function, that could (probably?) be extended to support this ?

---

Love this idea? Give it a 👍. 

[^1]: [Generated labels](https://github.com/NVIDIA/gpu-feature-discovery#generated-labels)
