### ISSUE TITLE
[backend] Persistence agent failing `kubeflow-pipeline-mkp-test`

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#9904]
### Environment

Currently `/test kubeflow-pipeline-mkp-test` is failing on HEAD.

### Steps to reproduce

In https://github.com/kubeflow/pipelines/commit/cb18d00bbbaed9cd77fc50dce739ed62c72b2356#diff-7df17678529866306ef6665ffbeeda377a1e869aca24856f7cf8a99891877fe8, service account token projection is introduced to enable Auth. However, it is failing the `kubeflow-pipeline-mkp-test` test because persistent agent is unable to find the service account token. Error message as below:

![image](https://github.com/kubeflow/pipelines/assets/37026441/fe516db0-f9eb-4613-86ad-51bd81bf10e4)

cc @difince @chensun 

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
### Exploration

I granted `roles/iam.serviceAccountTokenCreator` to the GCE default service account: https://cloud.google.com/iam/docs/service-account-permissions#token-creator-role, and retried the mkt-test. If this permission unblocks the test, then we will need to do one of the followings:

1. Make SA token requirement configurable (which means it can become optional), it allows us to exclude volume token projection for KFP standalone mode. We still need to clearly document the permission needed in the full kubeflow mode.
2. Update all existing clusters to grant this additional permission. Put up a warning to all users about this breaking change and how should they unblock the KFP deployment. Update documentations for KFP standalone and full Kubeflow.

**Comment by difince** [comment]
From the log message, it looks like in GCE the SA token hasn't been created. 
I would like to clearly state that in the current (the new) implementation, PA( Persistence Agent) authentication is not related to the multiuser mode at all. No matter the multiuser mode, PA is the only one that has the permissions and the right identity to call these two endpoints (no matter the namespace the reported workflow belongs to). 
As I do not have any knowledge of GCE .. I will totally count on your decision and if really needed I will make it configurable ..

**Comment by juliusvonkohout** [comment]
Yes, in a normal kubeflow there is a serviceaccount

```
        volumeMounts:
          - mountPath: /var/run/secrets/kubeflow/tokens
            name: persistenceagent-sa-token
      serviceAccountName: ml-pipeline-persistenceagent
      volumes:
        - name: persistenceagent-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: persistenceagent-sa-token
                  expirationSeconds: 3600
                  audience: pipelines.kubeflow.org
```

no such file looks like a GKE specific issue.

Can you check manually whether `/var/run/secrets/kubeflow/tokens` exists in the pod? `ls -lah` recursively for that directory tree might help
