### ISSUE TITLE
Usage of Kubeflow Pipelines v2

### ISSUE THREAD

**Issue by petrpechman** [kubeflow/pipelines#9970]
Hello, 

we have upgraded our Kubeflow Pipelines to version 2.0.1. We are now having a lot of trouble rewriting our code from version 1.8. We are missing the following features (maybe we just didn't find them in v2):

- set gpu resources (.set_gpu_limit())
- mount hostPath (.add_volume(), add_volume_mount())
- .set_security_context()

We want to train on multiple gpus, so we need to set gpu and cpu resources, connect network data storage, and so on.
Is Kubeflow Pipelines v2 good for us? Are these features planned in version 2? Or should we still use Kubeflow Pipelines 1.8?

**Comment by chensun** [comment]
> set gpu resources (.set_gpu_limit())

`set_gpu_limit()` has been renamed to [`set_accelerator_limit`](https://kubeflow-pipelines.readthedocs.io/en/sdk-2.0.1/source/dsl.html?h=set_acc#kfp.dsl.PipelineTask.set_accelerator_limit) so that is covers both GPU and TPU (on Vertex). Meanwhile, `set_gpu_limit` still exists but gives you a deprecation warning and calls into `set_accelerator_limit` under the hood.

> mount hostPath (.add_volume(), add_volume_mount())

Volume mount has been moved into an extension package: 
https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/

> .set_security_context()

KFP v2 doesn't have this feature parity yet. My advice would be submitting a separate feature request with the description of your use case.

**Comment by C-Jaewon** [comment]
@chensun Is there a way to use data stored on Nas??

**Comment by chensun** [comment]
> @chensun Is there a way to use data stored on Nas??

Kubeflow Pipelines user code is running in a container inside a cluster, as long as you can set up a solution for cluster containers to access NAS, KFP doesn't pose additional barrier.

**Comment by petrpechman** [comment]
To use Nas I have to do for exmple this:
```
volume = k8s_client.V1Volume(name='mounted', host_path={'path': '/mnt'})
volume_mount = k8s_client.V1VolumeMount(name='mounted', mount_path='/mnt')
task.add_volume(volume).add_volume_mount(volume_mount)
```
How can I do this exactly in v2 or is there any other way how to do that?
I found only how to mount PVC in [kfp-kubernetes](https://kfp-kubernetes.readthedocs.io/en/kfp-kubernetes-1.0.0/index.html) but not  how to mount Nas.

Thank you

**Comment by C-Jaewon** [comment]
![image](https://github.com/kubeflow/pipelines/assets/20211880/264ef11c-e2ca-4bb9-b46f-18b53ca9e1c9)
I want to mount 192.168.0.97:/volume1/USER_SHARE as /home/jovyan/katib-volume
but unable to mount

**Comment by C-Jaewon** [comment]
@petrpechman 
pv.yaml
```
# make Pv

apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-data-vol
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-csi
  mountOptions:
    - defaults
  nfs:
    path: /volume1/tt
    server: 192.168.0.98
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: admin
  name: train-data-vol
spec:
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
```
Create pv and pvc and execute the command below.
kubectl apply -f pv.yaml
kubectl apply -f pvc.yaml

You can check the mount results in the kubeflow volume.
